UserForm.js
This implements Stripes-Form on the UserForm.
=> Added stripes-form to UserForm

CHANGELOG.md, LoanActionsHistory.js, LoansHistory.js, UserLoans.js, ViewUser.js, package.json
This PR also upgrades **ui-users** to the newest okapi interfaces: 
- users (14.0)
- circulation (2.0)
- loan-storage (3.0)
=> Connect to Loan Actions API. Fixes UIU-103

CHANGELOG.md, LoanActionsHistory.js, LoansHistory.js, UserLoans.js, ViewUser.js
Show "Open Loans" and "Closed Loans" tabs on the loan-list panes, and show a count of open and closed loans panes, linked to their respective tabs, from the user details pane.
=> Uiu 128 user loans

LoansHistory.js
Link the entire row, not just the text in the "Title" column, to the loan details. Fixes UIU-160.
=> Link entire row to loan-details. Fixes UIU-160

package.json
See https://issues.folio.org/browse/UIU-154 for details.
=> Add `addresstypes.collection.get` permission 

LoansHistory.js
=> Add renewals column. See UIU-128.

CHANGELOG.md, LoanActionsHistory.js, LoansHistory.js, ViewUser.js, package.json
This PR also upgrades `circulation` dependency to 2.1 and `loan-storage` to 3.1.
=> Display loan due date. Fixes UIU-171 

LoanActionsHistory.js
Show the Item's status, barcode, and return date on the loan details
modal. Link the barcode to the item detail page. Many other fields added
with "TODO" placeholder text.
=> more details on loan details pane. Refs UIU-177

LoansHistory.js
Use a DropdownButton to provide better formatting for the loan-actions
menu as shown in the screenshot attached to UIU-128.
=> format actions menu. Refs UIU-128

CHANGELOG.md, package.json
=> PR: Update permissions namespace

Users.js
modest tweaks to the `Notes` API now that all of its functionality has been consolidated in the soon-to-be-renamed `stripes-util-notes` repository.
=> updated Notes API

settings/index.js
=> Check new-style, not old-style permission names in settings

test/ui-testing/new_user.js, test/ui-testing/patron_group.js
Minor changes to testing patron groups and new users.
=> Updated some selectors to work with new layout.

Users.js, ViewUser.js, util.js
This PR fixes patron's name based on the feedback from Cate in UIU-215.
=> Adjust patron's name. Fixes UIU-215

Users.js
=> Change "User Status" filter to "Status". Fixes UIU-210

CHANGELOG.md, lib/RenderPermissions/RenderPermissions.js
Fixes the last part of UIU-250.
=> Sort existing permissions as well as available ones

lib/OpenLoans/OpenLoans.js, settings/permissions/PermissionSetDetails.js
(I first called this branch `lint`, but when I tried to push it, it turned out there was already a branch of that name. Not wanting to get sucked into dealing what whatever the heck its state is, I just picked a nonsense name for this temporary branch that exists only for a single commit.)
=> Fix ESLint errors, return code to clean state

test/ui-testing/patron_group.js
=> Increased wait time.

.eslintrc, CHANGELOG.md, settings/permissions/PermissionSetDetails.js, settings/permissions/PermissionSetForm.js, settings/permissions/PermissionSets.js
This PR should address [UIU-231](https://issues.folio.org/browse/UIU-231), [UIU-276](https://issues.folio.org/browse/UIU-276), and [UIU-165](https://issues.folio.org/browse/UIU-165).
=> Refactor permission sets. Fixes UIU-231.

Users.js, converters/address.js, lib/SearchAndSort/SearchAndSort.js, lib/SearchAndSort/index.js, package.json
That main functionality is now in a new component, `lib/SearchAndSort/SearchAndSort.js`, which does most of its own work but also relies on the parent component's `resources` and `mutator`, which are passed in. The eventual destiny of this component is to be pulled out of ui-users and into stripes-smart-components, where it will form the heart of all our search-and-sort-based modules (Users, Items, Instances, Requests, and no doubt many more to come), but there is a lot more work to be done before that can happen.
I am keen to get the present state merged as soon as possible, as the changes are so textually pervasive that every passing hour is an additional opportunity for a hideous merge-conflict to arise. I will continue working on this after the merge is done, but with less terror in …
=> Tentative merge of heart-surgery to extract main functionality

Users.js, lib/SearchAndSort/SearchAndSort.js
This PR together with the fix to mutations epic in `stripes-connect` https://github.com/folio-org/stripes-connect/pull/18 should make it work with `mutators`.
=> Refactor user create. Fixes UIU-301

Users.js, lib/SearchAndSort/SearchAndSort.js
Most of the "users" references are now gone. Several remain.
=> Ongoing work on UIU-299

Users.js, ViewUser.js, lib/SearchAndSort/SearchAndSort.js
I think `Users.js` is now completely done. There is still a little bit of tidying up to be done in `SearchAndSort`, but I will merge that separately.
=> Pushing on with UIU-299

CHANGELOG.md, package.json
=> Add `optionalDependencies` on find-user plugin

settings/permissions/PermissionSets.js
putting STCOM-66 to bed with this.
=> Fix typo on entryLabel prop

UserForm.js, Users.js, ViewUser.js, lib/SearchAndSort/SearchAndSort.js
I think only two things remain to be done after this:
* Have `<SearchAndSort>` provide the generic part of record-creation, calling back to the invoker only for the additional operations that ui-users needs;
* Have `<SearchAndSort>` provide the close-full-record action for the view-component.
=> Ongoing work on UIU-303

package.json
=> Upgrade stripes-smart-components dependency to v1.2.0

CHANGELOG.md, Users.js, package.json
Depends on `stripes-smart-components` v.1.3.0.
Fixes UIU-333. See comments on UISE-13 for motivation.
=> Use the URL parameter `query` rather than `search`

ViewUser.js, lib/RenderPermissions/RenderPermissions.js, lib/ViewSections/ContactInfo/ContactInfo.js, lib/ViewSections/ExtendedInfo/ExtendedInfo.js, lib/ViewSections/ProxyPermissions/ProxyPermissions.js, lib/ViewSections/UserInfo/UserInfo.js, lib/ViewSections/UserLoans/UserLoans.js
I changed some minor things - mostly Accordion related to fit the accordions to the new changes in that component.
=> Bug fixes and changes

LoanActionsHistory.js, data/loanActionMap.js, lib/ClosedLoans/ClosedLoans.js, lib/OpenLoans/OpenLoans.js, util.js
Backed out code for Item status formatter. Status is being set within requests module when request is created.
=> UIU-346 Loans Detail: Item status formatter

LoanActionsHistory.js
Updated item status to show loan action history. Prior item was only showing current status for each  action item. 
@MikeTaylor , appreciate if you can merge. Thanks Mark
=> UIU-346 Updated item status to show loan action history.

LoansHistory.js, ViewUser.js, lib/OpenLoans/OpenLoans.js, lib/ViewSections/UserLoans/UserLoans.js
In this pull request I have primarily worked on fitting the Users-app to the new PaneHeader component and also updated some icons to use IconButton.
(There might be more stuff that needs adjustment. This will come in another pull request)
=> Updating to fit new PaneHeader

LoanActionsHistory.js
UIU-248 Updated view with resourceShouldRefresh. Tested both with boolean and a function. The function should return a boolean. This allows for custom function on whether or not to refresh dataset.
@MikeTaylor @mkuklis  This is related to pull request with STCON-39. This allow for the detail loan action view to refresh. This code is dependent on STCON-39 pull request.
=> UIU-248 Updated view with resourceShouldRefresh.

CHANGELOG.md, ViewUser.js, withProxy.js
Fixes [UIU-363](https://issues.folio.org/browse/UIU-363).
=> Hide proxy section if user lacks permission to see it. Fixes UIU-363.

CHANGELOG.md, data/contactTypes.js
Fixes [UIU-261](https://issues.folio.org/browse/UIU-261).
=> remove phone and mobile-phone as preferred contact options. Fixes UIU-261

CHANGELOG.md, Users.js, data/contactTypes.js
Fixes [UIU-365](https://issues.folio.org/browse/UIU-365), [UIU-366](https://issues.folio.org/browse/UIU-366).
=> sort fields on user-edit screen. Fixes UIU-365, UIU-366

CHANGELOG.md, lib/ClosedLoans/ClosedLoans.js, lib/OpenLoans/OpenLoans.js
Refs [STRIPES-482](https://issues.folio.org/browse/STRIPES-482).
=> Favor 'Link to' over 'a href'. Refs STRIPES-482

lib/ClosedLoans/ClosedLoans.js, lib/OpenLoans/OpenLoans.js
Refs [STRIPES-482](https://issues.folio.org/browse/STRIPES-482).
=> prune dead code from factoring out 'a href...' Refs STRIPES-482

CHANGELOG.md, ViewUser.js
Scenario 1 in [UIU-143](https://issues.folio.org/browse/UIU-1433), [UIU-230](https://issues.folio.org/browse/UIU-230).
=> unique URLs for open-, closed-loans. Refs UIU-143, UIU-230.

CHANGELOG.md, lib/ViewSections/UserLoans/UserLoans.js
Fixes Scenario 2 in [UIU-143](https://issues.folio.org/browse/UIU-143), [UIU-230](https://issues.folio.org/browse/UIU-230).
=> Links instead of buttons for loan-count links. Fixes UIU-143, UIU-230

CHANGELOG.md, LoanActionsHistory.js, LoansHistory.js, ViewUser.js, lib/ViewSections/UserLoans/UserLoans.js
Fixes [UIU-145](https://issues.folio.org/browse/UIU-145).
=> loan details page has unique URL. Fixes UIU-145

Users.js
Resolves UICHKOUT-46:
This passes onComponentWillUnmount forward into the search and sort component. Depends on other PRs: [ui-checkout](https://github.com/folio-org/ui-checkout/pull/55), [ui-plugin-find-user](https://github.com/folio-org/ui-plugin-find-user/pull/10), [stripes-smart-components](https://github.com/folio-org/stripes-smart-components/pull/80)
=> Uichkout 46

converters/address.js, package.json
=> Fix ESLint error in converters/address.js

CHANGELOG.md, lib/ProxyGroup/ProxyEditList/ProxyEditList.css, lib/ProxyGroup/ProxyEditList/ProxyEditList.js, lib/ProxyGroup/ProxyViewList/ProxyViewList.css, lib/ProxyGroup/ProxyViewList/ProxyViewList.js
Refs [UX-115](https://issues.folio.org/browse/UX-115)
=> Additional 'No proxies/No sponsors' formatting. Refs UX-115

CHANGELOG.md, LoanActionsHistory.js, lib/ClosedLoans/ClosedLoans.js, lib/OpenLoans/OpenLoans.js
Fixes [UIU-368](https://issues.folio.org/browse/UIU-368).
=> rewire loan links from items to inventory. Fixes UIU-368

CHANGELOG.md, UserForm.js, Users.js, ViewUser.js, lib/EditSections/EditProxy/EditProxy.js, lib/ViewSections/ProxyPermissions/ProxyPermissions.js, lib/ViewSections/UserInfo/UserInfo.js, settings/PatronGroupsSettings.js, test/ui-testing/new_permission_set.js, test/ui-testing/new_user.js, test/ui-testing/patron_group.js, util.js
Fixes [UIU-370](https://issues.folio.org/browse/UIU-370) 
Makes lint happy.
=> Relabel elements in user details Proxy section. Fixes UIU-370

lib/Autocomplete/Autocomplete.css, lib/EditSections/EditProxy/EditProxy.js, lib/ViewSections/ProxyPermissions/ProxyPermissions.js
[https://issues.folio.org/browse/UIU-370](https://issues.folio.org/browse/UIU-370)
=> Fix labels. Part of UIU-370

CHANGELOG.md, constants.js, lib/ErrorModal/ErrorModal.js, lib/ErrorModal/index.js, lib/OpenLoans/OpenLoans.js, util.js, withRenew.js
Fixes [https://issues.folio.org/browse/UIU-405](https://issues.folio.org/browse/UIU-405)
=> Get fixed renewal period from loan policy. Fixes UIU-405.

Users.js, package.json
Fixes part of UIU-399.
(Also, get rid of the unused and misleading initialValue for the anointed resource.)
=> Show list of results when a filter is selected

CHANGELOG.md, constants.js, util.js, withRenew.js
[https://issues.folio.org/browse/UIU-415](https://issues.folio.org/browse/UIU-415)
=> Get rolling renewal period from loan policy. Fixes UIU-415.

CHANGELOG.md, LoanActionsHistory.js, lib/OpenLoans/OpenLoans.js, withRenew.js
Fixes [https://issues.folio.org/browse/UIU-395](https://issues.folio.org/browse/UIU-395).
=> Add renew button to loan details. Fixes UIU-395.

CHANGELOG.md, settings/permissions/PermissionSetForm.js, settings/permissions/PermissionSets.js
[https://issues.folio.org/browse/UIU-412](https://issues.folio.org/browse/UIU-412)
=> Make perm set title required. Fixes UIU-412.

CHANGELOG.md, UserForm.js
[https://issues.folio.org/browse/UIU-414](https://issues.folio.org/browse/UIU-414)
=> Fix address validation. Fixes UIU-414.

CHANGELOG.md, lib/ProxyGroup/ProxyEditList/ProxyEditList.js
=> Placeholder text when no "find-user" plugin

CHANGELOG.md, Users.js, package.json
Refs [STSMACOM-64](https://issues.folio.org/browse/STSMACOM-64)
=> let SearchAndSort derive things from packageInfo. Refs STSMACOM-64

CHANGELOG.md, package.json
=> Upgrade stripes-components dependency to v2.0.3

CHANGELOG.md, util.js, withRenew.js
[https://issues.folio.org/browse/UIU-429](https://issues.folio.org/browse/UIU-429)
=> Prevent renewal. Fixes UIU-429

CHANGELOG.md, constants.js, util.js, withRenew.js
[https://issues.folio.org/browse/UIU-428](https://issues.folio.org/browse/UIU-428)
=> Handle renew from current due date. Fixes UIU-428

CHANGELOG.md, LoanActionsHistory.js, ViewUser.js, lib/OpenLoans/OpenLoans.js
[https://issues.folio.org/browse/UIU-406](https://issues.folio.org/browse/UIU-406)
=> Add borrower name and patron group to loan details. Fixes UIU-406.

CHANGELOG.md, package.json
Makes filters work in nested apps.
Fixes UIU-430.
=> Bump stripes-components dependency to v2.0.5

CHANGELOG.md, Users.js, package.json
Refs [UIPFU-6](https://issues.folio.org/browse/UIPFU-6)
=> props.browseOnly may prevent user creation/editing. Refs UIPFU-6

CHANGELOG.md, util.js, withRenew.js
[https://issues.folio.org/browse/UIU-433](https://issues.folio.org/browse/UIU-433)
=> Get alternate fixed renewal period from loan policy. Fixes UIU-433

settings/PatronGroupsSettings.js
Resolves [UIU-420](https://issues.folio.org/browse/UIU-420)
Provides a validation function that ensures the presence of the group property
and passes this function into the EditableList.
=> Patron group settings validating presence of group

CHANGELOG.md, loanUtils.js, util.js, withRenew.js
Fixes [https://issues.folio.org/browse/UIU-434](https://issues.folio.org/browse/UIU-434) and [https://issues.folio.org/browse/UIU-435](https://issues.folio.org/browse/UIU-435)
=> Get alternate rolling renewal period from loan policy. Fixes UIU-434 and UIU-435.

CHANGELOG.md, package.json
... by using v3.1.1 or higher of stripes-connect.
Completes UIU-399.
=> Clear search results when query or filter is cleared

CHANGELOG.md, lib/EditablePermissions/EditablePermissions.js, settings/permissions/ContainedPermissions.js, settings/permissions/PermissionSetForm.css, settings/permissions/PermissionSetForm.js
Fixes [https://issues.folio.org/browse/UIU-410](https://issues.folio.org/browse/UIU-410) and [https://issues.folio.org/browse/UIU-404](https://issues.folio.org/browse/UIU-404).
=> Update new permission set detail record. Fixes UIU-410 and UIU-404.

util.js, withRenew.js
[https://issues.folio.org/browse/UIU-440](https://issues.folio.org/browse/UIU-440)
=> Use correct local time on open loans view. Fixes UIU-440.

CHANGELOG.md, lib/ClosedLoans/ClosedLoans.js, lib/OpenLoans/OpenLoans.js
Refs [UI-407](https://issues.folio.org/browse/UIU-407)
=> move item-details link to the options menu. Refs UI-407

CHANGELOG.md, UserForm.js
[https://issues.folio.org/browse/UIU-394](https://issues.folio.org/browse/UIU-394)
=> Enter key should not submit the user edit form. Fixes UIU-394.

lib/RenderPatronGroup/RenderPatronGroupNumberOfUsers.js, package.json, settings/AddressTypesSettings.js, settings/PatronGroupsSettings.js, test/ui-testing/patron_group.js
[This uses the new ControlledVocab functionality in this PR.](https://github.com/folio-org/stripes-smart-components/pull/118)
=> STCOM-228: Migrate PatronGroups and AddressTypes to ControlledVocab

CHANGELOG.md
Refs [UIU-416](https://issues.folio.org/browse/UIU-416)
=> changelogging for UIU-416: extract strings for translation

CHANGELOG.md, constants.js
[https://issues.folio.org/browse/UICIRC-53](https://issues.folio.org/browse/UICIRC-53)
=> Match interval period values with the values on the server. Refs UICIRC-53.

CHANGELOG.md, constants.js, loanUtils.js
[https://issues.folio.org/browse/UICIRC-53](https://issues.folio.org/browse/UICIRC-53)
=> Match periodId and profileId values with the values on the server. Refs UICIRC-53.

lib/Loans/OpenLoans/OpenLoans.js
- Added new columns call number, contributors
- Matrial type is added in paranthesis to the title
- Limit the number of contributors displayed to 2 and add a popover displaying the rest of them, on click
=> Add Call Number, Contributors and Material Type to Loans, refs UIU-397

settings/permissions/PermissionSetForm.js, translations/en.json
G3g i18n r4t is a p2n in t1e a1s.
Refs [UIU-416](https://issues.folio.org/browse/UIU-416)
=> correct translation key typos

CHANGELOG.md, LoanActionsHistory.js
https://issues.folio.org/browse/UIU-457
=> Update loan actions table after renew. Fixes UIU-457

settings/permissions/PermissionSetForm.js
https://issues.folio.org/browse/UIU-404
=> Align delete button. Part of UIU-404

CHANGELOG.md, UserForm.js, Users.js, lib/EditSections/EditExtendedInfo/EditExtendedInfo.js, lib/EditSections/EditUserInfo/EditUserInfo.js, translations/de.json, translations/en.json
If one is provided the other is required as well.
=> Make username and password optional. UIU-389

CHANGELOG.md, LoanActionsHistory.js
Fixes [UIU-471](https://issues.folio.org/browse/UIU-471).
=> handle metadata case insensitively. Fixes UIU-471.

CHANGELOG.md, LoanActionsHistory.js, package.json
Refs [UIU-471](https://issues.folio.org/browse/UIU-471)
=> Favor metadata over metaData. Refs UIU-471

CHANGELOG.md, Users.js
Fixes [UIU-481](https://issues.folio.org/browse/UIU-481)
=> fix patron group sort for English only. Fixes UIU-481

lib/ProxyGroup/ProxyItem/ProxyItem.js
=> UIU-202: Replaced hardcoded labels by i18n translation keys

CHANGELOG.md, lib/ProxyGroup/ProxyEditItem/ProxyEditItem.js, lib/ProxyGroup/ProxyEditList/ProxyEditList.js, lib/ProxyGroup/ProxyItem/ProxyItem.js, withProxy.js
https://issues.folio.org/browse/UIU-495
=> Use new proxyFor schema instead of meta. Fixes UIU-495.

lib/ProxyGroup/ProxyEditList/ProxyEditList.js
Refs [UIU-416](https://issues.folio.org/browse/UIU-416)
=> extract string for "+ New" proxy CRUD buttons

LoanActionsHistory.js, ViewUser.js, lib/ProxyGroup/ProxyEditList/ProxyEditList.js, lib/UserAddresses/UserAddresses.js, settings/permissions/PermissionSetForm.js, settings/permissions/PermissionSets.js, translations/en.json, withRenew.js
https://issues.folio.org/browse/UIU-416
=> UIU-416: i18n

constants.js
https://issues.folio.org/browse/UICIRC-66
=> Replace int values with string representations for renewFromOptions. Refs UICIRC-66.

LoansHistory.js, lib/ViewSections/UserLoans/UserLoans.js, translations/de.json, translations/en.json
https://issues.folio.org/browse/UICHKIN-28
The bug was opened in the wrong Jira repo.
=> UICHKIN-28: fix i18n bug

package.json
See [UIU-495](https://issues.folio.org/browse/UIU-495)
=> sync okapi users interface in concert with UIU-495

CHANGELOG.md, LoanActionsHistory.js, LoanActionsHistoryProxy.js, UserForm.js, Users.js, ViewUser.js, lib/EditablePermissions/EditablePermissions.js, lib/Loans/ClosedLoans/ClosedLoans.js, lib/Loans/OpenLoans/OpenLoans.js, lib/PatronGroupNumberOfUsers/PatronGroupNumberOfUsers.js, lib/ProxyGroup/ProxyEditItem/ProxyEditItem.js, lib/ProxyGroup/ProxyEditList/ProxyEditList.js, lib/ProxyGroup/ProxyItem/ProxyItem.js, lib/UserAddresses/UserAddresses.js, lib/ViewSections/UserLoans/UserLoans.js, settings/PatronGroupsSettings.js, settings/permissions/ContainedPermissions.js, settings/permissions/PermissionSetForm.js, settings/permissions/PermissionSets.js
Couple of commits here (at the moment) to make the changes easier to see in diff.
- The first one is the relevant one which removes the accrue-fees-to settings from the view/edit proxy/sponsor components.
- The second is from a run of jscodeshift to fix all the `react/sort-comp` linter errors.
=> UIU-525: Removed Accrue-Fees-To from proxy/sponsor UI

CHANGELOG.md, lib/Loans/OpenLoans/OpenLoans.js, withRenew.js
https://issues.folio.org/browse/UIU-552
=> Adjust renew error messages. Fixes UIU-552.

package.json
Interface provided by mod-feesfines. Towards FOLIO-1318.
=> Update okapiInterfaces to depend on `feesfines`.

CHANGELOG.md, ViewUser.js, translations/ui-users/en.json
https://issues.folio.org/browse/STSMACOM-113
=> Configure tags helper app in users. Part of STSMACOM-113.

lib/ProxyGroup/ProxyViewList/ProxyViewList.js, test/ui-testing/new_proxy.js, translations/ui-users/en.json
Thanks to @julianladisch for [pointing this out](https://issues.folio.org/browse/UIU-416?focusedCommentId=30145&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-30145).
=> UIU-416: translate ProxyViewList

lib/EditSections/EditExtendedInfo/EditExtendedInfo.js
Related to https://github.com/folio-org/stripes-smart-components/pull/192.
Prefer overriding `timeZone` over using `ignoreLocalOffset`.
=> Replace ignoreLocalOffset prop

lib/AddServicePointModal/AddServicePointModal.js, lib/EditSections/EditServicePoints/EditServicePoints.js, translations/ui-users/en.json
- Is-mandatory-asterisk didn't make sense on the view page.
- Wrong prop being set for the Modal titlebar.
=> Service Points: Fixed some labels

Users.js
Refs [UIU-400](https://issues.folio.org/browse/UIU-400)
=> wordsmith the filter label

lib/AddServicePointModal/AddServicePointModal.js, translations/ui-users/en.json
Added a little text til we swap the modal over to a SAS implementation that includes this functionality for us.
=> UIU-546 Service Points: Add number of service points found to modal

settings/FeeFinesTable/CopyModal.js, settings/FeeFinesTable/FeeFines.js, settings/OwnerSettings.js, settings/PaymentSettings.js, settings/RefundReasonsSettings.js, settings/WaiveSettings.js, translations/ui-users/en.json, util.js
Modify settings fee/fine section
=> Modify settings fee/fine section

Users.js, lib/Loans/ClosedLoans/ClosedLoans.js, lib/Loans/OpenLoans/OpenLoans.js, lib/Loans/components/ActionsBar/ActionsBar.css, package.json
https://issues.folio.org/browse/UIU-459
=> UIU-459: Export search results to CSV

package.json
https://issues.folio.org/browse/UIU-619
The actual permission gating via `IfPermission` is already in place so this just drops in neatly.
=> UIU-619: Added permission set to view a user's service points

CHANGELOG.md, ViewUser.js, package.json
https://issues.folio.org/browse/UIU-627
=> Bump circulation interface to v.4.0. Part of UIU-627

lib/Accounts/Actions/WaiveModal.js, lib/Accounts/Actions/WarningModal.js, lib/Accounts/ChargeFeeFine/Charge.js, lib/Accounts/ChargeFeeFine/ItemLookup.js, lib/Accounts/OpenAccounts/OpenAccounts.js
I'm adding 2 missing files from @DGB2018 to get the build working again. @DGB2018 is working to fix this.
=> Add missing files plus + lint

CHANGELOG.md, lib/Loans/ClosedLoans/ClosedLoans.js, package.json, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-463
=> Anonymize closed loans on demand. Fixes UIU-463.

lib/ProxyGroup/ProxyEditList/ProxyEditList.js, package.json
https://issues.folio.org/browse/STCOM-331
=> STCOM-331 Get Pluggable from stripes-core

lib/EditSections/EditContactInfo/EditContactInfo.js, lib/UserAddresses/UserAddresses.js, package.json
https://issues.folio.org/browse/STCOM-327
=> STCOM-327 Get AddressFieldGroup from stripes-smart-components

AccountsHistory.js, Users.js, package.json
https://issues.folio.org/browse/STCOM-332
=> STCOM-332 Get makeQueryFunction() from stripes-smart-components

settings/index.js
https://issues.folio.org/browse/STCOM-330
=> STCOM-330 Get Settings from stripes-smart-components

lib/EditSections/EditContactInfo/EditContactInfo.js
Regression from https://github.com/folio-org/ui-users/pull/508
=> Fix AddressEditList import

Users.js
Added AppIcon to the first column of the results list to make it match the design of this prototype:
https://ux.folio.org/universal-navigation/uxi-3/
=> Added app icon to the first column of the results list

AccountsHistory.js, CHANGELOG.md, ViewUser.js, lib/Accounts/Actions/Actions.js, lib/Accounts/Actions/PayModal.js, lib/Accounts/AllAccounts/AllAccounts.js, lib/Accounts/ChargeFeeFine/Charge.js, lib/Accounts/ChargeFeeFine/ChargeForm.js, lib/Accounts/ClosedAccounts/ClosedAccounts.js, lib/Accounts/Menu.js, lib/Accounts/OpenAccounts/OpenAccounts.js, package.json, translations/ui-users/en.json
Refs [UIU-635](https://issues.folio.org/browse/UIU-635), [UIU-645](https://issues.folio.org/browse/UIU-645)
=> UNAM UIU-635 and UIU-645

ViewUser.js
This PR adds a new `shouldRefresh` function from https://github.com/folio-org/stripes-connect/pull/62  to `selUser` resource in order to control when the user should be refreshed.
=> Update number of tags on the user's view

CHANGELOG.md, src/ViewUser.js, translations/ui-users/en.json
https://issues.folio.org/browse/STRIPES-558
=> STRIPES-558 Remove notes helper app

src/components/ProxyGroup/ProxyItem/ProxyItem.js
- make lint (jsx-one-expression-per-line) happy by breaking logic into multiple lines
=> Display the create date on the proxy detail panel, refs UIREQ-120

CHANGELOG.md, src/components/ProxyGroup/ProxyEditList/ProxyEditList.js
Refs [STCOM-385](https://issues.folio.org/browse/STCOM-385)
=> show `active` column in find-user popup

test/ui-testing/patron_group.js
The `title` attribute is being phased out so tests must hang off other
elements.
Refs [STCOM-296](https://issues.folio.org/browse/STCOM-296)
=> don't hang tests off title attribute

translations/ui-users/pt_BR.json
=> Update translation strings as of 20181112T160917

CHANGELOG.md, src/LoanActionsHistory.js
https://issues.folio.org/browse/UIU-715
=> Add loan policy name to loan details view. Fixes UIU-715.

CHANGELOG.md, src/LoanActionsHistory.js
https://issues.folio.org/browse/UIU-714
=> Refresh action details after renew. Fixes UIU-714.

CHANGELOG.md, src/ViewUser.js
https://issues.folio.org/browse/UIU-729
=> Set expired user status to inactive. Fixes UIU-729

CHANGELOG.md, src/Users.js
https://issues.folio.org/browse/UIU-733
=> Add sort by name to initial query resource. Fixes UIU-733

CHANGELOG.md, package.json, src/ViewUser.js, src/components/ViewSections/UserRequests/UserRequests.js, src/components/ViewSections/UserRequests/index.js, src/components/ViewSections/index.js, translations/ui-users/en.json
Fixes [UIU-677](https://issues.folio.org/browse/UIU-677)
=> Include "requests" accordion on user-details

package.json, src/AccountsHistory.js, src/UserForm.js, src/components/Accounts/ChargeFeeFine/ChargeForm.js, src/components/BulkRenewalDialog/BulkRenewInfo.js, src/components/BulkRenewalDialog/BulkRenewedLoansList.js, src/components/EditSections/EditServicePoints/EditServicePoints.js, src/components/EditablePermissions/EditablePermissions.js, src/settings/permissions/PermissionSetForm.js
See folio-org/stripes-components#743
=> update deprecated icon names

package.json, src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/OpenLoans/OpenLoans.js
https://issues.folio.org/browse/UIU-686
=> Hide link to item details if user doesn't have enough permissions. Part of UIU-686

CHANGELOG.md, src/components/EditablePermissions/EditablePermissions.js
https://issues.folio.org/browse/UIU-739
=> Fix permission menu after reopening. Fixes UIU-739

src/LoanActionsHistory.js
This PR refactors action history component in order to address renew issues found in UIU-686.
https://issues.folio.org/browse/UIU-686
=> Fix renew issue on loan details screen. Part of UIU-686

package.json, src/UserForm.js, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, src/components/EditSections/EditExtendedInfo/ResetPasswordControl/ResetPasswordControl.js, src/components/EditSections/EditExtendedInfo/ResetPasswordControl/ResetPasswordModal/ResetPasswordModal.js
[Edit User Detail Record: Connect a Reset Password Modal to BE](https://issues.folio.org/browse/UIU-735)
=> UIU-735 - connected reset password modal to BE

CHANGELOG.md, src/components/ViewSections/UserRequests/UserRequests.js
Fixes [UIU-690](https://issues.folio.org/browse/UIU-690)
=> pass user barcode to new requests

CHANGELOG.md, src/components/EditSections/EditUserInfo/EditUserInfo.js
Fixes [UIU-700](https://issues.folio.org/browse/UIU-700)
=> hide metadata on new-user form

src/ViewUser.js, src/components/EditSections/EditProxy/EditProxy.js, src/components/EditSections/EditServicePoints/EditServicePoints.js, src/components/EditSections/EditUserPerms/EditUserPerms.js, src/components/EditablePermissions/EditablePermissions.js, src/settings/permissions/PermissionSetForm.js
See https://github.com/folio-org/stripes-core/pull/503 and https://github.com/folio-org/stripes-core/pull/504
=> Get IfInterface and IfPermission from stripes-core

test/ui-testing/patron_group.js
* Correctly extract the UUID for the staff group.
* Use the updated icon-name to delete the test patron group.
=> fix patron group test

CHANGELOG.md, src/components/ErrorModal/ErrorModal.js, src/components/ProxyGroup/ProxyEditList/ProxyEditList.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-734
=> Prohibit adding user as a proxy or sponsor for themselves. Fixes UIU-734.

CHANGELOG.md, src/AccountActionsHistory.js, src/AccountsHistory.js, src/ViewUser.js, src/components/Accounts/AllAccounts/AllAccounts.js, src/components/PatronBlock/PatronBlockForm.js, src/components/PatronBlock/PatronBlockLayer.js, src/components/PatronBlock/PatronBlockMessage.js, src/components/PatronBlock/index.js, translations/ui-users/en.json
* Fix minor errors of fee/fine history and details. Fixes [UIU-238](https://issues.folio.org/browse/UIU-238), [UIU-239](https://issues.folio.org/browse/UIU-239).
=> Fix minor errors

src/AccountActionsHistory.js, src/components/Accounts/Actions/Actions.js, src/components/Accounts/Actions/CancellationModal.js, src/components/Accounts/Actions/CommentModal.js, src/components/Accounts/Actions/PayModal.js, src/components/Accounts/Actions/WaiveModal.js, src/components/Accounts/Actions/WarningModal.js, src/components/Accounts/Actions/modal.css, src/components/Accounts/ChargeFeeFine/FeeFineInfo.js, src/components/Accounts/ChargeFeeFine/ItemInfo.js, src/components/Accounts/ChargeFeeFine/ItemLookup.js, src/components/Accounts/Menu.js, src/components/EditSections/EditServicePoints/EditServicePoints.js, src/components/EditablePermissions/EditablePermissions.js, src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/OpenLoans/OpenLoans.js, translations/ui-users/en.json
According to [UIU-740](https://issues.folio.org/browse/UIU-740), all hardcoded strings should be internationalized using the react-intl pattern 
[React Intl docs](https://github.com/yahoo/react-intl/wiki)
=> UIU-740: Apply internationalization to all hardcoded strings (excluding Settings)

CHANGELOG.md, package.json, src/LoanActionsHistory.js, src/ViewUser.js, src/components/Loans/OpenLoans/OpenLoans.js, src/components/ViewSections/UserRequests/UserRequests.js, translations/ui-users/en.json
Hide request buttons and disable request links when user doesn't have permissions. 
https://issues.folio.org/browse/UIU-757
=> Hide request buttons and disable request links. Fixes UIU-757.

src/ViewUser.js
https://issues.folio.org/browse/UIU-741
=> Add extra permission check for PatronBlock. Part of UIU-741

package.json
<h1>Purpose</h1>
<li>To add the required permissions for reset password flow</li>
=> Add permissions for link generation permissions

CHANGELOG.md, src/components/Loans/ClosedLoans/ClosedLoans.js
We are adding:
* Add "all actions" permission from Closed Loans. Ref [UIU-867](https://issues.folio.org/browse/UIU-867).
=> Fix Fees/Fines 

src/LoanActionsHistory.js
=> UIU-786: Fix bug with query.

CHANGELOG.md, test/ui-testing/new_service_point.js, test/ui-testing/new_user.js, test/ui-testing/patron_group.js
Changes to the aria attributes in MCL must be reflected in the
integration tests as well.
Refs [UIU-880](https://issues.folio.org/browse/UIU-880), [STCOM-365](https://issues.folio.org/browse/STCOM-365)
=> integration tests must accommodate MCL aria changes

src/components/BulkOverrideDialog/BulkOverrideLoansList.js, src/components/BulkRenewalDialog/BulkRenewedLoansList.js, src/components/Loans/OpenLoans/helpers/isOverridePossible/overridePossibleMessages.js, translations/ui-users/en.json
Changed error messages according to backend changes. Also, UIU-724 was failing on tests and recreation of PR resolved this problem.
=> UIU-724.1: Show failure reason on bulk action confirmation modal

test/bigtest/interactors/users.js, test/ui-testing/new-permission-set.js, test/ui-testing/new-service-point.js, test/ui-testing/new-user.js, test/ui-testing/patron-group.js, test/ui-testing/test.js
* define selectors for all user filters in users interactor
* wait for elements before interacting with them in patron-group test
* rename all tests to kebab-case for consistency with platform-core
=> test cleanup

CHANGELOG.md, package.json, src/ViewUser.js
https://issues.folio.org/browse/UIU-889
=> Update circulation v7.0 and request-storage v3.0 OKAPI interfaces. Fixes of UIU-889.

translations/ui-users/en_US.json
=> Update translation strings as of 20190222T002228

translations/ui-users/en_US.json
=> Update translation strings as of 20190225T222207

translations/ui-users/en.json
Refs [UIU-891](https://issues.folio.org/browse/UIU-891)
=> add missing translation pair

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/zh_CN.json
=> Update translation strings as of 20190227T140407

CHANGELOG.md, src/settings/TransferAccountsSettings.js, src/settings/index.js, translations/ui-users/en.json
We are adding:
* Add CRUD Fee/Fine Transfer Accounts Settings. Ref [UIU-544](https://issues.folio.org/browse/UIU-544).
=> Add CRUD Fee/Fine Transfer Accounts

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/zh_CN.json
=> Update translation strings as of 20190327T174151

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeForm.js, src/settings/OwnerSettings.js, translations/ui-users/en.json
We are adding:
* UX Consistency Fixes for New Fee/Fine (aka Charge Manual Fee/Fine). Ref. [UIU-903](https://issues.folio.org/browse/UIU-903).
* Fix cannot delete Fee/Fine Owner message. Ref [UIU-841](https://issues.folio.org/browse/UIU-841).
=> Add change Fees/Fines

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/zh_CN.json
=> Update translation strings as of 20190405T144349

CHANGELOG.md, src/components/Accounts/AllAccounts/AllAccounts.js, src/components/Accounts/ClosedAccounts/ClosedAccounts.js, src/components/Accounts/Menu.js, src/components/Accounts/OpenAccounts/OpenAccounts.js, src/components/PatronBlock/PatronBlockModal.js, src/components/ViewSections/PatronBlock/PatronBlock.js
We are adding:
* Fix display when the patron has more than one block. Fix [UIU-804](https://issues.folio.org/browse/UIU-804).
* Fix comment snippet missing from Fee/Fine History. Fix [UIU-955](https://issues.folio.org/browse/UIU-955).
* Fix comment count wrong on Fee/Fine History. Fix [UIU-957](https://issues.folio.org/browse/UIU-957).
=> Fix bugs Fees/Fines

CHANGELOG.md, src/components/Accounts/Actions/Actions.js, src/components/PatronBlock/PatronBlockModal.js, src/components/ViewSections/PatronBlock/PatronBlock.js, translations/ui-users/en.json
* UX Consistency Fixes for Patron Blocks on Renewals pop-up. Ref [UIU-947](https://issues.folio.org/browse/UIU-947).
* Fix Fee/Fines Details "Created at". Fix [UIU-927](https://issues.folio.org/browse/UIU-927).
* Fix "All actions" permission to see Patron Block details. Fix [UIU-866](https://issues.folio.org/browse/UIU-866).
* Fix Patron block pop-up for Renewals. Fix [UIU-959](https://issues.folio.org/browse/UIU-959).
=> Task/bugs Fees/Fines

CHANGELOG.md, src/settings/PatronGroupsSettings.js
Fix the typo.
Fixes [UIU-806](https://issues.folio.org/browse/UIU-806)
=> send singular value to singular prop

src/ViewUser.js
1. On bugfest.folio.ebsco.com, with a user who has permission set folio-admin
2. Go to Check Out app
3. Bring up user
4. Check out an item to user
5. Using action menu, navigate to loan details
6. Exit loan details
7. Exit open loans
User info pane is wide enough to see key information about user
The resulting user info pane is overly narrow.
Commands:
* 		collapseAllSections:  "mod+alt+g"
* 		edit:  "mod+alt+e"
* 		expandAllSections:  "mod+alt+b"
* 		new:  "alt+n"
* 		save:  "mod+s"
* 		search:  "mod+alt+h"
=> UIU-909: Change HasCommand position.

CHANGELOG.md, src/LoanActionsHistory.js, src/components/Loans/OpenLoans/components/Modals/Modals.js
Send a valid sort clause.
Refs [UIU-869](https://issues.folio.org/browse/UIU-869)
=> correctly set sort clause

src/ViewUser.js, src/components/Loans/OpenLoans/components/Modals/Modals.js
Add permission check to hide dropdown with actions if a user doesn't have permission to use it.
=> UIU-915: Add permission check.

CHANGELOG.md, src/settings/CommentRequiredForm.js, src/settings/CommentRequiredSettings.js, test/bigtest/interactors/settings-comment.js, test/bigtest/network/factories/comments.js, test/bigtest/network/models/comments.js, test/bigtest/network/scenarios/comments.js, test/bigtest/tests/settings-comment-test.js
We adding:
Test to Comments section.
=> Test: Comments settings section

CHANGELOG.md, src/Users.css, src/Users.js
=> UIU-973: Add user status indication.

src/Users.js, src/reports/OverdueLoanReport.js, translations/ui-users/en.json
The label in the previous PR was wrong so just fixing it here.
=> Fix overdue loans report label. Part of UIU-983

CHANGELOG.md, src/settings/FeeFinesTable/Owners.js, src/settings/TransferAccountsSettings.js, test/bigtest/interactors/settings-transfers.js, test/bigtest/network/factories/transfers.js, test/bigtest/network/models/transfers.js, test/bigtest/network/scenarios/settings-feefine.js, test/bigtest/tests/settings-transfers-test.js
We are adding:
* Create BigTest for Transfer accounts Settings. Ref [UIU-1000](https://issues.folio.org/browse/UIU-1000).
* Fix "Shared" Fee/Fine Owner. Fix [UIU-989](https://issues.folio.org/browse/UIU-989).
* Fix "Last Updated" column. Fix [UIU-960](https://issues.folio.org/browse/UIU-960).
=> Create BigTest transfer accounts settings

CHANGELOG.md, src/AccountActionsHistory.js, src/AccountsHistory.js, src/components/Accounts/Actions/Actions.js, src/components/Accounts/Actions/TransferModal.js, src/components/Accounts/Actions/WarningModal.js, src/components/Accounts/AllAccounts/AllAccounts.js, src/components/Accounts/ClosedAccounts/ClosedAccounts.js, src/components/Accounts/Menu.js, src/components/Accounts/OpenAccounts/OpenAccounts.js, test/bigtest/interactors/user-transfer.js, test/bigtest/network/factories/accounts.js, test/bigtest/network/factories/feefineactions.js, test/bigtest/network/models/accounts.js, test/bigtest/network/models/feefineactions.js, test/bigtest/network/scenarios/transfers.js, test/bigtest/tests/user-transfer-test.js, translations/ui-users/en.json
We are adding:
* Create BigTest for Transfer fee/fine modal. Ref [UIU-1016](https://issues.folio.org/browse/UIU-1016).
=> Create BigTest for Transfer fee/fine modal

test/ui-testing/new-permission-set.js, test/ui-testing/new-user.js, test/ui-testing/patron-group.js
Try harder not to use nav-buttons.
Refs [UITEST-65](https://issues.folio.org/browse/UITEST-65)
=> avoid helpers.openApp; it uses navigation buttons

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/zh_CN.json
=> Update translation strings as of 20190523T143922

src/Users.js
https://issues.folio.org/browse/UIU-1011
=> Add permission required check for loans. Part of UIU-1011

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/zh_CN.json
=> Update translation strings as of 20190529T122422

CHANGELOG.md, src/components/Accounts/Actions/Actions.js, src/components/Accounts/ChargeFeeFine/Charge.js, src/components/Accounts/ChargeFeeFine/ChargeForm.js, src/components/Accounts/ChargeFeeFine/FeeFineInfo.js
We are adding:
* Fix fee/fine history display.
* Fix payments display.
=> Fix fee/fine history display

CHANGELOG.md, src/LoanActionsHistory.js, src/components/Loans/OpenLoans/components/Modals/Modals.js, test/bigtest/tests/user-edit-page-test.js
Reverts folio-org/ui-users#852
=> Revert "STSMACOM-152: Removed 'user'-prop from <ChangeDueDateDialog>"

translations/ui-users/pt_BR.json
=> Update translation strings as of 20190603T125055

CHANGELOG.md, src/AccountActionsHistory.js, src/components/Accounts/Actions/PayManyModal.js, src/components/Accounts/Actions/PayModal.js, src/components/Accounts/ChargeFeeFine/ChargeForm.js, src/components/ViewSections/PatronBlock/PatronBlock.js
* Fix sort patron blocks. Fix [UIU-868](https://issues.folio.org/browse/UIU-868).
* Fix notify patron to charge manual and pay modal. Fix [UIU-953](https://issues.folio.org/browse/UIU-953).
* Fix comment column size. Fix [UIU-954](https://issues.folio.org/browse/UIU-954).
=> Add fees/fines fixes

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/zh_CN.json
=> Update translation strings as of 20190606T155546

CHANGELOG.md, src/components/EditSections/EditExtendedInfo/CreateResetPasswordControl/CreateResetPasswordControl.js
https://issues.folio.org/browse/UIU-1066
=> Fix ability to edit users. Part of UIU-1066

CHANGELOG.md, src/AccountActionsHistory.js, src/AccountsHistory.js, src/ViewUser.js, src/components/Accounts/Actions/Actions.js, src/components/Accounts/Actions/PayManyModal.js, src/components/Accounts/Actions/PayModal.js, src/components/Accounts/Actions/TransferModal.js, src/components/Accounts/Actions/WaiveModal.js, src/components/Accounts/ChargeFeeFine/Charge.js, src/components/Accounts/ChargeFeeFine/ChargeForm.js, src/components/Accounts/ViewFeesFines/ViewFeesFines.js, src/settings/OwnerSettings.js
We are adding:
* Fixes fees/fines.
* Fix UX Consistency for New Fee/Fine. Fix [UIU-1052](https://issues.folio.org/browse/UIU-1052).
=> Add fee/fine fixes

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/zh_CN.json
=> Update translation strings as of 20190624T123511

src/Users.js, translations/ui-users/en.json
Reuse existing capitalized Active/Inactive translations.
=> UIU-894: Reuse existing capitalized Active/Inactive translations for the search filter

CHANGELOG.md, package.json, test/bigtest/interactors/fee-fine-history.js, test/bigtest/interactors/open-loans.js, test/bigtest/interactors/user-transfer.js, test/bigtest/tests/fee-fine-history-test.js, test/bigtest/tests/open-loans-test.js
https://issues.folio.org/browse/UIU-1088
=> Add missing permissions. Fixes UIU-1088

src/settings/permissions/PermissionSets.js
`EntryManager.entryLabel` requires a string, not a FormattedMessage.
=> provide correct prop-type entryLabel

package.json
https://issues.folio.org/browse/UIU-1088
=> Add missing permission. Part of UIU-1088

CHANGELOG.md, src/components/ProxyGroup/ProxyItem/ProxyItem.js
https://issues.folio.org/browse/UIU-924
=> Fix expiration date for sponsor and proxy. Fixes UIU-924.

package.json
https://issues.folio.org/browse/UIU-1088
=> Add more permissions to view requests. Part of UIU-1088

CHANGELOG.md, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, test/bigtest/interactors/open-loans.js, test/bigtest/tests/change-due-date-test.js
Cover some changes provided in scope of this [pull request](https://github.com/folio-org/stripes-smart-components/pull/572)
=> UIU-1070: Update tests to cover changes in due date modal in stripes-smart-components

src/components/ProxyGroup/ProxyItem/ProxyItem.js
More cleanup related to proxy's expiration date. 
https://issues.folio.org/browse/UIU-924
=> Cleanup expiration date. Part of UIU-924

package.json, src/Users.js
https://issues.folio.org/browse/UIU-1088
=> Adjust 'view requests' sub permissions. Part of UIU-1088

CHANGELOG.md, src/reports/OverdueLoanReport.js, translations/ui-users/en.json
Relates to [UIU-987](https://issues.folio.org/browse/UIU-987) story.
=> UIU-987: Extend overdue loans report with fine/fee field

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/zh_CN.json
=> Update translation strings as of 20190718T013203

src/components/ProxyGroup/ProxyEditItem/ProxyEditItem.js
https://issues.folio.org/browse/UIU-924
=> Fix proxy expiration date. Part of UIU-924

translations/ui-users/zh_CN.json
=> Update translation strings as of 20190718T220243

CHANGELOG.md, src/ViewUser.js, src/components/PatronBlock/PatronBlockForm.js, src/components/PatronBlock/PatronBlockLayer.js, src/components/PatronBlock/PatronBlockMessage.js, src/components/PatronBlock/PatronBlockModal.js, src/components/ViewSections/PatronBlock/PatronBlock.js, test/bigtest/interactors/manual-blocks.js, test/bigtest/network/factories/manualblocks.js, test/bigtest/network/models/manualblocks.js, test/bigtest/network/scenarios/manual-blocks.js, test/bigtest/network/serializers/manualblocks.js, test/bigtest/tests/manual-patron-blocks-test.js, test/bigtest/tests/manual-patron-loan-test.js
We are adding:
* Create BigTest for CRUD patron blocks. Refs [UIU-1003](https://issues.folio.org/browse/UIU-1003).
=> Add Patron Blocks BigTest

CHANGELOG.md, package.json, src/components/ViewSections/PatronBlock/PatronBlock.js
* Modify permission for patron blocks. Refs [UIU-728](https://issues.folio.org/browse/UIU-728).
=> Modify Patron Blocks permission

src/ViewUser.js, src/components/PatronBlock/PatronBlockForm.js, src/components/PatronBlock/PatronBlockLayer.js, src/components/PatronBlock/PatronBlockModal.js, test/bigtest/interactors/manual-blocks.js, test/bigtest/tests/manual-patron-blocks-test.js
https://issues.folio.org/browse/UIU-1141
=> Cleanup Patron Blocks. Part of UIU-1141

test/bigtest/interactors/manual-blocks.js, test/bigtest/tests/manual-patron-blocks-test.js, test/bigtest/tests/manual-patron-loan-test.js
https://issues.folio.org/browse/UIU-1141
=> Trying to fix patron blocks again. Part of UIU-1141

src/LoansHistory.css, src/LoansHistory.js
`<SegmentedControl>` is deprecated; replace it with `<ButtonGroup>`. This should help clean up the console a bit.
=> replace deprecated SegmentedControl component

src/components/PatronBlock/PatronBlockForm.js
I introduced a bug in he previous PR where it was not possible to unchecked previously checked checkboxes. This PR should address it.
=> Fix checkbox toggle. Part of UIU-1141

translations/ui-users/ar.json
=> Update translation strings as of 20190918T144452

package.json
Restores #969 by reverting #978.
=> Restore "UIU-1243: Update the circulation API to support changes in the rule editor"

translations/ui-users/ar.json
=> Update translation strings as of 20190927T125508

CHANGELOG.md, src/Users.js
Fix the mechanism for the accumulation of overdue loans in the CSV report according to the [story](https://issues.folio.org/browse/UIU-1286).
=> UIU-1286: Fix the accumulation of overdue loans in CSV report.

CHANGELOG.md, src/util.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-1018
=> Update sponsor and proxy labels. Part of UIU-1018

CHANGELOG.md, package.json, src/LoanActionsHistory.js, src/ViewUser.js
Implement view loans permission as part of [UIU-1083](https://issues.folio.org/browse/UIU-1083). This permission is only for view purposes and does not give the user the possibility to edit loans.
=> UIU-1083: Implement view loans permission

src/views/UserEdit/UserForm.js
Username should not start or end with whitespace, when user is creating 
In create user form, trim whitespaces from username, when submit button pressed
https://issues.folio.org/browse/UIU-1289
=> UIU-1289: Add trim method to username value

src/components/EditSections/EditProxy/EditProxy.js
If we need this prop in to add a proxy, we need this prop to add a
sponsor. HOW DID I MISS THIS THE FIRST TIME?!?
Refs [UIU-1313](https://issues.folio.org/browse/UIU-1313)
=> UIU-1313 restore initialValues to proxy AND sponsor

test/bigtest/network/factories/manualblocks.js
set expiration date to future in factory rather than hardcoded October 23rd 😆
=> fix patronBlocks tests... 

src/components/EditSections/EditProxy/EditProxy.js
=> "sponsors" is not a proptype

src/views/UserSearch/UserSearch.js
Me: Nightmare, please click a submit button.
Nightmare: I will click all the submit buttons!
Me: No, just the one please.
Nightmare: I will even click submit buttons that don't exist yet!
Me: What? No! Just this one. How is that even possible? Why would you--
Nightmare: Bwahahahah! :facepunch:
I SWEAR ON MY GRANDMOTHER'S GRAVE THIS IS TRUE:
If a nightmare test contains a click action on an element like
```
button[type=submit]
```
and later in the same test loads a different form which also includes a
similar element, the same action will be immediately invoked, i.e. the
second form will be immediately submitted. Does this make sense? No,
this does not make sense. It's like it holds the submit action in escrow
and applies to to all future submit buttons it may find, even those that
did not …
=> nightmare will kill a puppy unless submit buttons have ids

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/ru.json, translations/ui-users/zh_CN.json, translations/ui-users/zh_TW.json
=> Update translation strings as of 20191028T151017

package.json
Refs to the [UIU-1177](https://issues.folio.org/browse/UIU-1177).
=> UIU-1177: Remove view of users application from load edit permission

src/components/EditSections/EditExtendedInfo/RequestPreferencesEdit/RequestPreferencesEdit.js, src/customTypeValidators.js, src/shapes.js
##Purpose
Address type change causes an error. So this PR fixes it.
=> UIU-1155: Fix issue when address type change causes an error

src/components/EditSections/EditExtendedInfo/RequestPreferencesEdit/RequestPreferencesEdit.js
##Purpose
Avoid saving of the empty default address field.
##Screenshots
=> UIU-1155: Improve validation of default address field

src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js
https://issues.folio.org/browse/UIU-1181
=> UIU-1181: Apply permission check to loan policy menu item.

CHANGELOG.md, src/views/UserEdit/UserEdit.js
Add service points to the list in the modal. [Story](https://issues.folio.org/browse/UIU-1334).
**Screenshot**
=> UIU-1334: Add service points to user

test/bigtest/interactors/settings-feefine.js, test/bigtest/interactors/users.js, test/bigtest/tests/settings-manual-charges-test.js, test/bigtest/tests/settings-owners-test.js, test/bigtest/tests/settings-payments-test.js, test/bigtest/tests/settings-refunds-test.js, test/bigtest/tests/settings-transfers-test.js, test/bigtest/tests/settings-waives-test.js, test/bigtest/tests/user-view-page-test.js, test/bigtest/tests/users-show-all-test.js
Wait for the page to load before attempting to access the items on it.
Refs [FOLIO-2360](https://issues.folio.org/browse/FOLIO-2360)
=> FOLIO-2360 be patient before testing

CHANGELOG.md, src/components/UserDetailSections/UserRequests/UserRequests.js
https://issues.folio.org/browse/UIU-1370
=> UIU-1370: Use user's id instead of a barcode when navigating to requests module.

translations/ui-users/pt_BR.json
=> Update translation strings as of 20191122T195518

src/components/EditSections/EditExtendedInfo/RequestPreferencesEdit/RequestPreferencesEdit.js, src/components/UserDetailSections/ExtendedInfo/components/RequestPreferencesView/RequestPreferencesView.js, test/bigtest/interactors/user-form-page.js, test/bigtest/interactors/user-view-page.js, test/bigtest/network/config.js, test/bigtest/network/factories/addresse.js, test/bigtest/network/factories/request-preferences.js, test/bigtest/network/models/request-preferences.js, test/bigtest/tests/user-create-page-test.js, test/bigtest/tests/user-edit-page-test.js, test/bigtest/tests/user-view-page-test.js
https://issues.folio.org/browse/UIU-1328
Cover with tests request preferences section.
Requires PR https://github.com/folio-org/stripes-smart-components/pull/670
=> Request preferences tests

CHANGELOG.md, src/components/data/static/contactTypes.js, src/views/UserEdit/UserEdit.js
https://issues.folio.org/browse/UIU-1385
=> UIU-1385: add defaults for new user creation

CHANGELOG.md, src/components/PatronBlock/PatronBlockLayer.js, src/components/UserDetailSections/PatronBlock/PatronBlock.js, src/routes/PatronBlockContainer.js
https://issues.folio.org/browse/UIU-1397
=> UIU-1397: Display correct user block on the edit form

CHANGELOG.md, src/components/PatronBlock/PatronBlockForm.js, src/components/PatronBlock/PatronBlockLayer.js
https://issues.folio.org/browse/UIU-1420
=> UIU-1420: Add record last updated and created back to manual patron block. 

src/views/AccountsListing/AccountsListing.js
https://issues.folio.org/browse/UIU-1412
=> UIU-1412: Go back to user view when accounts listing is closed

CHANGELOG.md, src/views/UserDetail/UserDetail.js, test/bigtest/interactors/user-form-page.js
Fix bud with wrong address type displaying on User Details page, now it shows UUID
https://issues.folio.org/browse/UIU-1404
=> UIU-1404: Fix bug with uncorrect displaying of address type

CHANGELOG.md, src/components/Accounts/Actions/Actions.js, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js
Passing `notify` field when ActionModal of fee/fine payment is submitted, or `Charge`/`Charge with pay` button is pressed - `notify` value is also passing to BE
---
https://issues.folio.org/browse/UIU-1413
=> UIU-1413: add state `notify` value

CHANGELOG.md, src/routes/LoansListingContainer.js
https://issues.folio.org/browse/UIU-1046
=> UIU-1046: Refresh list of loans after anonymization

CHANGELOG.md, src/components/data/static/contactTypes.js, src/views/UserEdit/UserEdit.js
Provide correct defaults when creating new users. 
Refs [UIU-1385](https://issues.folio.org/browse/UIU-1385)
=> UIU-1385 add defaults for new user creation

src/views/LoanDetails/LoanDetails.js, src/views/LoansListing/LoansListing.js
UIU-1377 didn't make it to the q4 release but without it the issue reported in UIU-1412 came back. We are bringing some of the changes from UIU-1377 in order to address it.
https://issues.folio.org/browse/UIU-1412
=> UIU-1412 - replace history.goBack with actual path

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIU-1440
=> UIU-1440: Update circulation okapiInterface to version 9.0

src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js
Fix provides sending correct value of `notify` checkbox for each action type (charge and pay) to BE
https://issues.folio.org/browse/UIU-1413
=> UIU-1413: Send proper value of notify field

src/views/UserSearch/UserSearch.js
I noticed that some of my work in UIU-1352 got removed after I merged the latest master. In this PR I re-added those changes.
- Added collapse button in filter pane
- Added translated strings
=> UIU-1352: Follow up updates

CHANGELOG.md, src/constants.js, src/routes/UserSearchContainer.js, src/routes/filterConfig.js, src/views/UserSearch/Filters.js, src/views/UserSearch/UserSearch.js, test/bigtest/interactors/user-view-page.js, test/bigtest/interactors/users.js, test/bigtest/tests/users-show-all-test.js, translations/ui-users/en.json
Add ability to filter users by tags.
https://issues.folio.org/browse/UIU-1448
=> UIU-1448 - Filter Users by Tags

CHANGELOG.md, src/views/UserDetail/UserDetail.js
https://issues.folio.org/browse/UIU-1435
=> UIU-1435: Show edit button only if user has 'Can edit user profile' permission.

translations/ui-users/ur.json
=> Update translation strings as of 20200217T172736

CHANGELOG.md, src/components/Loans/OpenLoans/OpenLoansControl.js, src/components/Wrappers/withRenew.js, src/views/LoanDetails/LoanDetails.js, test/bigtest/interactors/open-loans.js, test/bigtest/tests/bulk-loan-renew-test.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-1299
=> UIU-1299: Execute loan renew in sequence

src/views/UserSearch/UserSearch.js, test/bigtest/tests/users-show-all-test.js
Reset query param when search control is empty.
https://issues.folio.org/browse/UIU-1473
=> UIU-1473 - Unable to clear search

CHANGELOG.md, src/views/UserEdit/UserForm.js
Fix active/inactive state for Save button
https://issues.folio.org/browse/UIU-1194
=> UIU-1194 - fix active/inactive state for Save button

package.json
- Add ability to control who at the library has the ability to CRUD custom fields
=> UIU-1492 Create UI permissions for Settings > Users > Custom Fields CRUD

src/components/Wrappers/withRenew.js
https://issues.folio.org/browse/UIU-1299
This PR passes `silent` option to the bulk renew post mutator in order to turn off the auto refreshes for all but last renew.
=> UIU-1299: Pass silent during bulk renew

package.json, src/index.js, src/routes/EditCustomFields.js, src/settings/CustomFieldsSettings.js, test/bigtest/interactors/settings-custom-fields.js, test/bigtest/tests/settings-custom-fields-test.js
- Apply permission restrictions to Users > Custom Fields
=> UIU-1492 Custom fields: Create UI permissions for Settings > Users > Custom Fields CRUD

src/routes/EditCustomFields.js, src/settings/CustomFieldsSettings.js
- Correct naming of Custom Fields delete permission
=> UIU-1492 Fix incorrect custom fields delete permission name

translations/ui-users/fr_FR.json, translations/ui-users/ru.json
=> Update translation strings as of 20200316T134017

src/views/UserEdit/UserEdit.js
Bug fixing: Can't remove permission while also adding one from popup
https://issues.folio.org/browse/UIU-1494
**Before**
**After**
=> UIU-1494: Make updatePermissions function async

src/views/UserDetail/UserDetail.js, src/views/UserSearch/UserSearch.js, test/bigtest/interactors/user-view-page.js, test/bigtest/tests/user-view-page-test.js
- Move "New" button to the actions dropdown
- Remove "Actions" menu and "Edit" icon and replace it with "Edit" button
https://issues.folio.org/browse/UIU-1471
=> UIU-1471 - Paneheader Actions updates

src/components/Accounts/ViewFeesFines/ViewFeesFines.js, src/views/AccountDetails/AccountDetails.js
Fix formatting issue for material type value.
https://issues.folio.org/browse/UIU-1541
=> UIU-1541 - Fees/Fines History and Fee/Fine Details displaying "undefined" as Instance (Material Type)

CHANGELOG.md, package.json, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/views/LoanDetails/LoanDetails.js
https://issues.folio.org/browse/UIU-1266
Adds permission to claim items returned and hides the claim action/button if user does not have the correct permission.
=> UIU-1266: Add permission to claim items returned

src/settings/CommentRequiredSettings.js
Fixed incorrect using local resources in the manifest.
https://issues.folio.org/browse/UIU-1544
=> UIU-1544 - Unable to SAVE Comment Required setting change

src/views/AccountDetails/AccountDetails.js
Fix incorrect close behavior for account details form.
https://issues.folio.org/browse/UIU-1542
=> UIU-1542 - Cannot get back to user app without closing browser

src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/Accounts/ChargeFeeFine/ChargeForm.js
Properly detect location name when create a new fee fine via checkout page and send it to BE.
https://issues.folio.org/browse/UIU-1554
=> UIU-1554 - Location not displayed and/or saved with fee/fine (when fee/fine created at check-in)

src/views/AccountDetails/AccountDetails.js
Update link to inventory item page.
https://issues.folio.org/browse/UIU-1553
=> UIU-1553 - Item record not found when clicking on link from Fee/Fine Details

CHANGELOG.md, src/components/BulkOverrideDialog/BulkOverrideLoansList.js, src/components/BulkRenewalDialog/BulkRenewedLoansList.js, src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/OpenLoans/helpers/getListDataFormatter.js, src/views/LoanDetails/LoanDetails.js
https://issues.folio.org/browse/UIU-1515
We still had couple places with the old imports to stripes util. This PR should fix it.
=> UIU-1515: Fix import path to stripes util

src/components/Accounts/ViewFeesFines/ViewFeesFines.js, src/views/AccountDetails/AccountDetails.js
Check for presence of values of values before displaying them.
Refs [UIU-1541](https://issues.folio.org/browse/UIU-1541)
=> UIU-1541 - fixed formatting issue for material type value (#1220)

translations/ui-users/ar.json, translations/ui-users/ru.json, translations/ui-users/ur.json
=> Update translation strings as of 20200406T162815

src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/Accounts/ChargeFeeFine/ChargeForm.js
Properly detect location name when creating a new fee/fine via checkout page
and include that in the submission.
=> UIU-1554 send location when creating fee/fine from checkout

src/views/AccountDetails/AccountDetails.js
Provide correct link to inventory item page.
Refs [UIU-1553](https://issues.folio.org/browse/UIU-1553)
=> UIU-1553 correct link to inventory

src/components/UserDetailSections/ExtendedInfo/components/RequestPreferencesView/RequestPreferencesView.css
https://issues.folio.org/browse/UIU-779 …
=> UIU-779 fix request preferences view styles

translations/ui-users/pt_BR.json
=> Update translation strings as of 20200416T214343

src/components/ProxyGroup/ProxyEditList/ProxyEditList.css, src/components/UserDetailSections/ExtendedInfo/components/RequestPreferencesView/RequestPreferencesView.css
https://issues.folio.org/browse/UIU-779 …
=> UIU-779 Remove hardcoded font sizes

CHANGELOG.md, src/components/data/static/loanActionMap.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-1603
=> UIU-1603: Add translation for closed loan

CHANGELOG.md, package.json
As requested by folio-org/mod-circulation-storage#242
https://issues.folio.org/browse/UIU-1598
=> UIU-1598: support loan-storage 7.0

src/settings/permissions/PermissionSetForm.css, src/settings/permissions/PermissionSetForm.js
https://issues.folio.org/browse/UIU-1587 …
=> UIU-1587 Settings > Users > Create/Edit Permission set fix footer view

CHANGELOG.md, src/routes/UserSearchContainer.js, src/views/UserEdit/UserEdit.js, test/bigtest/interactors/manual-blocks.js
Preserve filters after user record is successfully updated:
https://issues.folio.org/browse/UIU-1604
=> UIU-1604: Preserve filters after user is updated

CHANGELOG.md, src/settings/CommentRequiredForm.js
https://issues.folio.org/browse/UIU-1589
=> UIU-1609 Settings > Users > Fee/Fine > Comment | Move Save button to the footer

CHANGELOG.md, src/settings/FeeFineSettings.js, src/settings/OwnerSettings.js, src/settings/PaymentSettings.js, src/settings/RefundReasonsSettings.js, src/settings/TransferAccountsSettings.js, src/settings/WaiveSettings.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-1611
=> UIU-1611 Settings > Users > Fee/Fine pages > replace black asterisk with red asterisk

test/bigtest/tests/open-loans-test.js
This test pokes at stripes-components functionality and should be
addresed there instead.
=> don't do stripes-components tests here

src/settings/sections.js, test/bigtest/tests/settings-custom-fields-test.js, test/bigtest/tests/user-edit-page-test.js
Enable Custom Fields routes and tests after resolving issue with User schema deserialization
[MODUSERBL-89](https://issues.folio.org/browse/MODUSERBL-89)
=> MODUSERBL-89: Enable Custom Fields routes and tests

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/he.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/ja.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/ru.json, translations/ui-users/ur.json, translations/ui-users/zh_CN.json, translations/ui-users/zh_TW.json
=> Update translation strings as of 20200521T142352

translations/ui-users/ar.json
=> Update translation strings as of 20200522T132417

src/components/ModalContent/ModalContent.js
It looks like while working on UIU-1215 I forgot to use the correct import for `loanActionMutators`.
This PR should address that.
=> UIU-1215: Use correct import 

CHANGELOG.md, package.json, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, test/bigtest/helpers/setup-application.js, test/bigtest/tests/mark-as-missing-test.js, test/bigtest/tests/patron-blocks/settings-conditions-form-test.js
Add permission to mark a claimed item as missing.
https://issues.folio.org/browse/UIU-1268
=> UIU-1268: Add permission to mark a claimed item as missing.

CHANGELOG.md, src/components/data/static/loanActionMap.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-1643
=> UIU-1643: Adds additional statuses to loan action map

CHANGELOG.md, src/components/UserDetailSections/UserInfo/UserInfo.js, test/bigtest/helpers/turn-off-warnings.js, test/bigtest/index.js, test/bigtest/interactors/FindUserInstances.js, test/bigtest/interactors/closed-loans.js, test/bigtest/interactors/find-user.js, test/bigtest/interactors/open-loans.js, test/bigtest/interactors/users.js, test/bigtest/network/config.js, test/bigtest/network/factories/credential.js, test/bigtest/tests/user-edit-page-test.js, test/bigtest/tests/user-proxy-edit-test.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-1523
This PR also addresses unrelated tests failures across ui-users.
=> UIU-1523: Capitalize user status when displayed

CHANGELOG.md, src/views/LoanDetails/LoanDetails.js
https://issues.folio.org/browse/UIU-1662
=> UIU-1662: Bring back Declare lost button

src/views/AccountDetails/AccountDetails.js
Fix duplicate displaying of actions on account details page.
https://issues.folio.org/browse/UIU-1644
=> UIU-1644 - Fee/Fine Details is not refreshing, which may result in user entering duplicate actions

CHANGELOG.md, src/components/Accounts/Actions/Actions.js, test/bigtest/tests/user-transfer-test.js
* Update `createdAt` in pay/waive/transfer Actions
* Add `createdAt` in cancel Action
* Add `curServicePoint.id` to Transfer fines tests
* remove unused `owners` var in payment action
Refs UIU-1399
=> UIU-1399 Add createdAt to pay, waive, transfer and cancel actions

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/he.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/ja.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/ru.json, translations/ui-users/ur.json, translations/ui-users/zh_CN.json, translations/ui-users/zh_TW.json
=> Update translation strings as of 20200618T161121

CHANGELOG.md, src/views/UserEdit/UserEdit.js, test/bigtest/interactors/user-form-page.js, test/bigtest/interactors/user-view-page.js, test/bigtest/tests/user-edit-page-test.js
https://issues.folio.org/browse/UIU-1528
=> UIU-1528: Trim email address in user record to remove blanks

src/constants.js, src/settings/patronBlocks/Limits/LimitsForm.js, test/bigtest/tests/patron-blocks/settings-limits-form-test.js, translations/ui-users/en.json
According to the new requirments validation for `Settings --> Users --> Patron blocks --> Limits` was changed. 
https://issues.folio.org/browse/UIU-1675
=> UIU-1675: Change validation messages

src/components/PatronBlock/PatronBlockForm.js, translations/ui-users/en.json
Change `Request` to `Requests` on Manual Patron Block page
https://issues.folio.org/browse/UIU-1488
=> UIU-1488: Change label

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/he.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/ja.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/ru.json, translations/ui-users/ur.json, translations/ui-users/zh_CN.json, translations/ui-users/zh_TW.json
=> Update translation strings as of 20200623T182030

CHANGELOG.md, src/components/EditSections/EditUserInfo/EditUserInfo.js, src/components/UserDetailSections/UserInfo/UserInfo.js, src/views/UserEdit/UserEdit.js, src/views/UserEdit/UserForm.css, src/views/UserEdit/UserForm.js, test/bigtest/tests/user-edit-page-test.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-1649
The purpose of this PR is to implement the preferred name field on the user record.
Also, on the edit page, it was requested to apply the new default pane max width value and to change the pane title from the user's name to "Edit".
=> UIU-1649: Add preferred first name field on user record

src/constants.js, src/settings/patronBlocks/Limits/LimitsForm.js, test/bigtest/tests/patron-blocks/settings-limits-form-test.js, translations/ui-users/en.json
Change tha validation for `Recall overdue by maximum number of days` limit to "Must be blank or a number from 1 to 999999"
https://issues.folio.org/browse/UIU-1675
=> UIU-1675: Work with validation

CHANGELOG.md, src/index.js, src/views/UserDetail/UserDetail.js, src/views/UserEdit/UserForm.js, src/views/UserSearch/UserSearch.js
`<CommandList>` and `<HasCommand>`, due to a transitive dependency on
`mousetrap`, leaked memory which caused problems in CI when running unit
tests.
This branch restores those wrappers which were removed in #1139.
Refs [UIU-1457](https://issues.folio.org/browse/UIU-1457), [STCOM-636](https://issues.folio.org/browse/STCOM-636)
Replaces #1208, which replaced #1161. There's no material difference
among any of these three PRs, but `master` had drifted so much that it
was easier to start from scratch.
=> UIU-1457 restore CommandList, HasCommand

CHANGELOG.md, src/routes/LoanDetailContainer.js, src/views/LoanDetails/LoanDetails.js, test/bigtest/network/config.js, test/bigtest/tests/declare-lost-test.js
https://issues.folio.org/browse/UIU-1669
=> UIU-1669: Refresh Fine incurred field when item is declared lost

translations/ui-users/ru.json
=> Update translation strings as of 20200701T150841

src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/OpenLoans/helpers/getListDataFormatter.js
UIU 1639 Open and Closed loans lists : Ensures buttons have discernible text 
https://issues.folio.org/secure/RapidBoard.jspa?rapidView=79&projectKey=MODINVSTOR&view=detail&selectedIssue=UIU-1639
=> UIU 1639 Open and Closed loans lists : Ensures buttons have discernible text 

CHANGELOG.md, src/components/data/reports/OverdueLoanReport.js, src/routes/UserSearchContainer.js, src/views/UserSearch/UserSearch.js, translations/ui-users/en.json
We are using pagination to avoid some timeout issues reported under:
https://issues.folio.org/browse/UIU-1747
=> UIU-1747: Generate overdue loans report via pagination.

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/he.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/ja.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/ru.json, translations/ui-users/ur.json, translations/ui-users/zh_CN.json, translations/ui-users/zh_TW.json
=> Update translation strings as of 20200702T191903

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/he.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/ja.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/ru.json, translations/ui-users/ur.json, translations/ui-users/zh_CN.json, translations/ui-users/zh_TW.json
=> Update translation strings as of 20200709T123052

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/he.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/ja.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/ru.json, translations/ui-users/ur.json, translations/ui-users/zh_CN.json, translations/ui-users/zh_TW.json
=> Update translation strings as of 20200710T132222

CHANGELOG.md, package.json
maaaaaaaybe this resolves UIU-1759? I don't think it should, as the platform should _already_ be supplying all the deps that are changed here, but I can't reproduce UIU-1759 locally where I've had this change in place for a while.
=> Stripes 5 react router 5.2

CHANGELOG.md, src/routes/UserSearchContainer.js
- Support ability to search users by Preferred first name field
=> UIU-1767: Users App: Search preferred first name

src/components/Loans/OpenLoans/OpenLoansControl.js, src/routes/AccountDetailsContainer.js, src/settings/patronBlocks/Conditions/Conditions.js, src/views/AccountDetails/AccountDetails.js, src/views/LoanDetails/LoanDetails.js, src/views/LoanDetails/LoanProxyDetails.js
Removed some statements shutting off linter errors for specific pages
that I had placed earlier because previous fix was time-sensitive and
fixing the linter errors was causing other problems.  Those are resolved
here, so both linter and tests should be working.
=> Linter error resolution

src/components/data/reports/OverdueLoanReport.js, translations/ui-users/en.json
Add chronology and copyNumber fields to loans exports.
https://issues.folio.org/browse/UIU-1482
=> UIU-1482 - Add chronology, copy number to loans exports

src/routes/AccountDetailsContainer.js
Fetch contributors list from instance instead of loan.
https://issues.folio.org/browse/UIU-1786
=> UIU-1786 - Manual charge with item should not be associated with loan

CHANGELOG.md, src/components/EditSections/EditExtendedInfo/CreateResetPasswordControl/CreateResetPasswordControl.js, src/components/EditSections/EditExtendedInfo/DepartmentsNameEdit/DepartmentsNameEdit.css, src/components/EditSections/EditExtendedInfo/DepartmentsNameEdit/DepartmentsNameEdit.js, src/components/EditSections/EditExtendedInfo/DepartmentsNameEdit/index.js, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, src/components/EditSections/EditExtendedInfo/RequestPreferencesEdit/RequestPreferencesEdit.js, src/components/UserDetailSections/ExtendedInfo/ExtendedInfo.js, src/routes/UserRecordContainer.js, src/settings/DepartmentsSettings.js, src/shapes.js, src/views/UserDetail/UserDetail.js, src/views/UserEdit/UserEdit.js, src/views/UserEdit/UserForm.js, test/bigtest/interactors/user-form-page.js, test/bigtest/interactors/user-view-page.js, test/bigtest/network/factories/department.js, test/bigtest/network/factories/user.js, test/bigtest/network/models/department.js, test/bigtest/network/serializers/department.js, test/bigtest/tests/settings-departments-test.js, test/bigtest/tests/user-edit-page-test.js, test/bigtest/tests/user-view-page-test.js, translations/ui-users/en.json
- Add Departments name to User Create/Edit/View Pages
- Add validation to Settings > Departments for empty code value
[UIU-1224](https://issues.folio.org/browse/UIU-1224)
=> UIU-1224: Add departments to User record

src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/OpenLoans/components/OpenLoansSubHeader/OpenLoansSubHeader.js, translations/ui-users/en.json
Add `copy number` field to CSV report in loans context.
https://issues.folio.org/browse/UIU-1482
=> UIU-1482: Add copy number into CSV report

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/he.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/ja.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/ru.json, translations/ui-users/ur.json, translations/ui-users/zh_CN.json, translations/ui-users/zh_TW.json
=> Update translation strings as of 20200811T193833

CHANGELOG.md, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/Loans/OpenLoans/components/OpenLoansSubHeader/OpenLoansSubHeader.js, src/components/util/util.js, src/constants.js, src/views/LoanDetails/LoanDetails.js, test/bigtest/tests/aged-to-lost-test.js
https://issues.folio.org/browse/UIU-1495
This PR prevents due date changes for Aged to lost items (essentially the same thing  that was done earlier for Declared lost items).
=> UIU-1495: Handle Aged to lost items for bulk due date change

CHANGELOG.md, package.json, translations/ui-users/en.json
[[UIU-1778]](https://issues.folio.org/browse/UIU-1778) Departments: Create UI permissions for Settings>Users>Departments CRUD
**REQUIREMENT: Create the UI permissions:**
Settings (Users) : Create, edit, view, and delete departments
Settings (Users) : Create, edit, and view departments
Settings (Users) : View departments
=> UIU-1778 Departments: Create UI permissions for Settings>Users>Departments CRUD

CHANGELOG.md
https://issues.folio.org/browse/UIU-1812
=> UIU-1812: Add missing departments permission

CHANGELOG.md, src/views/LoanDetails/LoanDetails.js
https://issues.folio.org/browse/UIU-1819
=> UIU-1819: Prevent UI crashing when loading loan with deleted item

src/settings/DepartmentsSettings.js, src/settings/sections.js
[[UIU-1778]](https://issues.folio.org/browse/UIU-1778) Departments: Create UI permissions for Settings>Users>Departments CRUD
**REQUIREMENT: Create the UI permissions:**
Settings (Users) : Create, edit, view, and delete departments
Settings (Users) : Create, edit, and view departments
Settings (Users) : View departments
=> UIU-1778 integrated permissions

CHANGELOG.md, src/routes/LoanDetailContainer.js, test/bigtest/tests/loan-actions-history-test.js
Filter out blank actions on loan details UI.
https://issues.folio.org/browse/UIU-1820
=> UIU-1820: Filter out blank actions on loan details UI

src/components/Accounts/Actions/ActionModal.js, src/components/Accounts/Actions/FeeFineActions.js, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/Accounts/ChargeFeeFine/FeeFineInfo.js
In the process of refactoring fees/fines BE takes care of updating Account object and creating new FeeFineAction object.
In current PR were removed such requests since they are performed on server side
=> Remove some fee/fine requests

CHANGELOG.md, src/components/Accounts/Actions/ActionModal.js, src/components/Accounts/Actions/FeeFineActions.js, src/components/Accounts/Actions/WarningModal.js, src/components/Accounts/Menu.js, src/components/Accounts/ViewFeesFines/ViewFeesFines.js, src/components/Accounts/accountFunctions.js, src/constants.js, src/routes/AccountDetailsContainer.js, src/views/AccountDetails/AccountDetails.js, src/views/AccountsListing/AccountsListing.js, test/bigtest/interactors/fee-fine-details.js, test/bigtest/network/config.js, test/bigtest/network/scenarios/fee-fine-details.js, test/bigtest/tests/fee-fine-details-test.js, translations/ui-users/en.json
Add of refund fee/fine single action. Integrate following endpoints in order to get rid of calculation on FE:
- `/accounts/{accountId}/check-refund`
- `/accounts/{accountId}/refund`
https://issues.folio.org/browse/UIU-1850
=> UIU-1850 - Add refund action

src/components/Accounts/Actions/ActionModal.js, src/components/Accounts/Actions/FeeFineActions.js, src/routes/AccountsListingContainer.js, test/bigtest/interactors/user-pay.js, test/bigtest/network/config.js, test/bigtest/network/scenarios/pay.js, test/bigtest/tests/user-pay-test.js
Move calculations for multiple fee/fine actions to BE.
https://issues.folio.org/browse/UIU-1798
=> UIU-1798 - Refactor actions for multiple selected list items

CHANGELOG.md, src/routes/UserSearchContainer.js, src/routes/filterConfig.js, src/views/UserSearch/Filters.js, src/views/UserSearch/UserSearch.js, test/bigtest/interactors/users.js, test/bigtest/network/config.js, test/bigtest/tests/users-departments-filter-test.js, translations/ui-users/en.json
Add a Departments filter to filter users by their department
[UIU-1355](https://issues.folio.org/browse/UIU-1355)
=> UIU-1355: Users App | Add a Departments filter

src/components/Accounts/Actions/ActionModal.js, src/components/Accounts/Actions/FeeFineActions.js, src/components/Accounts/accountFunctions.js, src/constants.js, src/views/AccountDetails/AccountDetails.js
Current PR related to changes made in previous [PR#1510](https://github.com/folio-org/ui-users/pull/1510), which break some existing logic. Add changes to restore existing logic and correct state of refund fees/fines.
=> UIU-1850: Work with fee/fine refund action

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/he.json, translations/ui-users/hi_IN.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/ja.json, translations/ui-users/ko.json, translations/ui-users/pl.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/ru.json, translations/ui-users/ur.json, translations/ui-users/zh_CN.json, translations/ui-users/zh_TW.json
=> Update translation strings as of 20201013T203429

translations/ui-users/ar.json, translations/ui-users/fr_FR.json
=> Update translation strings as of 20201020T221939

src/components/PatronBlock/PatronBlockForm.js, src/components/PatronBlock/PatronBlockLayer.js, src/components/UserDetailSections/PatronBlock/PatronBlock.js, test/bigtest/tests/patron-blocks-test.js
After updating `Datepicker` component, `patronBlock` page is crashing after selecting of date at `Datepicker`.
In scope of current PR:
- change `dateFormat` from `YYYY/MM/DD` to `YYYY-MM-DD`
- migrate patronBlock form to `react-final-form`
- as this bug is a regression - rewrite test where `Expiration date` now is setting with click on `Datepicker` component instead of
just filling the `Expiration date` to `input` field
https://issues.folio.org/browse/UIU-1896
**When click on the date in Datepicker page is crushing**
=> UIU-1896: Fix of Datepicker error at PatronBlock form

package.json
Since was made breaking changes in `Modfeesfines` in [PR](https://github.com/folio-org/mod-feesfines/pull/139), we should update version of `feesfines` okapi interface for consistent changes
=> Update version of feesfines okapi interface

src/components/Accounts/accountFunctions.js, src/constants.js
Make sure Refund process will not refund the same fee/fine more than once.
https://issues.folio.org/browse/UIU-1885
=> UIU-1855 - Patrons should not be refunded a fee/fine more than once

translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/he.json, translations/ui-users/hi_IN.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/ja.json, translations/ui-users/ko.json, translations/ui-users/pl.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/ru.json, translations/ui-users/ur.json, translations/ui-users/zh_CN.json, translations/ui-users/zh_TW.json
=> Update translation strings as of 20201102T140138

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, test/bigtest/tests/charge-fee-fine-test.js
Not asked to confirm leaving New Fee/Fine page anymore
https://issues.folio.org/browse/UIU-1933
=> UIU-1933: Add back confirmation modal

src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/Accounts/ChargeFeeFine/ChargeForm.js
Fix ownerId reset on re-fetch
https://issues.folio.org/browse/UIU-1898
=> UIU-1898 - Selection of fee/fine owner on new fee/fine charge is not remaining selected

src/components/Accounts/accountFunctions.js, src/constants.js
Deny to refund only fully refunded accounts
https://issues.folio.org/browse/UIU-1885
=> UIU-1885 - Patrons should not be refunded a fee/fine more than once

CHANGELOG.md, src/routes/UserRecordContainer.js, src/views/UserDetail/UserDetail.js, src/views/UserDetail/components/ExportFeesFinesReportButton/ExportFeesFinesReportButton.js, src/views/UserDetail/components/ExportFeesFinesReportButton/index.js, src/views/UserDetail/components/index.js, test/bigtest/interactors/user-view-page.js, test/bigtest/network/scenarios/fee-fine-actions.js, test/bigtest/tests/user-view-page-test.js, translations/ui-users/en.json
- change target to master after merge UIU-1955
- add EXPORT option to User Information
https://issues.folio.org/browse/UIU-1957
=> UIU-1957: Add EXPORT option to User Information

CHANGELOG.md, src/routes/AccountDetailsContainer.js, src/views/AccountDetails/AccountDetails.js, test/bigtest/interactors/fee-fine-details.js, test/bigtest/tests/fee-fine-export-test.js
- Add EXPORT option to fees/fines Details
https://issues.folio.org/browse/UIU-1956
=> UIU-1956: Add EXPORT option to fees/fines Details

CHANGELOG.md, package.json
Increment `@folio/stripes-cli` to `v2`.
Refs [UIU-2047](https://issues.folio.org/browse/UIU-2047)
=> UIU-2047 increment @folio/stripes-cli to v2

CHANGELOG.md, src/components/RefundsReportModal/RefundsReportModal.js, src/views/UserSearch/UserSearch.js
- Fix wrong value on reset data for Refunds to process manually report (CSV)
https://issues.folio.org/browse/UIU-2050
=> UIU-2050: Fix wrong value on reset data for Refunds to process manually report (CSV)

CHANGELOG.md, src/views/UserSearch/UserSearch.js, test/bigtest/interactors/users.js, test/bigtest/network/config.js, test/bigtest/network/scenarios/feefine-refund-error.js, test/bigtest/network/scenarios/feefine-refund-not-found.js, test/bigtest/network/scenarios/feefine-refund.js, test/bigtest/tests/refunds-report-test.js, translations/ui-users/en.json
- Add Callout for Refund report
https://issues.folio.org/browse/UIU-2035
=> UIU-2035: Add Callout for Refund report

CHANGELOG.md, src/settings/patronBlocks/Limits/Limits.js, src/settings/patronBlocks/Limits/LimitsForm.js, test/bigtest/tests/patron-blocks/settings-limits-form-test.js, translations/ui-users/en.json
- Allow 0 as valid entry for Patron Block Limits
https://issues.folio.org/browse/UIU-1998
=> UIU-1998: Allow 0 as valid entry for Patron Block Limits

CHANGELOG.md, src/components/RefundsReportModal/RefundsReportModal.js, test/bigtest/tests/refunds-report-test.js
https://issues.folio.org/browse/MODFEE-173
- Change logic for Save and close disable state
https://issues.folio.org/browse/UIU-2034
=> UIU-2034: Change logic for Save and close disable state

CHANGELOG.md, src/views/LoanDetails/LoanDetails.js
- Fix eslint error in LoanDetails.js
https://issues.folio.org/browse/UIU-2068
=> UIU-2068: fix eslint error in LoanDetails.js

CHANGELOG.md, karma.conf.js, src/components/ErrorPane/ErrorPane.js, src/components/ErrorPane/index.js, src/routes/UserRecordContainer.js, src/views/UserDetail/UserDetail.js, test/bigtest/interactors/user-not-found-page.js, test/bigtest/interactors/user-view-page.js, test/bigtest/tests/user-not-found-test.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-2081
=> UIU-2081: Show user-readable message when user is not found

CHANGELOG.md, package.json, translations/ui-users/en.json
We should  add Cash drawer Reconciliaton report and Financial transactions detail report permissions for reports
https://issues.folio.org/browse/UIU-2088
=> UIU-2088: Add Cash drawer Reconciliaton report and Financial transactions detail report permissions for reports

CHANGELOG.md, src/views/UserSearch/UserSearch.js, test/bigtest/interactors/users.js, test/bigtest/tests/cash-drawer-report-test.js, test/bigtest/tests/financial-transaction-report-test.js, translations/ui-users/en.json
We should  add new fee/fine reports as options to User Actions drop-down.
https://issues.folio.org/browse/UIU-2083
After merge UIU-2088 target branch should be changed to master
=> UIU-2083: Add new fee/fine reports as options to User Actions drop-down

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js
User should go back after creating new "fee/fine" page.
https://issues.folio.org/browse/UIU-2117
=> UIU-2117: Go back after fee/fine created

CHANGELOG.md, src/routes/LoanDetailContainer.js, src/views/LoanDetails/LoanDetails.js
Show loading indicator on the loans details screen
https://issues.folio.org/browse/UIU-2120
=> UIU-2120: Show loading indicator on Loans details screen

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/FeeFineInfo.js
Add possible for enter correct values for Fee/Fine amount
https://issues.folio.org/browse/UIU-2156
=> UIU-2156: Add possible for enter correct values for Fee/Fine amount

CHANGELOG.md, src/components/Accounts/Actions/FeeFineActions.js
Fix selecting current fee fine type
https://issues.folio.org/browse/UIU-2157
=> UIU-2157: Fix selecting current fee fine type

CHANGELOG.md, src/components/EditSections/EditUserInfo/EditUserInfo.js
Save the patron expiration with the time set to the end of the day(23:59:59) tenant's time zone.
https://issues.folio.org/browse/UIU-2182
=> UIU-2182: Save the patron expiration with the time set to the end of the day(23:59:59) tenant's time zone.

src/views/UserSearch/UserSearch.js
Add missing claimed-returned button
=> Add missing claimed-returned button

CHANGELOG.md, src/views/UserDetail/UserDetail.js
Check Notes interface and permission before showing `<NotePopupModal>`
[UIU-2212](https://issues.folio.org/browse/UIU-2212)
=> UIU-2212: Error window when opening or saving user data

CHANGELOG.md, src/components/Wrappers/withServicePoints.js
https://issues.folio.org/browse/UIU-2245
=> UIU-2245:  Filter out non existing service points

CHANGELOG.md, src/components/data/static/contactTypes.test.js
Create Jest/RTL test for contactTypes
https://issues.folio.org/browse/UIU-2368
=> UIU-2368: Create Jest/RTL test for contactTypes

CHANGELOG.md, src/components/Loans/OpenLoans/OpenLoans.test.js
https://issues.folio.org/browse/UIU-2314
=> UIU-2314: Create Jest/RTL test for OpenLoans

CHANGELOG.md, src/components/RequestFeeFineBlockButtons/RequestFeeFineBlockButtons.test.js
https://issues.folio.org/browse/UIU-2287
=> UIU-2287: Create Jest/RTL test for RequestFeeFineBlockButtons

src/settings/AddressTypesSettings.test.js, src/settings/DepartmentsSettings.js, src/settings/DepartmentsSettings.test.js, src/settings/FeeFineSettings.test.js, src/settings/OwnerSettings.test.js, src/settings/PatronGroupsSettings.test.js, src/settings/PaymentSettings.test.js, src/settings/RefundReasonsSettings.test.js, src/settings/TransferAccountsSettings.test.js, src/settings/WaiveSettings.test.js, test/jest/__mock__/stripesCore.mock.js, test/jest/__mock__/stripesSmartComponent.mock.js
Refs [UIU-2393](https://issues.folio.org/browse/UIU-2393), [UIU-2380](https://issues.folio.org/browse/UIU-2380), [UIU-2396](https://issues.folio.org/browse/UIU-2396), [UIU-2384](https://issues.folio.org/browse/UIU-2384)
=> controlled vocab tests

CHANGELOG.md, src/components/PermissionLabel/PermissionLabel.test.js
Code coverage and unit test cases for permission label
=> UIU-2330 create Jest/RTL test for PermissionLabel.js

CHANGELOG.md, src/settings/permissions/PermissionSets.test.js, test/jest/__mock__/stripesSmartComponent.mock.js
Code coverage and Unit testing for permssionSets settings component.
=> UIU-2383 create Jest/RTL test for PermissionSets.js

package.json, src/index.js, src/views/AccountDetails/AccountDetails.js, src/views/UserDetail/UserDetail.js
Fees/fines and loans should be readable, but not changeable, for users
with "Users: Can view fees/fines".
Refs [UIU-2472](https://issues.folio.org/browse/UIU-2472)
=> UIU-2472 include read-only permission for fees/fines

CHANGELOG.md, src/components/PermissionsAccordion/components/PermissionsList/PermissionsList.test.js
Code coverage and unit test case for PermissionsList component
=> UIU-2374 create Jest/RTL test for PermissionsList.js

CHANGELOG.md, src/settings/permissions/PermissionSetDetails.test.js
Code coverage and unit testing for permissionSetDetails  Component
=> UIU-2394 create Jest/RTL test for PermissionSetDetails.js

CHANGELOG.md, src/components/RenderPermissions/RenderPermissions.test.js
Code coverage and test cases for renderPermissions screen.
=> UIU-2267 create Jest/RTL test for RenderPermissions.js

CHANGELOG.md, src/components/UserDetailSections/UserPermissions/UserPermissions.test.js
Code coverage and unit testing for user permissions.
=> UIU-2303 create Jest/RTL test for UserPermissions.js

CHANGELOG.md, src/components/UserDetailSections/ProxyPermissions/ProxyPermissions.test.js
Code coverage and unit testing for proxy permissions.
=> UIU-2275 create Jest/RTL test for ProxyPermissions.js

CHANGELOG.md, src/settings/FeeFinesTable/Owners.test.js
Code coverage and unit testing for Owners.js
=> UIU-2408 create Jest/RTL test for Owners.js

CHANGELOG.md, package.json
Support okapi interfaces `circulation` `12.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* The implementation of title level requests requires data migration to allow for a single queue of requests, whether item or title level (https://issues.folio.org/browse/UXPROD-3330).
https://issues.folio.org/browse/UIU-2480
=> UIU-2480: also support `circulation` `12.0`

CHANGELOG.md, package.json, src/views/UserDetail/UserDetail.js
This should have been part of #1966 but it was missed.
Refs [UIU-2495](https://issues.folio.org/browse/UIU-2495), [UIU-2480](https://issues.folio.org/browse/UIU-2480), [FOLIO-3376](https://issues.folio.org/browse/FOLIO-3376)
=> UIU-2495 support request-storage 4.0

CHANGELOG.md, src/components/PatronBlock/PatronBlockModal.test.js
Code coverage and unit testing for patronblock modal.
=> UIU-2278 create Jest/RTL test for PatronBlockModal.js

CHANGELOG.md, src/settings/PaymentSettings.test.js, test/jest/helpers/buildResources.js
Code coverage and unit testing for payment settings component.
=> UIU-2389 create Jest/RTL test for PaymentSettings.js

CHANGELOG.md, src/settings/components/SettingsPage.js
Move focus to the Users pane header when selecting Users under the list of Settings
https://issues.folio.org/browse/UIU-2036
=> UIU-2036: Settings > Users > change focus

CHANGELOG.md, src/settings/FeeFineSettings.test.js
Unit Testing and code coverage for Fee fine settings component.
=> UIU-2378 create Jest/RTL test for FeeFineSettings.js

CHANGELOG.md, src/components/EditSections/EditExtendedInfo/CreateResetPasswordControl/Modals/WithCopyModal/WithCopyModal.test.js
Code coverage and unit testing for with copy Modal.
=> UIU-2268 create Jest/RTL test for WithCopyModal.js

CHANGELOG.md, src/components/ErrorModal/ErrorModal.test.js
Code coverage and unit testing for Error Modal.
=> UIU-2318 create Jest/RTL test for ErrorModal.js

CHANGELOG.md, package.json
Support okapi interfaces `circulation` `13.0`
* Title level requests changes affect ui-requests (UIREQ) without breaking change for this module.
* Was changed API associated with request queue.
https://issues.folio.org/browse/UIU-2483
=> UIU-2483: Also support circulation 13.0

CHANGELOG.md, src/components/Accounts/Actions/CancellationModal.test.js
Code coverage and unit test cases for cancellation modal component.
=> UIU-2342 create Jest/RTL test for CancellationModal.js

CHANGELOG.md, src/components/Accounts/ViewFeesFines/ViewFeesFines.js, translations/ui-users/en.json
Column selector dropdown does not match column headings
https://issues.folio.org/browse/UIU-2504
=> UIU-2504: Column selector dropdown does not match column headings

translations/ui-users/en.json
Refs. [UIU-637](https://issues.folio.org/browse/UIU-637)
Replaces #2012
=> UIU-637 Change error message for existing fee/fine type

CHANGELOG.md, src/components/EditSections/EditExtendedInfo/CreateResetPasswordControl/Modals/CreatePasswordModal.js, src/components/EditSections/EditExtendedInfo/CreateResetPasswordControl/Modals/CreatePasswordModal.test.js
Code coverage and unit test cased for create password modal.
=> UIU-2355 create Jest/RTL test for CreatePasswordModal.js

CHANGELOG.md, src/components/EditSections/EditExtendedInfo/CreateResetPasswordControl/Modals/ResetPasswordModal.test.js
Code  coverage and unit test cases for reset password modal.
=> UIU-2359 create Jest/RTL test for ResetPasswordModal.js

CHANGELOG.md, src/components/Loans/OpenLoans/components/BulkClaimReturnedModal/BulkClaimReturnedModal.js
Purpose: https://issues.folio.org/browse/UIU-1688
Approach: update column names to be unique
=> UIU-1688 Accessibility: Document has multiple static elements with the same ID attribute

package.json
h/t @funkymalc for noticing that we failed to bump the minor version on
our #master branch to keep it ahead of the published versions.
=> bump minor to 7.1

CHANGELOG.md, src/components/util/patronBlocks.test.js
Code coverage and Unit testing for patronBlocks component.
=> UIU-2290 create Jest/RTL test for patronBlocks.js

CHANGELOG.md
https://issues.folio.org/browse/UIU-2532
=> Release v7.1.0

CHANGELOG.md, src/components/EditSections/EditProxy/EditProxy.test.js
Code coverage and unit testing for editproxy component.
=> UIU-2285 create Jest/RTL test for EditProxy.js

CHANGELOG.md, src/components/validators/asyncValidateField.test.js
Code coverage and unit testing for asyncvalidatefield function.
=> UIU-2271 create Jest/RTL test for asyncValidateField.js

CHANGELOG.md, src/components/CustomFieldsFilters/CustomFieldsFilter.js, src/components/Loans/OpenLoans/components/BulkClaimReturnedModal/BulkClaimReturnedModal.js, src/settings/patronBlocks/BlockTemplates/BlockTemplateDetails.js
Import from `@folio/stripes/...` rather than directly from its
constituent repositories.
Refs [UIU-2173](https://issues.folio.org/browse/UIU-2173)
=> UIU-2173 import from @folio/stripes

CHANGELOG.md, src/components/ProxyGroup/ProxyItem/ProxyItem.test.js
Code coverage and unit testing for ProxyItem component.
=> UIU-2274 create Jest/RTL test for ProxyItem.js

CHANGELOG.md, src/components/BulkOverrideDialog/BulkOverrideDialog.test.js, test/jest/__mock__/stripesSmartComponent.mock.js
Code coverage and unit testing for BulkOverrideDialog component
=> UIU-2295 create Jest/RTL test for BulkOverrideDialog.js

CHANGELOG.md, src/components/BulkOverrideDialog/BulkOverrideLoansList.test.js
Code coverage and unit testing for BulkOverrideLoansList component
=> UIU-2328 create Jest/RTL test for BulkOverrideLoansList.js

CHANGELOG.md, src/components/BulkRenewalDialog/BulkRenewalDialog.test.js
Code coverage and unit testing for BulkRenewalDialog component.
=> UIU-2309 create Jest/RTL test for BulkRenewalDialog.js

CHANGELOG.md, src/components/BulkRenewalDialog/BulkRenewInfo.test.js
Code coverage and unit testing for BulkRenewInfo component.
=> UIU-2362 create Jest/RTL test for BulkRenewInfo.js

CHANGELOG.md, package.json, src/index.js
Remove react-hot-loader
https://issues.folio.org/browse/UIU-2567
=> UIU-2567: Remove react-hot-loader

CHANGELOG.md, src/components/Loans/ClosedLoans/ClosedLoans.js
Add loans anonymized message with count of loans not anonymized
[UIU-2246](https://issues.folio.org/browse/UIU-2246)
=> UIU-2246 Add loans anonymized message with count of loans not anonymized

CHANGELOG.md, src/settings/patronBlocks/Conditions/Conditions.test.js
Code coverage and unit testing for conditions component
=> UIU-2405 create Jest/RTL test for Conditions.js

CHANGELOG.md, src/settings/patronBlocks/Conditions/ConditionsForm.test.js
Code coverage and unit testing for conditionsForm.
=> UIU-2382 create Jest/RTL test for ConditionsForm.js

CHANGELOG.md, src/settings/PatronGroupsSettings.js
https://issues.folio.org/browse/UIU-2602
=> UIU-2602: Remove unused usersPerGroup manifest from PatronGroupsSettings

CHANGELOG.md, src/components/HelperApp/HelperApp.test.js, test/jest/__mock__/stripesCore.mock.js
Code coverage and unit testing for helperapp component.
=> UIU-2310 create Jest/RTL test for HelperApp.js

CHANGELOG.md, src/settings/sections.js
Fix Patron blocks settings order
https://issues.folio.org/browse/UIU-2448
=> UIU-2448: Fix Patron blocks settings order

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, package.json, src/components/Accounts/Actions/WarningModal.test.js, src/components/ModalContent/ModalContent.js, src/components/ModalContent/ModalContent.test.js, src/components/PatronBlock/OverrideModal.test.js, src/components/Wrappers/withServicePoints.js, src/components/data/reports/FeeFineReport.test.js, src/components/util/refundTransferClaimReturned.test.js, src/settings/FeeFineSettings.test.js, src/settings/FeeFinesTable/CopyModal.test.js, src/settings/OwnerSettings.js, src/settings/OwnerSettings.test.js, src/settings/PaymentSettings.js, src/settings/PaymentSettings.test.js, test/jest/helpers/renderWithRouter.js
Refs [UIU-2607](https://issues.folio.org/browse/UIU-2607)
=> UIU-2607 update NodeJS to active LTS, v16

CHANGELOG.md, src/components/PatronBlock/PatronBlockLayer.js, src/components/RequestFeeFineBlockButtons/RequestFeeFineBlockButtons.js, src/components/RequestFeeFineBlockButtons/RequestFeeFineBlockButtons.test.js, src/components/UserDetailSections/PatronBlock/PatronBlock.js, src/components/UserDetailSections/PatronBlock/PatronBlock.test.js, src/views/UserDetail/UserDetail.test.js
User should be directed to the last open page when working in more than one browser
https://issues.folio.org/browse/UIU-2605
=> UIU-2605: User should be directed to the last open page when working in more than one browser

CHANGELOG.md, src/components/Accounts/accountFunctions.test.js, test/jest/fixtures/account.json
Code coverage and unit testing for account functions component.
=> UIU-2334 create Jest/RTL test for accountFunctions.js

CHANGELOG.md, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.test.js
Code coverage and unit testing for edit extended information component.
=> UIU-2299 create Jest/RTL test for EditExtendedInfo.js

CHANGELOG.md, src/components/EditSections/EditContactInfo/EditContactInfo.test.js, test/jest/__mock__/stripesComponents.mock.js
Code coverage and unit testing for edit contact information component.
=> UIU-2343 create Jest/RTL test for EditContactInfo.js

CHANGELOG.md, src/components/Wrappers/withFormValues.test.js
Code coverage and unit testing for with form values wrapper.
=> UIU-2349 create Jest/RTL test for withFormValues.js

CHANGELOG.md, src/components/LoanActionDialog/LoanActionDialog.test.js
Code coverage and unit testing for Loan action dialog component.
=> UIU-2302 create Jest/RTL test for LoanActionDialog.js

CHANGELOG.md, src/components/UserDetailSections/UserServicePoints/UserServicePoints.test.js, test/jest/__mock__/stripesComponents.mock.js
Code coverage and unit testing for User service points components.
=> UIU-2335 create Jest/RTL test for UserServicePoints.js

.eslintrc, src/views/Notes/NoteViewPage.test.js
Lint: NONE SHALL PASS!
Code: My tests have no quarrel with you.
Lint: NONE SHALL PASS!
Code: But I must commit clean PRs!
Lint: Then you shall die.
Code: I command you to stand aside. Tests don't need proptype validation!
Lint: I move for no one.
Code: So be it.
[Dramatic music]
[More dramatic music]
[Even more dramatic music]
[Still more music. Srsly this joke is kind of old now]
Code: [disables proptype validation for tests] Now stand aside!
Lint: 'Tis but a scratch!
Code: Scratch? Your rule's off!
Lint: No it isn't!
Code: [Rolls eyes, stabs lint again for good measure]
=> loosen lint rules for tests

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ItemInfo.test.js
Code coverage and unit testing for item info component.
=> create Jest/RTL test for ItemInfo.js

CHANGELOG.md, src/components/util/navigationHandlers.test.js
Code coverage and unit testing for navigation handlers.
=> UIU-2369 create Jest/RTL test for navigationHandlers.js

src/components/ShowLongContentInPopover/ShowLongContentInPopover.js, src/components/ShowLongContentInPopover/ShowLongContentInPopover.test.js, src/components/ShowLongContentInPopover/index.js, test/jest/__mock__/stripesComponents.mock.js
Implement 3 dot component for actual cost list
This component created for actual cost list. Behavior of current component was shown to PO and will be tested in scope of actual cost feature.
https://issues.folio.org/browse/UIU-2667
How i understand we don't need update change log now. Could you please correct me if i am wrong?
=> UIU-2667:Implement 3 dot component for actual cost list

CHANGELOG.md, src/views/Notes/NoteEditPage.test.js
create Jest/RTL test for NoteEditPage.js
[UIU-2424](https://issues.folio.org/browse/UIU-2424)
=> UIU-2424 - create Jest/RTL test for NoteEditPage.js

src/components/Accounts/ChargeFeeFine/ItemLookup.test.js
Unit test for ItemLookup. 
Refs UIU-2376(https://issues.folio.org/browse/UIU-2376)
=> UIU-2376 include unit test for ItemLookup.js

src/components/LoanActionDialog/LoanActionDialog.js, src/routes/LoanDetailContainer.js
Lint noise on a PR's as noisy can be
Lint lintity lint lintity lint lint lintoo
Moved 'round a question, and see what's it do.
Mixed up the order
And that's linty too.
=> lint lintity lint lintity lint lint linty

src/components/UserDetailSections/UserLoans/UserLoans.test.js
Unit test for src/components/UserDetailSections/UserLoans/UserLoans.js,
Refs [UIU-2375](https://issues.folio.org/browse/UIU-2375)
=> UIU-2375 include unit test for UserLoans.js

CHANGELOG.md, package.json
Add permissions for lost items page
https://issues.folio.org/browse/UIU-2690
=> UIU-2690: Add permissions for lost items page

CHANGELOG.md
https://issues.folio.org/browse/UIU-2704
=> Release v8.2.0

CHANGELOG.md, src/views/UserDetail/UserDetail.test.js, test/jest/__mock__/stripesComponents.mock.js, yarn.lock
Increase the code coverage by writing more tests
Issue: https://issues.folio.org/browse/UIU-2421
The unit tests already existed for src/views/UserDetail.js
I have improved the coverage to as much as possible by adding few tests.
=> UIU-2421 - Increase code coverage

CHANGELOG.md, src/views/LoanDetails/LoanDetails.js
Adjust permissions in order to see the link to open the request queue.
https://issues.folio.org/browse/UIU-2661
=> UIU-2661: Adjust permissions in order to see the link to open request queue

CHANGELOG.md, src/components/LoanActionDialog/LoanActionDialog.js, src/components/ModalContent/ModalContent.js, src/components/Wrappers/withClaimReturned.js
Disable 'Claimed return' button after click to prevent multiple submissions.
https://issues.folio.org/browse/UIU-2732
=> UIU-2732: Disable 'Claimed return' button after click to prevent multiple submissions

src/settings/OwnerSettings.js
"When there's a quote around, I want to be in charge of it." --Lint Eastwood
=> Lint. That is all.

CHANGELOG.md, package.json
Update request-storage interface version due to braking changes in mod-circulation-storage
[UIU-2749](https://issues.folio.org/browse/UIU-2749)
=> UIU-2749: Update versions of interfaces request-storage

package.json
Add necessary permissions for "billing actual cost" functionality.
Improvement of [PR #2299](https://github.com/folio-org/ui-users/pull/2299)
[UIU-1863](https://issues.folio.org/browse/UIU-1863)
[Related PR](https://github.com/folio-org/ui-users/pull/2299)
=> Add necessary permission for "billing actual cost" functionality

CHANGELOG.md, src/views/UserDetail/UserDetailFullscreen.test.js, test/jest/__mock__/stripesComponents.mock.js, yarn.lock
Create Jest/RTL test for UserDetailFullscreen.js
Issue: https://issues.folio.org/browse/UIU-2429
=> UIU-2429 - Create Jest/RTL test for UserDetailFullscreen.js

CHANGELOG.md, package.json, src/components/Accounts/Actions/CancellationModal.test.js, src/components/Accounts/Actions/CommentModal.test.js, src/components/PatronBlock/PatronBlockForm.js, src/components/PatronBlock/PatronBlockModalWithOverrideModal.test.js, src/settings/FeeFinesTable/CopyModal.test.js
* Copy stable tests from PR #2320
* Use stripes-cli ~2.6.3 for stripes v7 compatibility since ^2.7.0 expect stripes v8
=> Use stable tests

CHANGELOG.md
https://issues.folio.org/browse/UIU-2787
=> Release v9.0

CHANGELOG.md, src/views/UserDetail/UserDetail.test.js, src/views/UserDetail/components/DeleteUserModal/DeleteUserModal.test.js, src/views/UserDetail/components/OpenTransactionModal/OpenTransactionModal.test.js, yarn.lock
https://issues.folio.org/browse/STCOR-711
Fix paths to `StripesContext`. This should be merged after: https://github.com/folio-org/stripes-core/pull/1294
=> UIU-2834: Fix paths to StripesContext

.github/workflows/publish-jest-results.yml
=> Update publish jest workflow

yarn.lock
Resolve the following:
* https://github.com/folio-org/ui-users/security/dependabot/51
* https://github.com/folio-org/ui-users/security/dependabot/54
=> placate dependabot security alert #51

yarn.lock
Resolve https://github.com/folio-org/ui-users/security/dependabot/28
=> placate dependabot security update #28

CHANGELOG.md, package.json, src/components/UserDetailSections/UserRequests/UserRequests.test.js
Also support circulation 14.0
Field fulfilmentPreference was renamed to fulfillmentPreference. This changes do not affect current module.
https://issues.folio.org/browse/UIU-2858
=> UIU-2858: Also support circulation 14.0

src/components/PatronBlock/PatronBlockLayer.test.js, test/jest/helpers/renderWithRouter.js
* omit `screen.debug`
* omit private paths to translations in test harnesses
=> test clean-up

src/components/UserDetailSections/UserPermissions/UserPermissions.test.js, src/views/LostItems/LostItemsListContainer/components/LostItemsList/components/ActualCostDetailsModal/ActualCostDetailsModal.js, test/jest/helpers/renderWithRouter.js
Lint it up, lint it in, let me begin
I came to win, semicolons: no sin!
I won't ever tab up, punk ya betta back up
Better hit the space and yo, the whole block'll wrap up 
Braces, brackets, c'mon don't blow your stack it's 
Time ya got the feelin', stack frames to the ceilin'
Lint around, lint around
Lint around, lint around
Lint around, lint around
Lint up, lint up, and lint down
=> Lint in the house, yo!

CHANGELOG.md, package.json, src/components/ModalContent/ModalContent.js, src/components/Wrappers/withAddInfo.js, src/components/data/static/loanActionMap.js, src/views/LoanDetails/LoanDetails.js
Fixes UIU-2893.
No user-visible changes, just the use of a newer WSAPI.
=> UIU-2893 Use new WSAPI for adding patron/staff notes to loans

src/components/ErrorModal/ErrorModal.js, src/components/PermissionsAccordion/PermissionsAccordionList.js, src/settings/CommentRequiredForm.js, src/settings/CommentRequiredForm.test.js, src/settings/patronBlocks/BlockTemplates/BlockTemplateForm.js, src/settings/patronBlocks/BlockTemplates/BlockTemplateForm.test.js, src/settings/patronBlocks/Limits/Limits.js, src/views/UserDetail/UserDetail.js, src/views/UserDetail/components/ExportFeesFinesReportButton/ExportFeesFinesReportButton.js, src/views/UserEdit/UserEdit.js
Prop-types clean up during some React v18 testing. Could. Not. Resist.
=> prop-types cleanup

CHANGELOG.md, src/components/Accounts/Actions/ActionModal.js
Leverage cookie-based authentication in all API requests
https://issues.folio.org/browse/UIU-2746
=> UIU-2746 - Leverage cookie-based authentication in all API requests

src/components/AssignedUsers/AssignUsers.test.js, src/components/AssignedUsers/AssignedUsersContainer.js, src/components/AssignedUsers/AssignedUsersContainer.test.js, src/components/AssignedUsers/AssignedUsersList.js, src/components/AssignedUsers/AssignedUsersList.test.js, src/components/AssignedUsers/constants.js, src/components/AssignedUsers/hooks/useAssignedUsers/useAssignedUsers.js, src/components/AssignedUsers/hooks/useAssignedUsers/useAssignedUsers.test.js, src/components/AssignedUsers/hooks/useAssignedUsersMutation/useAssignedUsersMutation.test.js, src/components/AssignedUsers/hooks/utils.js, src/components/AssignedUsers/hooks/utils.test.js, src/components/AssignedUsers/utils.test.js
- Add `MAX_RECORDS` to component level `constants.js` in order to reuse this component in `ui-consortium-settings`
- Fix code styling issue such as trailing comma and spaces
- Add `grantedToIds` to query key in order to improve query caching mechanizm
=> UIU-2873: cache and code styling issues

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, PULL_REQUEST_TEMPLATE.md, package.json
[UIU-2927](https://issues.folio.org/browse/UIU-2927) - Update Node.js to v18 in GitHub Actions
[UIU-2918](https://issues.folio.org/browse/UIU-2918) - Add PULL_REQUEST_TEMPLATE.md file to the repository.
=> UIU-2927, UIU-2918 - Update Node.js to v18 in GitHub Actions, Add PULL_REQUEST_TEMPLATE.md file to the repository.

CHANGELOG.md, translations/ui-users/en.json, translations/ui-users/en_US.json
https://issues.folio.org/browse/UIU-2922
Adjust loans.staffInfoDialogBody translation
=> UIU-2922: Adjust loans.staffInfoDialogBody translation

CHANGELOG.md, src/components/Accounts/Actions/ActionModal.js
[UIU-2930](https://issues.folio.org/browse/UIU-2930) - User can't pay the fee/fine
Propagate request headers properly. …
=> UIU-2930 - propagate request headers properly

CHANGELOG.md, src/components/RequestFeeFineBlockButtons/RequestFeeFineBlockButtons.js, src/components/RequestFeeFineBlockButtons/RequestFeeFineBlockButtons.test.js, src/views/UserDetail/UserDetail.js
[UIU-2951](https://issues.folio.org/browse/UIU-2951) - **Scenario 3**: disabled action buttons for shadow users.
https://github.com/folio-org/ui-users/assets/116072773/2c217552-cd27-43f6-ba03-470e99485648 …
=> UIU-2951: disabled action buttons for shadow users

CHANGELOG.md, package.json, src/settings/AddressTypesSettings.js, yarn.lock
This PR is intended for Poppy release of this module.
Update change log for older releases as well, as it was not handled for orchid bug fix versions.
Fix linting config and lint issues.
=> Release v10.0.0

CHANGELOG.md
Version `10.0.1` has been released, so to keep the changelog consistent, add a release note. …
=> Update the changelog to reflect the `v10.0.1` release

CHANGELOG.md, package.json, src/views/UserEdit/UserEdit.js
This PR intends to release Poppy bugfix v10.0.2
While it's helpful for reviewers to help …
=> Release v10.0.2

CHANGELOG.md
Update changelog after release 10.0.3 …
=> UIU-2978 - Update changelog after release 10.0.3

CHANGELOG.md, package.json, src/components/PermissionsAccordion/components/PermissionsModal/PermissionsModal.js, src/routes/LoansListingContainer.js, src/routes/UserSearchContainer.js, src/views/UserEdit/UserForm.js
=> Release v10.0.4

CHANGELOG.md, src/components/EditSections/EditUserInfo/EditUserInfo.js, src/views/UserEdit/UserEdit.js, src/views/UserEdit/UserForm.js, src/views/UserEdit/UserForm.test.js
https://issues.folio.org/browse/UIU-3000
fix validation for shadow users to not check disabled fields …
=> UIU-3000 Can not edit shadow user account

CHANGELOG.md, src/views/LoanDetails/LoanDetails.js, src/views/LoanDetails/LoanDetails.test.js
Link to PR for master branch - https://github.com/folio-org/ui-users/pull/2588
While it's …
=> UIU-2964 - [DCB] Loan details: Disable loan actions (Lending library)

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIU-3003
Full changelog: https://github.com/folio-org/ui-users/compare/v10.0.4...release-v10.0.5
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> Release v10.0.5

CHANGELOG.md, src/components/ReportModals/CashDrawerReportModal.js, src/components/ReportModals/CashDrawerReportModal.test.js, src/components/ReportModals/FinancialTransactionsReportModal.js, src/components/ReportModals/FinancialTransactionsReportModal.test.js, src/components/ReportModals/RefundsReportModal.js, src/components/ReportModals/RefundsReportModal.test.js
Fix problem with Date field in User app reports does not populate when a first entry was cleared
https://issues.folio.org/browse/UIU-2991
=> UIU-2991: Fix problem with Date field in User app reports does not populate when a first entry was cleared

CHANGELOG.md, src/components/UserDetailSections/PatronBlock/PatronBlock.js, src/components/UserDetailSections/PatronBlock/PatronBlock.test.js, src/components/UserDetailSections/UserAccounts/UserAccounts.js, src/components/UserDetailSections/UserAccounts/UserAccounts.test.js, src/components/UserDetailSections/UserRequests/UserRequests.js, src/components/UserDetailSections/UserRequests/UserRequests.test.js, src/views/UserDetail/UserDetail.js, src/views/UserDetail/UserDetail.test.js
[UIU-2987](https://issues.folio.org/browse/UIU-2987) - User details: Disable action menu for DCB virtual user 
Disable "Actions" menu, "Create block", "Create Request", "Create fee/fine", "New" buttons when selected user is of type "dcb".
Improved a unit test to clear a console error in test run.
Activated a unit test, based on comments placed earlier. …
=> UIU-2987 - Hide all actionalble buttons on user details pane

CHANGELOG.md, src/views/LoanDetails/LoanDetails.js, src/views/LoanDetails/LoanDetails.test.js
Link to PR with master branch as target - https://github.com/folio-org/ui-users/pull/2597
=> UIU-2966-poppy-dcb

CHANGELOG.md, src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/ClosedLoans/ClosedLoans.test.js, src/components/util/util.test.js
[UIU-2989](https://issues.folio.org/browse/UIU-2989) - User - Closed Loans: UI changes for supporting DCB circulation
1. Borrowing-pickup library - Item details action menu item is hidden
2. Lending Library - right aligned set of action buttons and all action menu items except item details are hidden.
3. Pickup library - action menu trigger itself hidden, also right aligned set of action buttons are hidden
- Are the JIRAs under …
=> UIU-2989 - User - Closed Loans: UI changes for supporting DCB circulation

CHANGELOG.md, src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/ClosedLoans/ClosedLoans.test.js
Link to master branch PR - https://github.com/folio-org/ui-users/pull/2600/files
=> UIU-2989-poppy-dcb - Closed Loans: UI changes for supporting DCB circulation.

CHANGELOG.md, src/components/data/static/loanActionMap.js, src/components/data/static/loanActionMap.test.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-3014
Add `reminderFee` to loan action map.
=> UIU-3014: Add reminderFee to loan action map

CHANGELOG.md, package.json, translations/ui-users/en.json
[UIU-3018](https://issues.folio.org/browse/UIU-3018) - Add ‘Users: Can view profile pictures’ permission. …
=> UIU-3018 - Create new permission 'Users: Can view profile pictures'.

CHANGELOG.md, src/components/UserAddresses/UserAddresses.js, src/components/UserAddresses/UserAddresses.test.js, test/jest/__mock__/intl.mock.js
[UIU-2976](https://issues.folio.org/browse/UIU-2976) - Show country name in user detail screen …
=> UIU-2976 - Show country name in user address instead of country id.

CHANGELOG.md, package.json
[UIU-3038](https://issues.folio.org/browse/UIU-3038) -  Update sub permissions of permission 'Users: Can view user profiles'. …
=> UIU-3038 - Update sub permissions of permission 'Users: Can view user profiles'.

CHANGELOG.md, src/components/Accounts/ViewFeesFines/ViewFeesFines.js
Use correct field for display remaining in list
https://issues.folio.org/browse/UIU-3049
=> UIU-3049: Use correct field for display remaining in list

CHANGELOG.md, src/components/Loans/OpenLoans/helpers/getListDataFormatter.js
[UIU-2983](https://folio-org.atlassian.net/browse/UIU-2983)
https://github.com/folio-org/ui-users/assets/105021655/cee14c92-3138-4fe1-b17b-50f2cd9a8f9a
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> Open Loans title case sensitive sorting

CHANGELOG.md, package.json, src/components/EditSections/EditUserInfo/components/EditUserProfilePicture/EditUserProfilePicture.js, src/components/EditSections/EditUserInfo/components/EditUserProfilePicture/EditUserProfilePicture.test.js, src/components/EditSections/EditUserInfo/components/LocalFileModal/components/Slider/Slider.css, src/components/EditSections/EditUserInfo/components/LocalFileModal/components/Slider/Slider.js, yarn.lock
[UIU-3064](https://folio-org.atlassian.net/jira/software/c/projects/UIU/boards/76?assignee=712020%3A5ca69dba-5ba2-4ee1-be22-97e32eeff056&selectedIssue=UIU-3064) -  Implement client-side compression for Profile Pictures.
I have used an open source JavaScript library [compressor.js](https://github.com/fengyuanchen/compressorjs) to perform image compression prior to uploading to backend.
https://github.com/folio-org/ui-users/assets/105021655/182bbc5d-603d-4a2b-92c8-ced407820eed
- …
=> UIU-3064 - profile picture FE compression

src/components/EditSections/EditUserInfo/components/EditUserProfilePicture/EditUserProfilePicture.js, src/components/EditSections/EditUserInfo/components/EditUserProfilePicture/EditUserProfilePicture.test.js
[UIU-3047](https://folio-org.atlassian.net/jira/software/c/projects/UIU/boards/76?assignee=712020%3A5ca69dba-5ba2-4ee1-be22-97e32eeff056&selectedIssue=UIU-3047) -  Fix callout message on same local file upload.
While uploading a file locally, if the file exceeds maxFileSize from configurations user will see an error Callout.
When user uploads the same file again, a new error callout does not get displayed. This PR is to address this issue.
- Do JIRAs exist to update the impacted …
=> UIU-3047 - Fix callout message on same file upload (follow-up)

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UIU-3073
**Note:** version in package.json has been updated earlier. Hence it is not needed to be updated now.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> Release v10.1.0

CHANGELOG.md
This is a follow up PR to update changeLog.md file for ticket [UIU-3104](https://folio-org.atlassian.net/browse/UIU-3104). …
=> UIU-3104 - use Profile Picture stripes/smart-component in ui-users (follow-up)

CHANGELOG.md, src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/util/util.js, src/components/util/util.test.js, src/views/LoanDetails/LoanDetails.js
[UIU-3020](https://folio-org.atlassian.net/browse/UIU-3020) - Rename isDCBItem function to isDcbItem. …
=> UIU-3020 Rename isDCBItem function to isDcbItem

CHANGELOG.md, package.json, translations/ui-users/en.json
https://folio-org.atlassian.net/browse/UIU-3116 - Add “Users: Can view reading room access” permission …
=> UIU-3116 - Create new permission 'Users: Can view reading room access'

CHANGELOG.md, package.json, translations/ui-users/en.json
https://folio-org.atlassian.net/browse/UIU-3117 - Add “Users: Can view, and edit reading room access” permission …
=> UIU-3117 - Create new permission 'Users: Can view, and edit reading room access'

CHANGELOG.md, package.json, src/components/Loans/OpenLoans/OpenLoansControl.js, src/components/Wrappers/withRenew.js, src/components/Wrappers/withRenew.test.js, translations/ui-users/en.json
This PR intends to release https://folio-org.atlassian.net/browse/UIU-3135 for Quesnelia BugFix …
=> Release v10.1.1

CHANGELOG.md
This PR intends to update the change log to reflect Q bug fix release v10.1.1
While it's …
=> UIU-3142 - update change log to reflect Q bug fix release

CHANGELOG.md, src/constants.js, src/views/UserSearch/Filters.js, translations/ui-users/en.json
[UIU-3016](https://folio-org.atlassian.net/browse/UIU-3016) - Include DCB in 'User Type' search filter group.
https://github.com/folio-org/ui-users/assets/105021655/4e507fd4-7929-4135-ad58-9cf50a05c24b …
=> UIU-3016 - Include DCB in 'User Type' search filter group

CHANGELOG.md, src/components/EditSections/EditUserRoles/components/UserRolesList/UserRolesList.js, src/components/EditSections/EditUserRoles/components/UserRolesList/UserRolesList.test.js, src/components/EditSections/EditUserRoles/components/UserRolesModal/UserRolesModal.js, src/components/EditSections/EditUserRoles/components/UserRolesModal/index.css, translations/ui-users/en.json
This PR fixes comments from QA-team for [UIU-3124](https://folio-org.atlassian.net/browse/UIU-3124) ticket …
=> UIU-3124: fix filter issues in search form for user roles modal

CHANGELOG.md, src/settings/AddressTypesSettings.js, src/settings/CommentRequiredSettings.js, src/settings/ConditionsSettings.js, src/settings/CustomFieldsSettings.js, src/settings/DepartmentsSettings.js, src/settings/FeeFineSettings.js, src/settings/LimitsSettings.js, src/settings/OwnerSettings.js, src/settings/PatronGroupsSettings.js, src/settings/PaymentSettings.js, src/settings/RefundReasonsSettings.js, src/settings/TransferAccountsSettings.js, src/settings/TransferCriteriaSettings/TransferCriteriaSettings.js, src/settings/WaiveSettings.js, src/settings/index.js, src/settings/patronBlocks/BlockTemplates/BlockTemplates.js, src/settings/patronBlocks/Conditions/Conditions.js, src/settings/patronBlocks/Conditions/Conditions.test.js, src/settings/permissions/PermissionSetDetails.js, src/settings/permissions/PermissionSets.js, translations/ui-users/en.json
[UIU-2935](https://folio-org.atlassian.net/browse/UIU-2935) - Add HTML page titles for each page in Users Settings.
Implemented all Users Settings Page title using [TitleManager](https://github.com/folio-org/stripes-core/blob/master/src/components/TitleManager/TitleManager.js) Component from stripes-core.
Ideally all of the PRs involved in breaking changes …
=> UIU-2935 - Add html title for Users Settings Page

CHANGELOG.md, package.json, src/components/util/util.js, src/routes/UserRecordContainer.js, src/views/UserDetail/UserDetail.js
[UIU-3146](https://folio-org.atlassian.net/browse/UIU-3146) - Make dependency on mod-reading-rooms optional.
fetch request in manifest of "src/routes/UserRecordContainer.js" has been refactored to execute only when 
1. when user is patron or staff type
2. when "reading-room-patron-permission" interface exists
3. when logged in user has permission "reading-room.patron-permission.item.get"
4. when it is edit form and not create form.
I am not sure if the coverage can be further increased as several files do not have their corresponding test files.
If there are breaking changes, please **STOP** and …
=> UIU-3146 - Make dependency on mod-reading-rooms optional.

CHANGELOG.md, src/components/EditSections/EditReadingRoomAccess/EditReadingRoomAccess.test.js, src/components/EditSections/EditReadingRoomAccess/getFormatter.js
[UIU-3151](https://folio-org.atlassian.net/browse/UIU-3151) - Improve UX of Reading Room Access accordion selection box in User Profile Edit.
Replace [Selection](https://github.com/folio-org/stripes-components/tree/master/lib/Selection) Component with [Select](https://github.com/folio-org/stripes-components/tree/master/lib/Select) Component from @folio/stripes/components.
https://github.com/folio-org/ui-users/assets/105021655/8b6f84a4-c7db-4c47-85f7-8ab9eda837c0
- Do JIRAs exist …
=> UIU-3151 - Improve UX of Reading Room Access accordion selection box in User Profile Edit.

CHANGELOG.md, src/components/EditSections/EditReadingRoomAccess/EditReadingRoomAccess.js, src/components/EditSections/EditReadingRoomAccess/EditReadingRoomAccess.test.js, src/components/EditSections/EditReadingRoomAccess/constants.js, src/components/EditSections/EditReadingRoomAccess/getFormatter.js, src/components/UserDetailSections/ReadingRoomAccess/ReadingRoomAccess.js, src/components/util/util.js, src/routes/UserRecordContainer.js
[UIU-3132](https://folio-org.atlassian.net/browse/UIU-3132) - Reading Room table sorting in User Edit screen.
I do not see any further scope of increasing test case coverage in EditReadingRoomAccess.js file.
Also the coverage of getFormatter.js is 100% in local coverage report. It is not reflecting in SonarCloud Coverage Report.
Ideally all of the PRs …
=> UIU-3132 - Reading Room table sorting in edit screen.

CHANGELOG.md, src/components/PrintLibraryCardButton/PrintLibraryCardButton.js, src/components/PrintLibraryCardButton/PrintLibraryCardButton.test.js, src/components/PrintLibraryCardButton/index.js, src/views/UserDetail/UserDetail.js, translations/ui-users/en.json
[UIU-3159](https://folio-org.atlassian.net/browse/UIU-3159) - Add the 'Print Library Card' action in the Action Menu of User app.
Add a new button "Print Library Card" to action menu of user detail.
**Note:** Implementation of click handler will be achieved via two upcoming tickets. Hence I have added a TODO comment. Sonar Cloud can potentially complain about addressing this.
- Do PRs …
=> UIU-3159 - Add the 'Print Library Card' action in the Action Menu of User app.

CHANGELOG.md, src/components/EditSections/EditUserRoles/EditUserRoles.js, src/components/EditSections/EditUserRoles/EditUserRoles.test.js, src/components/EditSections/EditUserRoles/components/UserRolesModal/UserRolesModal.js, src/components/EditSections/EditUserRoles/components/UserRolesModal/UserRolesModal.test.js, src/components/Wrappers/withUserRoles.js, src/components/Wrappers/withUserRoles.test.js, src/hooks/useAllRolesData/useAllRolesData.js, src/hooks/useAllRolesData/useAllRolesData.test.js, src/hooks/useUserTenantRoles/useUserTenantRoles.js, src/views/UserEdit/UserForm.js
Refs [UIU-3145 ](https://folio-org.atlassian.net/browse/UIU-3145) - sort user roles by name;
Since user roles were only provided as a list of IDs and were being set as the initial state in react-final-form, they were not sorted. The current changes resolve this issue by fetching all roles data alphabetically and sorting the provided IDs according to the all roles data list.
- Do PRs exist …
=> UIU-3145: sort roles by name 

CHANGELOG.md, src/components/EditSections/EditContactInfo/EditContactInfo.js, src/components/EditSections/EditContactInfo/EditContactInfo.test.js, src/components/UserDetailSections/ContactInfo/ContactInfo.js
[UIU-3173](https://folio-org.atlassian.net/browse/UIU-3173) - Fix user input error in preferredEmailCommunication input field.
https://github.com/user-attachments/assets/ccbf6c2f-c69d-4857-a744-f0571fa001ca …
=> UIU-3173 - Fix user input error in preferredEmailCommunication input field

CHANGELOG.md, src/components/PrintLibraryCardButton/PrintLibraryCardButton.js, src/components/PrintLibraryCardButton/PrintLibraryCardButton.test.js, src/constants.js
UIU-3175(https://folio-org.atlassian.net/browse/UIU-3175) - Export user details CSV file enhancements.
Columns names in the csv file needs to be in English ONLY. Hence the localization has been removed.
Also, when the profile picture of the user whose details are being exported, is an external url, it needs to be added as the last column and not be exported.
- Do PRs exist for these …
=> UIU-3175 - Export user details CSV file enhancements.

CHANGELOG.md, src/components/EditSections/EditUserInfo/components/EditUserProfilePicture/EditUserProfilePicture.js
[UIU-3177](https://folio-org.atlassian.net/browse/UIU-3177) - update Profile Picture configurations to improve profile-pic quality.
Config Change results :-
To improve profile picture quality while exporting the picture of a Users via 'Print Library Card' action in User Info Screen.
https://github.com/user-attachments/assets/cb340051-194e-4099-b5be-9907b824f987
- Do PRs exist for these …
=> UIU-3177 - Improve User Profile Picture quality

CHANGELOG.md, src/components/PrintLibraryCardButton/PrintLibraryCardButton.js, test/jest/__mock__/intl.mock.js
[UIU-3174](https://folio-org.atlassian.net/browse/UIU-3174) - Update expiration date format in export user details
Update user expiration date from mm/dd/yyyy format to dd/mm/yyyy format, exported csv file …
=> UIU-3174 - Update expiration date format in export user details

CHANGELOG.md, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, src/components/EditSections/EditUserInfo/EditUserInfo.js
[UIU-3176](https://folio-org.atlassian.net/browse/UIU-3176) - Fix Expiration Field date selection issue after clearing e…
https://github.com/user-attachments/assets/58a2e081-6578-43a5-a71b-a6074b3162f2 …
=> UIU-3176 - Fix "Expiration Field" date selection issue after clearing expiration date field

CHANGELOG.md, src/components/data/converters/address.js, src/components/data/converters/address.test.js
[UIU-3188](https://folio-org.atlassian.net/browse/UIU-3188) - Populate Address Fields on user creation via edge module
On user creation via LoC edge API populate following fields on UI: 
- "State/Prov./Region"
- "Zip/Postal Code" 
- "Country"
The address type for an LOC user will always be set to "Home" and the address will be designated as the "Primary Address" on user creation.
https://github.com/user-attachments/assets/bd59edcc-76af-4ea4-86fa-8cf6ab7614d4
- Do JIRAs exist to …
=> UIU-3188 - Populate Address Fields on user creation via edge module

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, package.json, src/routes/UserSearchContainer.js, src/routes/UserSearchContainer.test.js
This PR intends to release https://folio-org.atlassian.net/browse/UIU-3184 for Quesnelia CSP#4 …
=> UIU-3184 - Use keywords CQL field for keyword user search. (#2737)

CHANGELOG.md
UIU-3203 - update change log file to reflect Q CSP#4 release
While it's helpful for …
=> UIU-3203 - update change log file to reflect Q CSP#4 release

CHANGELOG.md, src/routes/UserRecordContainer.js
[UIU-3102](https://folio-org.atlassian.net/browse/UIU-3102) - revert conditional use of the users-keycloak interface …
=> UIU-3102: Revert conditional use of the users-keycloak interface in UserRecordContainer 

CHANGELOG.md, src/views/LoanDetails/LoanDetails.js
https://folio-org.atlassian.net/browse/UIU-3210
Missed part of: #2751 
Disable the print button for closed loans.
https://github.com/user-attachments/assets/4a60336e-5357-49bd-92c6-ff2a106fc814
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> UIU-3210 Loan details: Print Due date receipt

CHANGELOG.md, package.json
=> UIU-3229 Update `notes` to `v4.0`

CHANGELOG.md, package.json, src/components/LinkToPatronPreRegistrations/LinkToPatronPreRegistrations.js, src/routes/PatronPreRegistrationRecordsContainer.js, src/views/PatronsPreRegistrationListContainer/PatronsPreRegistrationListContainer.js, src/views/PatronsPreRegistrationListContainer/PatronsPreRegistrationListContainer.test.js, translations/ui-users/en.json
=> UIU-3221 - create new permission 'Users: Can view patron preregistration data'

CHANGELOG.md, src/hooks/index.js, src/hooks/useStagingUserMutation/index.js, src/hooks/useStagingUserMutation/useStagingUserMutation.js, src/hooks/useStagingUserMutation/useStagingUserMutation.test.js, src/routes/PatronPreRegistrationRecordsDuplicatesPage.test.js, src/views/PatronPreRegistrationRecordsDuplicates/PatronPreRegistrationRecordsDuplicates.js, src/views/PatronPreRegistrationRecordsDuplicates/PatronPreRegistrationRecordsDuplicates.test.js, src/views/PatronPreRegistrationRecordsDuplicates/PreRegistrationRecordsDuplicatesList/PreRegistrationRecordsDuplicatesList.js, src/views/PatronPreRegistrationRecordsDuplicates/PreRegistrationRecordsDuplicatesList/PreRegistrationRecordsDuplicatesListContainer.js, translations/ui-users/en.json
https://folio-org.atlassian.net/browse/UIU-3225
Use the `staging-users` API to merge a staging user with an existing one.
https://github.com/user-attachments/assets/1467d8fe-94e9-4b85-b416-1dbca0392264 …
=> UIU-3225 Integrate action to merge preregistration patron record with existing user record

src/utils/getFullName.js, src/utils/index.js, src/views/PatronPreRegistrationRecordsDuplicates/PreRegistrationRecordsDuplicatesList/PreRegistrationRecordsDuplicatesList.js, src/views/UserSearch/UserSearch.js
https://folio-org.atlassian.net/browse/UIU-3224
While it's helpful for reviewers to help …
=> UIU-3224 Fix data visualization issues on the duplicates list

CHANGELOG.md, package.json
This PR intends **release ui-users module for Ramsons.**
While it's helpful for reviewers to …
=> Release v11.0.0

CHANGELOG.md, package.json, src/components/Loans/OpenLoans/components/PrintToPDFWrapper/PrintTemplate.js, src/hooks/usePrintData/usePrintData.js, yarn.lock
https://folio-org.atlassian.net/browse/UIU-3239
While it's helpful for reviewers to help …
=> UIU-3239 Process more item tokens in due date print

CHANGELOG.md, src/routes/UserRecordContainer.js
[UIU-3234](https://folio-org.atlassian.net/browse/UIU-3234) - Delete a user from Keycloak when it is deleted in UI …
=> UIU-3234: Delete a user from Keycloak when it is deleted in UI

package.json
=> UIU-3214 clean up permissions

CHANGELOG.md, package.json
=> update changelog and package.json versions

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UIU-3259
- change permssion 
it will be merged after prs 
https://github.com/folio-org/mod-circulation/pull/1508
https://github.com/folio-org/mod-feesfines/pull/299
=> [UIU-3259] - Fix permission changes for mod-circulation

CHANGELOG.md, src/views/PatronsPreRegistrationListContainer/PatronsPreRegistrationList.js, src/views/PatronsPreRegistrationListContainer/PatronsPreRegistrationList.test.js, src/views/PatronsPreRegistrationListContainer/PatronsPreRegistrationListContainer.js
[UIU-3249](https://folio-org.atlassian.net/browse/UIU-3249) - Pagination is not working correctly on "Patron preregistration record results" page
Leverage API supported sorting of columns on pre-registrations records list.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> UIU-3249 - Leverage API supported sorting of columns on pre-registrations records list.

CHANGELOG.md, package.json
[UIU-3282](https://folio-org.atlassian.net/browse/UIU-3282) - User with minimal required capabilities cannot delete a user
Add necessary permission based on mod-users-keycloak descriptors https://github.com/folio-org/mod-users-keycloak/blob/master/descriptors/ModuleDescriptor-template.json#L40
Ideally all of the PRs involved in breaking changes would be …
=> UIU-3282: add capability to access users-keycloak delete method

CHANGELOG.md, package.json, src/routes/LoanDetailContainer.js, src/routes/LoansListingContainer.js, src/views/UserDetail/UserDetail.js
Update permission after BE permission changes
https://issues.folio.org/browse/UIU-3288
=> UIU-3288: Update permission after BE permission changes

CHANGELOG.md, package.json
Update "ui-users.feesfines.actions.all" permission.
Follow up PR for https://github.com/folio-org/ui-users/pull/2819
[UIU-3291](https://folio-org.atlassian.net/browse/UIU-3291)
=> UIU-3291: Permissions error when adding a Fee-Fine via the User's app and Check-in.

CHANGELOG.md
Update changelog after release
[UIU-3297](https://folio-org.atlassian.net/browse/UIU-3297)
=> UIU-3297: Update changelog after release

CHANGELOG.md, package.json
update change log and package.json files after release v11.0.9
While it's helpful for …
=> update change log and package.json files after release v11.0.9

CHANGELOG.md, src/components/UserDetailSections/PatronBlock/PatronBlock.js
Hide Create block button for user without permission
https://folio-org.atlassian.net/browse/UIU-3300
=> UIU-3300: Hide Create block button for user without permission

CHANGELOG.md, package.json
Rename permission after BE changes
https://folio-org.atlassian.net/browse/UIU-3309
=> UIU-3309: Rename permission after BE changes

CHANGELOG.md
Update changelog after release
https://folio-org.atlassian.net/browse/UIU-3313
=> UIU-3313: Update changelog after release

CHANGELOG.md, src/components/UserDetailSections/UserInfo/UserInfo.js, src/views/UserDetail/UserDetail.css, src/views/UserDetail/UserDetail.js, src/views/UserDetail/UserDetail.test.js, src/views/UserEdit/UserForm.css, src/views/UserEdit/UserForm.js
Show user pronouns within the user view pane if they're present.
https://folio-org.atlassian.net/browse/UIU-3118
=> UIU-3118: Pronoun Field - User Record View

CHANGELOG.md, package.json, yarn.lock
https://folio-org.atlassian.net/browse/UIU-3342
=> Release v12.0.0

CHANGELOG.md, src/components/Accounts/Actions/ActionModal.js
Change amount input type to number
https://folio-org.atlassian.net/browse/UIU-2836
=> UIU-2836: Change amount input type to number

CHANGELOG.md, src/hooks/useUserAffiliationRoles/useUserAffiliationRoles.js, src/hooks/useUserAffiliationRoles/useUserAffiliationRoles.test.js, src/views/UserDetail/UserDetail.js, src/views/UserEdit/UserForm.js
=> UIU-3360: Release 12.1.1

CHANGELOG.md, package.json
=> release v12.1.1

CHANGELOG.md, package.json, src/components/EditSections/EditUserInfo/EditUserInfo.js, src/components/EditSections/EditUserInfo/components/EditUserProfilePicture/EditUserProfilePicture.js, src/components/EditSections/EditUserInfo/components/EditUserProfilePicture/EditUserProfilePicture.test.js, src/components/EditSections/EditUserInfo/components/LocalFileModal/LocalFileModal.css, src/components/EditSections/EditUserInfo/components/LocalFileModal/components/Slider/Slider.css, src/components/EditSections/EditUserInfo/components/LocalFileModal/components/Slider/Slider.js, src/components/EditSections/EditUserInfo/components/WebcamModal/WebcamModal.js, src/components/EditSections/EditUserInfo/components/WebcamModal/WebcamModal.test.js, src/components/EditSections/EditUserInfo/components/WebcamModal/index.js, src/components/EditSections/EditUserInfo/components/index.js, translations/ui-users/en.json, yarn.lock
Allow to take a patron's profile picture photo using a webcam in the Users app.
This implementation builds on @Terala-Priyanka’s POC (https://github.com/folio-org/ui-users/commit/cabc8e054dd7c3690bff7af22b42f4919c4e327e).
https://folio-org.atlassian.net/browse/UIU-3266
=> UIU-3266: Add Patron Photo Capture Modal

CHANGELOG.md, package.json
…
Refs [UIU-3363](https://folio-org.atlassian.net/browse/UIU-3363). 
While it's helpful for …
=> UIU-3363: add missed permissions ui-users.roles.view to ui-users.roles.manage

CHANGELOG.md, src/components/EditSections/EditUserInfo/EditUserInfo.js
https://folio-org.atlassian.net/browse/UIU-3318
=> UIU-3318: Fix 'Expiration date' field value when non-default locale is applied

CHANGELOG.md, src/components/PatronBlock/PatronBlockMessage.js, src/components/PatronBlock/PatronBlockMessage.test.js, src/views/UserDetail/UserDetail.css, src/views/UserDetail/UserDetail.js
Use Message Banner stripes component for user patron blocks warning.
[UIU-3120](https://folio-org.atlassian.net/browse/UIU-3120)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
=> UIU-3120: Replace `TextField` with `MessageBanner` for patron block warning.

CHANGELOG.md, src/components/PatronBlock/PatronBlockMessage.js, src/components/PatronBlock/PatronBlockMessage.test.js, src/views/UserDetail/UserDetail.js, translations/ui-users/en.json, translations/ui-users/en_US.json
Display the message `Patron has block in place.` when there is only one patron block, and the message `Patron has blocks in place.` when there are multiple.
[UIU-3394](https://folio-org.atlassian.net/browse/UIU-3394)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> UIU-3394: Update patron block message to support pluralization.

CHANGELOG.md, src/views/LoanDetails/LoanProxyDetails.js
Proxy Borrower field does not equal Unknown user
https://folio-org.atlassian.net/browse/UIU-3373
=> UIU-3373: Proxy Borrower field does not equal Unknown user

CHANGELOG.md, package.json, src/routes/LoanDetailContainer.js, src/routes/LoansListingContainer.js
Make `circulation-bff-loans` dependency optional in folio_users UI module.
[Previously](https://github.com/folio-org/ui-users/pull/2910), the endpoint `/circulation/loans` was used, then it was changed to `/circulation-bff/loans`. The current task requires that the `/circulation-bff/loans` interface be made optional. It was decided by the team lead to use  `/circulation/loans` if `/circulation-bff/loans` is not available.
https://folio-org.atlassian.net/browse/UIU-3409
- Do …
=> UIU-3409: Make `circulation-bff-loans` dependency optional in folio_users UI module.

CHANGELOG.md, package.json, src/components/ModalContent/ModalContent.js, src/components/ModalContent/ModalContent.test.js
Add support for use circulation-bff for declare-item-lost
https://folio-org.atlassian.net/browse/UIU-3414
=> UIU-3414: Add support for use circulation-bff for declare-item-lost

CHANGELOG.md, package.json, src/components/Loans/OpenLoans/components/BulkClaimReturnedModal/BulkClaimReturnedModal.js, src/components/ModalContent/ModalContent.js, src/components/ModalContent/ModalContent.test.js, src/constants.js
Add support for use circulation-bff for claim-item-returned
https://folio-org.atlassian.net/browse/UIU-3413
=> UIU-3413: Add support for use circulation-bff for claim-item-returned

CHANGELOG.md
=> Release v12.1.13
