Users.js
This is a smaller PR which only restores the initial state of the search list when the search box has been cleared using the backspace button.
=> Restoring user search results when query is empty

Users.js
So that it can be available right off the bat, the username has been added to the path pattern in addition to the user id. This is so that the permissions can be obtained via the username. This resolves [STRIPES-193](https://issues.folio.org/browse/STRIPES-193)
=> Added username to the view path pattern

UserPermissions.js, lib/ListDropdown/ListDropdown.js
The permissions are now filtered and displayed based on their displayNames, instead of permissionName
=> Permission names are now displaying displayName

UserPermissions.js, lib/RenderPermissions/RenderPermissions.css, lib/RenderPermissions/RenderPermissions.js, lib/RenderPermissions/index.js
This PR addresses the concerns in [STRIPES-289](https://issues.folio.org/browse/STRIPES-289).
It separates out the presentation aspects of UserPermissions into a new component: RenderPermissions. All of the stripes-connect aspects of the permission management functionality are conducted in UserPermissions and then passed down into RenderPermissions. This should allow RenderPermissions to be reused in other contexts. (i.e. [LIBAPP-83](https://issues.folio.org/browse/LIBAPP-83))
=> Stripes 289

package.json
Permission set already defined in mod-users-bl/ModuleDescriptor.json. Towards STRIPES-435.
=> Update package.json to remove users-bl.all permission set.

Users.js
This addresses issue [UIS-71](https://issues.folio.org/browse/UIS-71)
This creates conditional logic for the new button, allowing props to be passed into the user module that can disable the display of the create new user button.
=> Added conditional logic from the displat of 'new' button

LoansHistory.js, data/loanHistoryMap.js
Show the *item's* status, not the loan's status, for each item on the
loans history pane.
=> show item status on loan list pane. Fixes UIU-175

ProxyPermissions.js, UserForm.js, UserLoans.js, ViewUser.js, lib/RenderPermissions/RenderPermissions.js, lib/UserAddresses/UserAddresses.js
This touched the components in the View User page, performing a bit of surgery on each to get the accordions wired up to eventually have them persist on a local resource.
Before I went through this step I attempted to keep the Accordions at the top, wrapping the components - but the design requires the accordion headers to contain buttons that interact with the sub-sections - and show/hide these buttons based on the open or closed status of the accordion. There isn't any good non-hacky way for a parent to reach in and use the code that's already present in a child component (only props, themselves) so I just ended up incorporating the Accordions themselves into the components, passing in the appropriate props to control them from ViewUser...
In addition to this, the AddressList component …
=> STCOM-20  Accordionate the Sections of User Details

package.json
Since Users.js uses the Notes 0.2.0 API, package.json better require the
Notes 0.2.0 API.
=> sync package.json's Notes dep with that in Users.js

CHANGELOG.md, ViewUser.js, package.json
This PR adds an 'expand all' button above the `<Accordion>`s on in the View User page.  The button label will dynamically change depending on the majority state of the accordions. If more accordions are closed, it becomes 'expand all', if more are open, 'collapse all'.
This PR also bumps deps on Stripes-components to 1.8.0
=> Stcom 71 expand all

ProxyPermissions.js, ViewUser.js
Adds the `editable` prop to the Proxy Permissions component and flips it 'on' in ViewUsers - once the section is incorporated into the UserForm, we can remove the prop from ViewUsers, and set it in the form.
=> UIU 243 read-only proxy section

CHANGELOG.md, ViewUser.js, lib/RenderPermissions/RenderPermissions.js
Adds the switch for 'read-only' and 'edit' modes via an 'editable' prop. Sets the component as editable in ViewUser until it is integrated into UserForm.
=> UIU-244 read only permissions section

lib/UserAddresses/UserAddresses.js
expose 'editable' prop in UserAddresses.js. Since this prop **is not** passed in the ViewUser component, addresses will become read-only there. They will remain editable in the user 'edit' view.
=> UIU-242 read-only address section - pass 'editable' prop through to AddressList component

CHANGELOG.md, package.json, settings/AddressTypesSettings.js, settings/PatronGroupsSettings.js
Allows us to use <ControlledVocab>
=> Use `<ControlledVocab>` from stripes-smart-components

CHANGELOG.md, Users.js
Hopefully alleviating the painfully annoying symptom that was noticeable on the projector at Montreal and occurs on almost everyone else's development/demo machine except for my own!
=> STCOM-40  Apply <Pane>'s 'noOverflow' prop to results pane

lib/Autocomplete/Autocomplete.css
Removing Bootstrap's global CSS from `stripes-core` (https://github.com/folio-org/stripes-core/pull/61) breaks the `Autocomplete` component used for country selection in addresses.
This should unblock https://github.com/folio-org/stripes-core/pull/61, so we can move toward the intended font stack and surface other CSS that was leaning too heavily on the global Bootstrap styles.
I copied over bits and pieces of Bootstrap CSS into the `Autocomplete` component's CSS as a stop-gap until there's an autocomplete component available in `stripes-components` up to FOLIO standards. Now the component is still functional without Bootstrap CSS, even though it will show the "Close" text previously hidden by a global `.sr-only` class.
The `Autocomplete` component, with the contents of this PR and no …
=> Prepare Autocomplete for Bootstrap global css removal

Users.js, lib/SearchAndSort/SearchAndSort.js
Since that utility component was already using the react-router props
for other reasons, it makes sense to also have it extract and parse
the query when it needs to. This simplifies the API to
`<SearchAndSort>`.
Another part of UIU-299.
=> No need to pass parsed URL query into <SearchAndSort>

lib/SearchAndSort/SearchAndSort.js
Yes. A pull-request, with all the attendant song-and-dance, in order to change a plainly incorrect "object" to "string". Because "quality". I guess I'll go and make a cup of tea while I wait for the tests to run before I can merge. La la la, quality!
=> Fix incorrect propType for parentResources.query.filters

lib/OpenLoans/OpenLoans.js
Explain to the user why the Renew button is disabled (no loans selected) with a rollover tooltip.
Using plain html title= attribute for tooltips.
=> UIU-305 Add tooltip on disabled renew button

CHANGELOG.md, lib/ViewSections/UserLoans/UserLoans.js
A named URL parameter changed from "userid" to "id" as a result of
refactoring this module to use stripes-smart-components' SearchAndSort,
causing code that relied on the previous name to fail.
=> display user loan count (regression). Fixes UIU-308

settings/PatronGroupsSettings.js
adding a manifest to a parent component of ControlledVocab causes PUT and DELETE to break
=> replaced controlled vocab with editable list

Users.js
Uses the new reset/clear button functionality introduced in:
- https://github.com/folio-org/stripes-components/pull/164
- https://github.com/folio-org/stripes-smart-components/pull/69
Also made the `filterConfig` updating not use hardcoded indices.
=> Use default filters for "Reset all" filter button

CHANGELOG.md, lib/EditablePermissions/EditablePermissions.js, lib/RenderPermissions/RenderPermissions.js
Use consistent language. Fixes [UX-115](https://issues.folio.org/browse/UX-115).
=> Use consistent language for 'no attribute found' messages. Fixes UX-115

CHANGELOG.md, settings/PatronGroupsSettings.js
Fixes [UIU-364](https://issues.folio.org/browse/UIU-364) using the really nice `suppressor: { delete: (item ) => ..., edit: (item) => ...}` interface @mkuklis and @JohnC-80 implemented in `EditableList`. So easy.
=> disable delete of non-empty patron groups. Fixes UIU-364

ViewUser.js
Moved notes to the end of the details pane PaneHeader (should be consistent across all apps)
=> Quick fix: Moved notes icon

lib/RenderPatronGroup/RenderPatronGroupLastUpdated.js, lib/RenderPatronGroup/RenderPatronGroupNumberOfUsers.js, settings/AddressTypesSettings.js, settings/PatronGroupsSettings.js, test/ui-testing/patron_group.js
Updated Patron Group CRUD to use new features/API of <EditableList> once https://github.com/folio-org/stripes-components/pull/191 is merged in.
In short, it trades the `availableFields` API for the `formatters` API of `<MultiColumnList>`
It also includes configurable column header labels and the ability to set read-only fields.
Additionally, tests have been updated and the component has grown a few new, important `id` attributes.
=> UIU-264 Patron group CRUD headers

UserForm.js, lib/EditSections/EditContactInfo/EditContactInfo.js, lib/EditSections/EditExtendedInfo/EditExtendedInfo.js, lib/EditSections/EditProxy/EditProxy.js, lib/EditSections/EditUserInfo/EditUserInfo.js, lib/EditablePermissions/EditablePermissions.js, settings/ProfilePictureForm.js
Adding marginBottom0 prop to buttons that doesn't need margin bottom. The reason is that we are re-adding the default margin on buttons.
While I was adding the props in a few places I came across some minor things on edit user that I decided to fix:
- Fixed headers on accordions
- Added accordion to edit user info
- Fixed PaneHeader (added IconButton for close icon and removed icons from PaneTitle)
=> Adding marginbottom0 to buttons + more

CHANGELOG.md, Users.js
The desired behavior of this app when used as a plugin as via
ui-plugin-find-users is different than when used as a standalone app. On
its own, a search that results in a single row should show that entry's
details pane. As part of a plugin, when being displayed in a modal, a
search that results in a single row should simply show that single row.
This change restores the previous functionality of the app when used as
a plugin while still allowing the app to take advantage of
SearchAndSort's show-single-row feature when used independently.
Refs [STSMACOM-52](https://issues.folio.org/browse/STSMACOM-52), [UIIN-58](https://issues.folio.org/browse/UIIN-58), [UIREQ-60](https://issues.folio.org/browse/UIREQ-60), [UICHKOUT-54](https://issues.folio.org/browse/UICHKOUT-54), …
=> SearchAndSort's show-single-row is now optional

lib/EditSections/EditExtendedInfo/EditExtendedInfo.js, lib/ProxyGroup/ProxyEditList/ProxyEditList.js
Follow-up to https://github.com/folio-org/stripes-components/pull/209.
1. `secondary` and `hollow` are no longer available button styles
2. The user edit view had inconsistent styles for "New" buttons:
They're now all `default` button style, not a mix of `default` and `primary`.
=> Improve button style consistency

lib/OpenLoans/OpenLoans.js
https://issues.folio.org/browse/UIU-386
The bug is that renewing a loan sets the loan's loan date to the current time.
With this PR, renewing a loan does not change the loan date.
=> UIU-386: do not change loanDate on renewal

package.json
This pulls in v0.8.x of react-overlays, rather then v0.7.x as before,
and so avoids a clash with the v0.8.x used by stripes-core.
Resolves the last part of STCOR-167.
=> Upgrade react-bootstrap-typeahead dependency to v2.4.0

lib/ProxyGroup/ProxyViewList/ProxyViewList.js, lib/ViewSections/UserInfo/UserInfo.js
The goal of STCOM-198 is clean up the "outlining" of folio modules at the component level and, in some cases, within the modules themselves.
This PR corresponds with PR's in both `stripes-components` and `stripes-core` (will add shortly)
Using the "Headings List" of the NVDA screen-reader the before-and-after states can be seen:
Before:
After: Notice the hierarchy of content is captured with the Main Navigation and 3 Panes at level 2, having sub-pane content also arranged within.
=> STCOM-198 Use semantic tags, update headings.

Users.js
JIRA: [Sorting on the "Status" field didn't work.](https://issues.folio.org/browse/UIU-401)
Made use of the `columnMapping` prop to provide the correct key to sort on to mod-users.
=> UIU-401: Fixed bug where sorting by user status didn't work

CHANGELOG.md, package.json
=> Modal users-in-users app can now search again, thanks to the STCOM-226 fix

test/ui-testing/new_proxy.js, test/ui-testing/patron_group.js
The Users module was changed to not show any users on initial load. This PR changes the tests to check the 'Active' filter to ensure that a list of users is fetched and displayed.
=> UIU-424: Updated tests to handle empty users list onload

UserForm.js, ViewUser.js
We added the functionality of adding AppIcon in a PaneHeader so this is a minor update to activate that feature in ui-users.
This can be passed down from Pane as well like so: ` <Pane appIcon={{ app: 'users' }} />`. For more info check out the storybook -> Pane -> readme.
=> Added app icon in PaneHeader's

lib/EditSections/EditUserInfo/EditUserInfo.js
Resolves [UIU-391](https://issues.folio.org/browse/UIU-391)
Checks to see if the patron group has a description and only appends the
parenthetical if the description exits.
=> Preventing display of empty parentheses

package.json, settings/PatronGroupsSettings.js
PatronGroupSettings should show the Delete button for all patron groups but disable the button for groups that currently have members. 
Currently, the button is simply hidden by using the actionSuppression. [This uses the new actionProps prop added here](https://github.com/folio-org/stripes-components/pull/274).
=> UIU-431: Show but disable the Delete button for in-use patron groups

test/ui-testing/patron_group.js
PatronGroupSettings were changed to always show the Delete button but leave it disabled. This updates the behaviour expected by the tests.
=> Updated tests to expect a present-but-disabled Delete PG button

CHANGELOG.md, ViewUser.js
Fixes [UIU-418](https://issues.folio.org/browse/UIU-418).
`stripes-components/util/transitionToParams.js` reaches directly to `props.location.query` for the query to update rather than using the anointed resource. (See https://github.com/folio-org/stripes-core/blob/e0d938d97f257f88bbb34481f64ee62408383442/doc/dev-guide.md#url-navigation for details on using an anointed resource to manage the query string, rather than manipulating it directly.)
=> Deprecate transitionToParams in favor of this.props.mutator.query.update

settings/PatronGroupsSettings.js
The validation is being done automatically in `<ControlledVocab>` components now [as of this stripes-smart-components PR.](https://github.com/folio-org/stripes-smart-components/pull/123)
=> PatronGroupSettings: Removed validator

CHANGELOG.md, settings/PatronGroupsSettings.js
We are using facets to do some reporting as though `facets=patronGroup` implements the equivalent of an SQL `group by patronGroup`, which it does not. Facets only retrieve the top five rows by default, but here we force it to retrieve the top 50 on the premise that there are not likely to be that many that many patron groups. 
This is a hack, plain and simple. 
Refs [MODUSERS-57](https://issues.folio.org/browse/MODUSERS-57)
=> Retrieve all patron-groups. Probably. Well, OK only if there are less than 50.

package.json
Update the stripes-components dependency in order to get a list of
countries that maps code to name, rather than name to name, for use in
the country component of the address.
Refs [UIU-416](https://issues.folio.org/browse/UIU-416)
=> use code/name mapping in country-list

package.json
Update the dependency on stripes-smart-components. Earlier versions
contain a bug wherein the `stripes` object is not always passed on to the
new-record handler.
Refs [STSMACOM-75](https://issues.folio.org/browse/STSMACOM-75).
=> make sure stripes is available where necessary

CHANGELOG.md, lib/ProxyGroup/ProxyEditList/ProxyEditList.js
In order to handle internationalized strings in a table-header, we need
to always pass in a map of field-names to header-values rather than
relying on the field-name to match the header-value. The field name,
e.g. username, patronGroup, etc. is never displayed whereas the
header-value, e.g. Username, Patron Group, is.
The header-name may be translated and therefore cannot be used as a key.
Fixes [UIU-452](https://issues.folio.org/browse/UIU-452)
=> pass table-header keys, not values to plugin

lib/Loans/OpenLoans/OpenLoans.js
[Fixed UIU-458](https://issues.folio.org/browse/UIU-458)
Incorrect usage of `this.loan` in the file as opposed to just using the `loan` passed into the callback was the cause.
=> UIU-458: Fixed issue with rendering correct material type for open loans

lib/Loans/OpenLoans/OpenLoans.js
Requested by Cate in: https://issues.folio.org/browse/LIBAPP-233
=> Removed 'Loan Details' from row dropdown in Open Loans

LoansHistory.js
The backend data is not being translated currently so it doesn't make sense to check if a loan is "offen" or "abgeschlossen" if the locale is German since the loan object's status will always either be "open" or "closed".
Backend responses will be translated later but it makes sense to have the system be functional for now, esp given the small footprint of this change and the potential for confusion as evidenced by the fact that UIU-468 was opened.
=> UIU-468: Stopped filtering backend loans data based on translated values

lib/EditSections/EditUserInfo/EditUserInfo.js, translations/en.json
Resolves [UIU-235](https://issues.folio.org/browse/UIU-235).
This puts the UI work in place to disable the status select when the user has expired. It also places a error-style message beneath the field to explain the disabled state. This was not done as validation for two reason:
1) The message needs to show up immediately upon form load, and not only at form submit.
2) The presence of the message should not prohibit form submission.
=> Disabeling the status select when user is expired

CHANGELOG.md, ViewUser.js
We made a major-version update to an Okapi dependency in `package.json` but didn't update the `<IfInterface>` test in the codebase. The discrepancy caused loan information to be unavailable in the user profile. 
Refs [UIU-471](https://issues.folio.org/browse/UIU-471)
=> IfInterface test should match package.json version. Refs UIU-471

CHANGELOG.md, LoanActionsHistory.js, data/loanActionMap.js, lib/Loans/OpenLoans/OpenLoans.js, package.json, translations/en.json
[Per UIU-497](https://issues.folio.org/browse/UIU-497), this adds the ability for users to change the due date of an existing loan without executing a renewal. This uses the new `ChangeDueDateDialog` smart component [introduced here](https://github.com/folio-org/stripes-smart-components/pull/179).
This functionality is available via a user's open loans page, or via the loan details page.
While mucking around in the OpenLoans component, I cleaned up the modal rendering a tad as well.
A subsequent PR that adds this functionality to the Check Out page is coming.
=> UIU-497: Added ability to change loan due dates

CHANGELOG.md, Users.js
=> Use `cql.allIndexes=1` when no query is supplied, instead of a wildcard

lib/ViewSections/UserInfo/UserInfo.js, package.json
There's no need to maintain a separate component to show metadata, so we're switching to the generic one as it gains more functionality as of folio-org/stripes-smart-components#207.
=> STCOM-305: Use generic ViewMetaData component

LoansHistory.js, ViewUser.js, package.json
`LoansHistory` was already being `connect()`ed so rather than taking the `loansHistory` records from it's parent (ViewUser), it now fetches `/circulation/loans` itself so that the fetch can be avoided via `IfPermission` if the logged-in user doesn't have permission to look at loan history.
Also, the decision of whether or not to render the profile photo relies on a check of `/configurations/entries` so I added the permission required to fetch that endpoint to the `ui-users.view` permission set.
=> UIU-558: Split out loan history fetch to avoid permission errors

CHANGELOG.md, lib/ProxyGroup/ProxyEditList/ProxyEditList.js, package.json, test/ui-testing/new_proxy.js
Generation of HTML element-IDs in `<ConfirmationModal>` changed in
https://github.com/folio-org/stripes-components/commit/ce3ba8c996463a389ae3c3aeb36069d9a785ed69
and that broke a bunch of tests that relied on the old style of element
IDs. Happily, we can restore this behavior by passing in an ID prop that
matches the old format.
This necessitated some slight rewriting of the proxy-deletion test which
previously relied on the value of a translated field to generate the
HTML element ID for the confirmation button. In order to avoid that, the
value passed into the ConfirmationModal changed from "deletesponsor" to
"deletesponsors" and from "deleteproxy" to "deleteproxies".
Refs [STCOM-317](https://issues.folio.org/browse/STCOM-317)
=> pass id prop to ConfirmationModal

LoanActionsHistory.js
We'll certainly need to get the loan policy name for the link, but this
is a convenient placeholder for now.
=> link to loan policy

ViewUser.js, package.json
https://github.com/folio-org/eslint-config-stripes/pull/33 pins all rulesets to prevent surprise rule changes.
=> Use eslint-config-stripes 2.0.3

test/ui-testing/new_permission_set.js
- Wait for the deletion request to settle before ending the test.
- Added back the logging of the UUID of the permission set for further debugging in case we need it.
=> Test New Perm Set: Let deletion settle and log uuid

ViewUser.js, package.json
[UIU-585](https://issues.folio.org/browse/UIU-585): We're using `configuration` to get information about whether to show profile pictures.
While I was in the code I also noticed we weren't announcing our dependency on the interface for loan-policy-storage that we use to view a users loans and change their due date and renew them. So I included that in the `package.json` and wrapped the affected components in an `IfInterface` as well.
=> UIU-585: Updated required interfaces

LoansHistory.js
https://issues.folio.org/browse/UIU-602
This PR fixes the issue related to refreshing the `loanHistory` resource after mutation (renew).
It looks like what was happening here is that the string template `:{id}` (extracting data defined by react-router) was never executed. I assume this was due to a fact that `LoansHistory` has no association with the router.
Since we are already passing `user` as a prop the `!{user.id}` template works just fine.
The interesting fact here is that the `loansHistory` resource was actually present (the data was loaded) when the `LoansHistory` component got connected and mounted. The resource data was coming from:
https://github.com/folio-org/ui-users/blob/master/lib/ViewSections/UserLoans/UserLoans.js#L25
Since the resource names match.
=> Change loansHistory params query. Fixes UIU-602

settings/FeeFinesTable/FeeFines.js
Validate was expecting to retrieve an item from a list and then retrieve
a property from that item but not considering the possibility that the
list was empty. This change avoids the null pointer exception in order to
keep the UI from becoming corrupted but does address the underlying
cause. Consequently, validation when the list contains no items always
fails, but at least it doesn't explode when it fails.
=> avoid validation NPE

withServicePoints.js
https://issues.folio.org/browse/STCOR-237
@doytch while working on STCOR-237 I noticed that sometimes when all SPs are removed from the given user the `defaultServicePointId` was still hanging around. This PR is trying to address that.
=> Clean defaultServicePointId when no service points are present. Part of STCOR-237

ViewUser.js, lib/EditSections/EditUserPerms/EditUserPerms.js, package.json
UIU-620 adds a permission set to edit a user's service points. This should _include_ the ability to edit a record in general. Per discussion on that issue with Cate, I extended the permission sets for editing proxies and permissions to also include the generic `ui-users.edit` permission for consistency.
UIU-618 is a bug where we're not checking if we have permissions to view the list of available permissions before fetching them. Made use of @mkuklis' work and threw a `permissionsRequired` prop on the manifest since the rendering permission-gating was already in place.
While doing that I noticed that the edit perms permission doesn't actually include the ability to read the permissions available. Fixed that.
UIU-621 is a bug where saving a user record without "edit proxy" or "edit service …
=> UIU-618, UIU-620, UIU-621: Edit User Permissions bugs and additions

package.json
The npm script, prepublishOnly, fails.   It assumes there is a stripes-core checkout one directory-level higher than this module's root directory.   Really bad assumption.
=> remove prepublishOnly npm script

CHANGELOG.md, ViewUser.js, package.json
*Purpose*
https://issues.folio.org/browse/UIU-627
Support both major versions in order to ease the transition between major versions of the `circulation` and `loan-storage` interfaces  (in order to introduce support loan anonymization)
*Approach*
* Changed the package to support both 3.0 and 4.0 versions of the `circulation` interface
* Changed the package to support both 4.0 and 5.0 versions of the `loan-storage` interface (as the only module which provides `circulation` 4.0 requires `loan-storage` 5.0 as this is a cascading change. They need to be in unison to form a coherent backend)
* ~~Extended the interface check in the view to first look for `circulation` version 3.0 and then 4.0~~
* Changed the interface check in the view to for any version of `circulation` interface (to be …
=> Support circulation interface 3.0 and 4.0 UIU-627

src/UserForm.css, src/UserForm.js, src/components/EditSections/EditContactInfo/EditContactInfo.js, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, src/components/EditSections/EditProxy/EditProxy.js, src/components/EditSections/EditServicePoints/EditServicePoints.js, src/components/EditSections/EditUserInfo/EditUserInfo.js, src/components/EditablePermissions/EditablePermissions.js
The user edit form doesn't do the flexing it needs to for different screen widths.
Set a max-width of `50em` for the entire form. Adjust `react-flexbox-grid` usage as necessary.
1. Don't use `react-flexbox-grid` to set a faux max-width. Set the max-width on the container, so the `<Row>` fills the container.
2. Don't use `react-flexbox-grid` when you don't need to.
```
<Row>
<Col xs={12}>
Content
</Col>
</Row>
```
does exactly the same thing as 
```
<div>
Content
</div>
```
- `react-flexbox-grid` is effective when you can guarantee the parent container is 100% of the width of the browser. Some day we might want this form to be renderable in the third pane of a `SearchAndSort`-esque layout. Then we'll want to write a little more custom CSS in this repo instead of using `react-flexbox-grid`. …
=> Clean up user edit form layout

CHANGELOG.md, package.json
* Depend on `@folio/stripes`. (Part of FOLIO-1547)
* Update imports for components moved from `stripes-components` to `stripes-smart-components`. (Part of FOLIO-1547)
=> Release v2.17.0

src/ViewUser.js, src/components/ViewSections/ExtendedInfo/ExtendedInfo.js
The date utility functions on the `stripes` god object are barreling toward a deprecation, since they simply duplicate functionality already provided by `react-intl`. This was the only instance of a `folio-org` repo consuming `stripes.formatAbsoluteDate()`. 
`<FormattedDate value={date} timeZone="UTC" />` provided by `react-intl` accomplishes the same thing.
While I was in `ExtendedInfo`, I adjusted the `react-flexbox-grid` usage, improved the `lodash` import, stopped passing in the `stripes` god object as a prop, and used `<FormattedMessage>` over `stripes.intl.formatMessage()`.
=> STCOR-267 Use react-intl formatDate with timeZone option

src/UserForm.js, src/ViewUser.js
Adds `xx-large` `<h2>` to user detail pane and form.
https://issues.folio.org/browse/STCOM-352
=> STCOM-352 Display large headline on detail record

CHANGELOG.md, package.json
Create a grantable permission that allows users to renew loans by
user-id and loan-id, and that also includes basic permissions to view
users.
Fixes [UIU-625](https://issues.folio.org/browse/UIU-625)
=> create renew-by-id permission

CHANGELOG.md, src/components/EditSections/EditContactInfo/EditContactInfo.js, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, src/components/EditSections/EditProxy/EditProxy.js, src/components/EditSections/EditServicePoints/EditServicePoints.js, src/components/EditSections/EditUserInfo/EditUserInfo.js, src/components/EditablePermissions/EditablePermissions.js, src/components/RenderPermissions/RenderPermissions.js, src/components/ViewSections/ContactInfo/ContactInfo.js, src/components/ViewSections/ExtendedInfo/ExtendedInfo.js, src/components/ViewSections/ProxyPermissions/ProxyPermissions.js, src/components/ViewSections/UserAccounts/UserAccounts.js, src/components/ViewSections/UserInfo/UserInfo.js, src/components/ViewSections/UserLoans/UserLoans.js, src/components/ViewSections/UserServicePoints/UserServicePoints.js, src/settings/permissions/PermissionSetDetails.js, src/settings/permissions/PermissionSetForm.js
Adjusts accordion headline sizes for correct a11y and visual hierarchy.
_includes change from https://github.com/folio-org/ui-users/pull/529_
=> Adjust headline sizes

CHANGELOG.md, src/settings/PatronGroupsSettings.js
The default sort field in `<ControlledVocab>` is `name`, but patron
groups don't have a `name` field, so we specify the field they do have
instead.
Refs [STSMACOM-139](https://issues.folio.org/browse/STSMACOM-139)
=> specify sort for patron groups

CHANGELOG.md, src/settings/AddressTypesSettings.js, src/settings/OwnerSettings.js, src/settings/PaymentSettings.js, src/settings/RefundReasonsSettings.js, src/settings/WaiveSettings.js
The default sort field in `<ControlledVocab>` is name, but many
entries don't have a `name` field, so we specify the field they do have
instead.
Refs [STSMACOM-139](https://issues.folio.org/browse/STSMACOM-139)
=> specify sortby for entries without `name`

src/settings/ProfilePictureSettings.js
`<Checkbox>` needs the `type="checkbox"` typehint to kick it into
boolean mode and treat `value` correctly. I think.
=> provide necessary typehint to Checkbox

CHANGELOG.md, src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/OpenLoans/OpenLoans.js
Provide the `totalCount` prop to `<MultiColumnList>` so we can hang
tests off whether the table is populated.
=> provide totalCount to MCL

CHANGELOG.md, src/components/ProxyGroup/ProxyEditList/ProxyEditList.js
`active` is the attribute on the user-object, but the formatter for this
field is named `status` because, um, I don't remember why but that's what
it's called now. So the `<Pluggable>` needs to ask for `status` rather
than `active` for that data to be correctly formatted in the modal.
Fixes [UIU-726](https://issues.folio.org/browse/UIU-726)
=> use the "status" formatter for the "active" attr

src/components/ProxyGroup/ProxyViewList/ProxyViewList.js, src/components/RenderPermissions/RenderPermissions.js
Allow `PropTypes.node` instead of the more restrictive
`PropTypes.string` for labels that may be passed as `<FormattedMessage>`
objects.
=> allow PropTypes.node for easier i18n

src/components/EditSections/EditUserInfo/EditUserInfo.js
Patron group names are runtime configuration values, not hard-coded
strings, hence they should not be translated. Translation was
inadvertently added in #574 as part of the general refactoring to use
better `react-intl` patterns. This reverts the patron group translation
portion of that work.
Refs [UIU-679](https://issues.folio.org/browse/UIU-679)
=> do not translate patron group names

src/components/ProxyGroup/ProxyEditItem/ProxyEditItem.js
When a proxy or sponsor is newly-added, the `proxy.metadata.createdDate`
field is empty. Sending `null` to `<FormattedTime>` results in a display
corresponding to the start of the unix epoch, midnight on 1970-01-01
whereas `stripes.formatDateTime` returned an empty string. This change uses
`<FormattedTime>` but correctly checks the value of the field before
displaying it, fixing the bug introduced in #574.
Refs [UIU-679](https://issues.folio.org/browse/UIU-679)
=> correctly display proxy/sponsor relationship date

CHANGELOG.md, src/UserForm.js
The work on shortcuts created a regression:
https://issues.folio.org/browse/UIU-743
This PR brings back the handleSubmit from redux-form while submitting the form via regular submit button.
=> Bring back handleSubmit when using submit button. Fixes UIU-743

src/UserForm.js, src/ViewUser.js, src/components/EditSections/EditProxy/EditProxy.js, src/components/EditablePermissions/EditablePermissions.js, src/settings/permissions/PermissionSetForm.js
Some attributes really need to be strings, not `<FormattedMessage>`s. Most of the time you can use a render prop to `<FormattedMessage>` to accomplish that, but not always, e.g. a `<DropdownMenu>` won't render correctly when coded that way so we have to fall back to `injectIntl` and `props.intl.formatMessage()`.
=> let strings be strings

src/components/ProxyGroup/ProxyEditItem/ProxyEditItem.js
The label for an `<option>` must be a string so we need to use
`formatMessage()` instead of `<FormattedMessage>`. This reverts that
portion of the work in #574.
Additionally, it sets the values for the `<option>`s in the
proxy-related fields to hard-coded strings consistent with the immutable
values on the backend.
Fixes [UIU-736](https://issues.folio.org/browse/UIU-736)
=> don't use FormattedMessage for options

package.json, src/LoanActionsHistory.js, src/components/Loans/OpenLoans/OpenLoans.js
Couple notes about this:
1. Currently if the user doesn't have the request related permissions the requests counter will just show `0`.
2. I couldn't use `permissionsRequired` inside the manifest because we are using `accumulate` type queries and there is currently no support for `permissionsRequired` for these type of queries in `stripes-connect`
3. It looks like both `LoanActionsHistory` and `OpenLoans` have some code duplication. It would be nice to refactor it at some point.
Given all these I would still like to move forward with this PR so we can finalize work on https://issues.folio.org/browse/UIU-686
=> 'Loan: All permissions' should not include request-related permissions. Part of UIU-741.

src/ViewUser.js
It looks like what was happening here is that after we hit 'X' on the edit form (after some changes were made) the `layer` in the redux store would be cleaned up by `SearchAndSort`:
https://github.com/folio-org/stripes-smart-components/blob/master/lib/SearchAndSort/SearchAndSort.js#L315
This would trigger a re-render of the `ViewUser` component without a `layer` present:
https://github.com/folio-org/ui-users/blob/master/src/ViewUser.js#L545
which would cause the `UserForm` to be destroyed completely (together with the `StripesFormWrapper` where the 'Close without saving' modal is implemented).
Switching to building a query from the current location solves this issue. This is similar to what `SearchAndSort` already does in a 'create' mode: …
=> Show 'Close without saving' dialog after changes are made on the user form. Fixes UIU-749.

src/LoanActionsHistory.js, src/components/Loans/OpenLoans/OpenLoans.js
This PR hides request count on the open loan view and loan details view in cases when `ui-users.requests.all` permission is not present.
=> Hide request count when request related permissions are not present. Part of UIU-741

CHANGELOG.md, src/AccountActionsHistory.js, src/AccountsHistory.css, src/AccountsHistory.js, src/Users.js, src/ViewUser.js, src/index.js, src/settings/CommentRequiredForm.js, src/settings/FeeFinesTable/FeeFines.js, src/settings/FeeFinesTable/Owners.js, src/settings/OwnerSettings.js, src/settings/index.js, src/settings/permissions/PermissionSetDetails.js, src/settings/permissions/PermissionSetForm.js, src/settings/permissions/PermissionSets.js, src/util.js, src/withRenew.js, translations/ui-users/en.json
According to [UIU-691](https://issues.folio.org/browse/UIU-691) all the hardcoded strings should be internationalized using the react-intl pattern.
react-intl constructs outlined at [here](https://github.com/folio-org/stripes-core/blob/master/doc/i18n.md) 
Use` <FormattedMessage>`, `<FormattedDate>`, and `<FormattedTime>` as often as possible, only falling back to formatMessage(), formatDate(), and formatTime() (accompanied by injectIntl) when a bare string is absolutely necessary.
This PR resolve [UIU-640](https://issues.folio.org/browse/UIU-640)
=> UIU-691: Apply internationalization to all hardcoded strings for Settings

CHANGELOG.md, package.json, src/settings/OwnerSettings.js
Provide `renderToOverlay` to `<MultiSelection>` to avoid clipping the
service points menu.
Fixes [STSMACOM-149](https://issues.folio.org/browse/STSMACOM-149)
=> avoid clipping service point menu

CHANGELOG.md, src/components/Loans/OpenLoans/OpenLoans.js
The request-queue link from the ellipses menu of the open-loans pane
should include filters to show only open loans.
Fixes [UIU-716](https://issues.folio.org/browse/UIU-716)
=> link to open requests

test/ui-testing/new_user.js
`nightmare.evaluate()` returns a promise so you have to call `then`
after it; otherwise, the test will continue in an alternate context
parallel to the one the promise is executing in, and then the promise
will return, and then nightmare will be all kinds of confused, and new
tests might continue in the middle of other and nightmare won't exit
correctly and it'll set there going on and on and you'll think "WHAT IS
HAPPENING? WHY WON'T THIS STOP??!?!" but it won't stop, and, well, you
get the idea.
=> call then() after evaluate()

test/ui-testing/new_permission_set.js, test/ui-testing/new_service_point.js, test/ui-testing/new_user.js, test/ui-testing/patron_group.js
Using the passed-in instance of Nightmare leads to weird, weird results
where tests seem to run interleaved with one another and things
generally fall apart in strange, unpredictable ways that ultimately
result in tests that fail when run as part of a suite but succeed when
run individually.
It's like the instance of Nightmare gets tired and just can't keep
itself together. Sadly, this means we can't use Nightmare to collect
coverage data since it's using that single instance that allows us to
generate that data. Alas.
Fixes [UIU-777](https://issues.folio.org/browse/UIU-777), Refs [FOLIO-1660](https://issues.folio.org/browse/FOLIO-1660)
=> instantiate new Nightmare instance for tests

src/UserForm.js, src/ViewUser.js, test/bigtest/interactors/user-form-page.js, test/bigtest/interactors/user-view-page.js, test/bigtest/network/factories/user-personal.js, test/bigtest/network/factories/user.js, test/bigtest/tests/user-create-page-test.js, test/bigtest/tests/user-edit-page-test.js, test/bigtest/tests/user-view-page-test.js, test/bigtest/tests/users-show-all-test.js, translations/ui-users/en.json
According to [UIU-754](https://issues.folio.org/browse/UIU-754), should be possible to cancel / edit user details using pane header dropdown. 
- Actions in 'Create User': Cancel
- Actions in 'Show User': Edit
- Actions in 'Edit User': Cancel
- Add actionMenu attribute to `<Pane>` with necessary action.
- Cover actions with tests.
=> UIU-754: Users App: Implement Pane header dropdown on Detail Records

src/components/ViewSections/PatronBlock/PatronBlock.js, translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en.json, translations/ui-users/es.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/hu.json, translations/ui-users/it_IT.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json
https://issues.folio.org/browse/STCOM-391
Related to https://github.com/folio-org/stripes-components/pull/775
Instead of having the "+" directly in the translation file, we'll now do:
```
<Icon icon="plus-sign">
<FormattedMessage id="ui-module.translationId" />
</Icon>
```
=> STCOM-391 Remove plus sign from translation strings

CHANGELOG.md, package.json
New features were added in users-bl that necessitated bumping its
interface, but without support for the new interface in the UI, we
couldn't build folio-snapshot. Providing parallel support for the old
interface (since no functionality here is changing) and the new
interface (so that backend dependencies can be satisfied) seems like the
least painful solution.
Refs [FOLIO-1735](https://issues.folio.org/browse/FOLIO-1735), [MODLOGIN-103](https://issues.folio.org/browse/MODLOGIN-103), [MODUSERBL-62](https://issues.folio.org/browse/MODUSERBL-62)
=> support updated okapi interfaces

src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/OpenLoans/components/OpenLoansSubHeader/OpenLoansSubHeader.js, src/components/PatronBlock/PatronBlockForm.js, src/components/PatronGroupNumberOfUsers/PatronGroupNumberOfUsers.js, src/settings/permissions/PermissionSetForm.js, translations/ui-users/en.json
title has been replaced by ariaLabel when necessary, but most of the
time it's not even necessary, e.g. when a button has a child element
that contains the text.
Refs [STCOM-296](https://issues.folio.org/browse/STCOM-296)
=> don't use title attributes

.gitignore, src/Users.js, src/ViewUser.js, src/components/PatronBlock/PatronBlockForm.js, test/bigtest/interactors/users.js, test/bigtest/network/config.js
This PR fixes a bug where unsaved changes modal is not shown after a record is being changed and closed.
Here are couple more details about what is going on:
1. We click on an edit link and the query resource is updated with the `{ layer: edit }` which eventually propagates to `history.push` https://github.com/folio-org/stripes-core/blob/master/src/locationService.js#L74
2. The form is now visible. The stripes-form registers a block: https://github.com/folio-org/stripes-form/blob/master/lib/StripesFormWrapper.js#L25 
3. We make a change on the form and hit close. 
4. The query resource is updated to `{ layer: null }`. This triggers re-render of the `ViewUser`. Since the previous implementation relies on the state of the query resource the `ViewUser` will hide the user form: …
=> Rely on url changes instead of query resource. Fixes UIU-878

CHANGELOG.md, src/UserForm.js, src/Users.js, src/ViewUser.js, src/components/PatronBlock/PatronBlockForm.js
`<Pane>` eventually causes its `appIcon` prop to create a new
`<AppIcon>` by importing from `@folio/stripes/components`, which has
been deprecated. So, instead of allowing that to happen, these changes
instantiate their own `<AppIcon>` instances from `@folio/stripes/core`
and push it through the `paneTitle` prop.
Look, ma! No more console warnings!
=> don't pass appIcon to Pane

test/bigtest/interactors/users.js, test/bigtest/tests/users-show-all-test.js
It looks like selecting filter by entering a specific URL doesn't work. The test has been changed and the inactive users filter checkbox is clicked manually now.
=> Fix failing users test

CHANGELOG.md, src/components/ProxyGroup/ProxyEditList/ProxyEditList.js
The edit-user page contains two instances of the find-user plugin. Each
needs a unique ID. This prevents us from generating invalid HTML and
also helps with tests which may want to distinguish adding a proxy from
adding a sponsor.
Refs [UIU-884](https://issues.folio.org/browse/UIU-884)
=> provide unique ID to find-user plugin

src/UserForm.js, src/ViewUser.js, src/components/PatronBlock/PatronBlockForm.js, translations/ui-users/en.json
In this PR I updated the AppIcon implementation in Pane's to use the dedicated `appIcon`-prop instead of rendering AppIcon's inside the PaneTitle.
This gives us better central control of the PaneHeader layout and ensures that RTL and text ellipsis are working as intended.
=> Pass <AppIcon> to <Pane>

CHANGELOG.md, src/Users.js
This PR uses `packageInfo` passed as a prop instead of the one found in `ui-users` package.json. This is required in order to detect if we are dealing with the `app` or `plugin` module in `SearchAndSort` which will help with fixing https://issues.folio.org/browse/ERM-72.
=> Use packageInfo passed via props if present. Refs ERM-72

CHANGELOG.md, src/LoanActionsHistory.js, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/ViewSections/UserRequests/UserRequests.js
Outbound links to the requests app now include the filter "Open - In
transit" in addition to other "open request" fiters".
Additionally, outbound links to the requests app exactly match the case
of the filters, causing the filter-checkboxes to properly appear in the
checked or unchecked state.
Additionally, queries for open or closed requests within this app to
use a substring match for "open" or "closed" rather than substring
matches on the full filter, e.g. "Open - In transit" which will
automatically handle additional statuses beginning with "Open" or
"Closed" in the future.
Fixes [UIU-682](https://issues.folio.org/browse/UIU-682)
=> support "Open - In transit" status

src/components/BulkOverrideDialog/BulkOverrideInfo.js, translations/ui-users/en.json
1. On bugfest.folio.ebsco.com, with a user who has permission set folio-admin
2. Using bulk renewal, renew an open loan that cannot be renewed (e.g., loan policy says it is not renewable)
3. Click override
**Expected**: Additional information displays with one asterisk. The Override button is the primary button and is placed rightmost and styled accordingly, once fields are filled out.
**Actual**: Additional information displays with two asterisks. The Cancel button is placed rightmost and is styled as the primary button.
=> UIU-906: Change buttons, delete asterisk.

src/Users.js
Emtpy list of values on filterConfig for patron-groups claimed that
the list would be filled in by componentWillUpdate. In fact,
componentDidUpdate is responsible for this, and the comment now
reflects that.
=> Fix outdated comment

CHANGELOG.md, src/ViewUser.js
Suppress the error alert when a user's permissions record is missing.
Fixes [UIU-507](https://issues.folio.org/browse/UIU-507)
=> don't choke when permissions record is missing

src/components/EditSections/EditUserInfo/EditUserInfo.js
Steps:
Log into FOLIO
Go to Users
Edit a user record
**Expected**: Required fields should have one indicator that they are required
**Actual**: Last name has two indicators (a black and a red asterisk). Not sure which is correct
=> UIU-914: Delete double asterisk.

src/components/ProxyGroup/ProxyEditItem/ProxyEditItem.js
* Check that a value is non-empty before formatting it.
* Provide the `key` attribute React is so keen about
=> cleanup some console warnings

CHANGELOG.md, src/withProxy.js
Remove the extra `query=` clause from the proxy-users query.
Fixes [UIU-952](https://issues.folio.org/browse/UIU-952)
=> correct proxy query

CHANGELOG.md, src/components/BulkOverrideDialog/BulkOverrideLoansList.js, src/components/BulkRenewalDialog/BulkRenewedLoansList.js, src/withRenew.js
The bug report here was that when a renewal was denied to the item
having an open recall-request against it, the explanation was missing
from the alert box.
This occurred because the error handler in `withRenew` inadvertently
returned a `<FormattedMessage>` with nested props when the error
contained a policy-name, which it does when the loan-policy is the
reason for the denial. When the error is the result of an open recall,
no policy-name is present, hence no nested props.
This fix cleans up the error handling in `withRenew` so the return value
is consistently structured for an error of any type, and it updates the
explanation display accordingly.
This bug was introduced in #600 during internationalization when
the code changed from something like
```
message = `could not renew because …
```
=> always show explantion for renewal failure

CHANGELOG.md, src/components/PatronBlock/PatronBlockLayer.js
Strict matching is way more efficient.
Fixes [UIU-956](https://issues.folio.org/browse/UIU-956)
=> use strict matching for patron-id query

src/withProxy.js
Remove the extra `query=` clause from the `proxiesfor` query.
This was partially addressed in #786. It's now completely addressed.
Added correct quoting of the query value as a bonus.
Refs [UIU-952](https://issues.folio.org/browse/UIU-952)
=> REALLY correct proxiesfor query

package.json, test/ui-testing/new-permission-set.js, test/ui-testing/new-user.js, test/ui-testing/patron-group.js
Apps are guaranteed to show up in the app-menu but not on the navigation
bar, so tests need to navigate by clicking menu items.
Refs [UITEST-65](https://issues.folio.org/browse/UITEST-65)
=> navigate via the app-menu instead of icons

CHANGELOG.md, src/withServicePoints.js
There was no limit clause previously, which meant we only got 10, which
was never enough.
Fixes [UIU-1053](https://issues.folio.org/browse/UIU-1053)
=> retrieve 1000 service points by default

src/reports/OverdueLoanReport.js, translations/ui-users/en.json
=> UIU-984: Add borrower fields to overdue loans report

package.json, src/index.js
We had changed the naming conventions for permission sets related to
settings pages but did get those changes in place in the code.
=> replace legacy permission set

CHANGELOG.md, src/reports/OverdueLoanReport.js, test/bigtest/interactors/user-form-page.js, translations/ui-users/en.json
Add "Loan policy name" and "Loan ID" fields to overdue loans report in the scope of the [story](https://issues.folio.org/browse/UIU-985)
=> UIU-985: Add loan policy name and loan id to overdue loans report

CHANGELOG.md, src/Users.js
This PR adds ability to search by both first and last name. This is a temporary fix until https://issues.folio.org/browse/RMB-385 is done on the server.
=> Add ability to search by first and last name. Part of UIU-1068.

src/Users.js
Unfortunately this is a breaking change because we rely on a change in `stripes-smart-components` which hasn't been released yet. We need to wait for it first before we can move forward with this. This is currently breaking UNAMs setup
=> Rollback search change in UIU-1068

test/bigtest/tests/user-edit-page-test.js
I spotted a lonely `.only` in the wild.
=> Removed .only from 'user-page-edit-test'

src/components/Loans/OpenLoans/components/Modals/Modals.js
I noticed that when the `ChangeDueDateDialog` is reopened second time the loans were not being refetched (and were gone from the screen). This PR together with https://github.com/folio-org/stripes-smart-components/pull/549 should fix some of the issues found in: https://issues.folio.org/browse/UIU-1065
=> Refetch loans when the ChangeDueDateDialog is reopened. Part of UIU-1065

src/components/BulkOverrideDialog/BulkOverrideDialog.js, src/components/BulkOverrideDialog/BulkOverrideInfo.js, src/components/BulkRenewalDialog/BulkRenewInfo.js, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/Loans/OpenLoans/helpers/isOverridePossible/isOverridePossible.js, src/components/Loans/OpenLoans/helpers/isOverridePossible/overridePossibleMessages.js, test/bigtest/interactors/open-loans.js, test/bigtest/network/scenarios/request-related-failure-multiple-errors.js, test/bigtest/network/scenarios/request-related-failure.js, test/bigtest/tests/open-loan-override-test.js
As a staff member, I want to override renewals that have failed because of pending requests, because I want to provide better customer service on a case-by-case basis.
- Given an attempted renewal
- When the renewal only fails because the item has an open recall on it
- Then give the user the ability to override
- Given a renewal that has failed for only the reasons in scenarios given above
- When the user overrides the renewal
- Then display the renewal override window
=> UIU-1017: Add override possible message. Add tests.

CHANGELOG.md, src/Users.js, translations/ui-users/en.json
Refers to the hardcode [issue](https://issues.folio.org/browse/UIU-894) for the active/inactive entries for the search filter in the *ui-users* application.
=> UIU-894: Handle "Active/Inactive" hard-code issue for the search filter

CHANGELOG.md, src/Users.js
Trim whitespace and tokenize on whitespace instead of single space in
order to avoid constructing search strings like `*` that would match
every single row in the DB.
Fixes [UIU-1086](https://issues.folio.org/browse/UIU-1086)
=> UIU-1086 be more careful about query construction

src/components/EditSections/EditUserInfo/EditUserInfo.css, src/components/EditSections/EditUserInfo/EditUserInfo.js
To fix incorrect displaying of patron group control.
https://issues.folio.org/browse/UIU-916
=> UIU-916 - Patron Group Menu Caret Obscures Content

src/components/Loans/OpenLoans/helpers/isOverridePossible/overridePossibleMessages.js
Allow the user to select a date using the date picker when the loan with rolling loan policy, renew from: due date, and a fixed due date schedule (due date limit), and a due date not falling within the range(s) in the fixed due date schedule
=> UIU-1100: Change showDueDatePicker flag.

src/components/EditablePermissions/EditablePermissions.js, src/components/PermissionList/PermissionList.js, test/ui-testing/new-permission-set.js
This test relied on `xclick`, which was removed from stripes-testing in
`v1.6.0`, which means that should've been tagged `v2.0.0`, but here we
are. `xclick` has been a known bad actor for ages now and should have
been removed from this test long ago.
In support of removing `xclick`, `data-` attributes were added to both
permission-add buttons and the permissions-in-this-set list in order to
provide unique selectors, and the non-unique `id` attribute that was
used for _every_ permission's delete button was made to be unique,
because, well, that's how `id` attributes are supposed to work.
=> fix new-permission-set test

src/settings/permissions/PermissionSetForm.js
The field's `required` attribute automatically provides the asterisk;
there is no need to manually include it.
=> remove double asterisk

CHANGELOG.md, src/LoanActionsHistory.js, test/bigtest/network/config.js
The shape of the response to queries against `loan-storage/loan-history`
has changed. Queries used to look like this:
```
GET loan-storage/loan-history?query=id=$LOAN_ID
{
"loans" : [ {
"id" : "$LOAN_ID",
...
} ],
"totalRecords" : 1
}
```
Then now look like this:
```
GET loan-storage/loan-history?query=loan.id=$LOAN_ID
{
"loansHistory": [ {
"id": "f1f72ec5-2e59-4607-8d24-52de0f8e56f9",
"operation": "I",
"loan": {
"id": "$LOAN_ID",
...
}
} ],
"totalRecords" : 1
}
```
Note the changes to both the query and the extra level of nesting of the
`loan` element in the response.
Refs [UIU-1092](https://issues.folio.org/browse/UIU-1092)
=> UIU-1092 use new loan-history shape

package.json
It was noticed that folio-snapshot build continue to use the old version of `mod-circulation-storage-8.2.0-SNAPSHOT.176` from Jun 10?. The latest mod-circulation-storage has bumped up the `loan-storage` interface to 6.0.
=> Update loan-storage dependency to pull new mod-circulation-storage

package.json
Access to users settings was inadvertently removed in #870. We don't
need `settings.users.enabled` to be a visible permission, but we do
need it to be present so that stripes-core will discover that this
module has settings.
Refs [UIU-1125](https://issues.folio.org/browse/UIU-1125)
=> UIU-1125 restore settings

package.json
[Changes](https://github.com/folio-org/mod-login/pull/64) in the version of the mod-login affect changes in the modules: 
-  'edge-oai-pmh',
-  'edge-orders',
-  'edge-patron',
-  'edge-rtac',
-  'ui-users',
-  'mod-users-bl'
-  'edge-sip2'
-  'mod-login'
=> Raising the interface version related to mod-login API breaking change

CHANGELOG.md, src/components/EditSections/EditUserPerms/EditUserPerms.js, src/settings/permissions/ContainedPermissions.js, src/settings/permissions/PermissionSets.js
Retrieve more permissions. 1k wasn't enough; hopefully 10k is. If not,
640k ought to be enough for everybody said nobody, ever. 
Fixes [UIU-1134](https://issues.folio.org/browse/UIU-1134)
=> UIU-1134 retrieve 10k permissions

CHANGELOG.md, package.json, src/UserForm.js, test/bigtest/interactors/user-form-page.js, test/bigtest/tests/user-create-page-test.js, test/bigtest/tests/user-edit-page-test.js
Implement footer with _Save & close_ and _Canclel_ buttons on the edit user form according to [story](https://issues.folio.org/browse/STCOM-429).
=> STCOM-429: Fixed footer for Save and Cancel buttons

src/UserForm.js
Reverts folio-org/ui-users#928
@zburke, @SergiyVSergiyenko, I was not right. We had this in requirements. 
> Save would only be clickable if the form is dirty, valid, and not submitting.
=> Revert "STCOM-429: Prevent disabling user form submit button when form is `inva…"

src/UserForm.js
The element ID for the save button was inadvertently removed in #925. Now
it's back!
Refs [STCOM-429](https://issues.folio.org/browse/STCOM-429)
=> STCOM-429 restore element IDs

CHANGELOG.md, src/UserForm.js, test/bigtest/tests/user-create-page-test.js
Update footer with _Save & close_ and _Cancel_ buttons on the edit user form.
Support arbitrary rendering of the content on two sides according the [story](https://issues.folio.org/browse/STCOM-571).
**Screenshots**
=> STCOM-571: Make PaneFooter flexible enough

package.json
PR #950 included changes to the add/edit user form's footer that relied
on a change to stripes-components that was not present in stripes
v2.10.0. That change was added in a patch release, v2.10.1, so this PR
updates the minimum stripes version to v2.10.1.
Yarn will do The Right Thing with the `~` dependencies here and pull in
that patch release automatically, but if any platform build processes
remove that `~` and use straight version, then this will protect them
and cause the correct version to be pulled in.
Refs [STCOM-571](https://issues.folio.org/browse/STCOM-571)
=> STCOM-571 include latest stripes-components

CHANGELOG.md, src/withRenew.js
Dedupe the list of loan policies before retrieving it. Previously, a
long list of loans, even if they all shared the same policy, would
generate a long query with one entry per loan. The query now contains
one entry per unique policy.
Refs [CHAL-30](https://issues.folio.org/browse/CHAL-30)
=> CHAL-30 dedupe loan policy list before retrieval

CHANGELOG.md, src/withRenew.js
Tweak the query that retrieves open requests related to a patron's loans
to be slightly more efficient. This is not a huge improvement, though
it's a little bit that can add up over many loans. The real problem is
that the requests API does not allow for the retrieval of requests keyed
by the borrower's ID, only the item ID, so the only way to find requests
for a patron's loans is to pass in the item ID for every loan.
Refs [CHAL-30](https://issues.folio.org/browse/CHAL-30)
=> CHAL-30 more efficient request retrieval

src/components/PermissionsAccordion/PermissionsAccordion.js, src/components/PermissionsAccordion/components/PermissionsModal/PermissionsModal.js, src/settings/permissions/PermissionSetForm.js
To allow to exclude custom permissions sets from the list of permissions
https://issues.folio.org/browse/UIU-1223
=> UIU-1223 - Do not display user generated permission sets in list

package.json
Reverts folio-org/ui-users#969
Reverting only so we can tag a patch release at tip-of-master; this is the only feature-commit since `v2.25.2` was released and reverting (and then reapplying) a single PR will be easier than cherry-picking everything since this PR onto a release branch. Yes, yes, we may want to investigate a different branching strategy like GitFlow in the long term to mitigate this process. Today, I just need to publish a release.
=> Revert "UIU-1243: Update the circulation API to support changes in the rule editor"

CHANGELOG.md, src/components/Loans/ClosedLoans/ClosedLoans.js, test/bigtest/interactors/closed-loans.js, test/bigtest/tests/closed-loans-test.js, translations/ui-users/en.json
Prevent manual anonymization of closed loans with fees/fines in the scope of the [UIU-1083](https://issues.folio.org/browse/UIU-1083).
=> UIU-1083: Prevent manual anonymization of closed loans with fees/fines

CHANGELOG.md, src/components/AddServicePointModal/AddServicePointModal.js, src/components/EditSections/EditExtendedInfo/CreateResetPasswordControl/CreateResetPasswordControl.js, src/components/EditSections/EditServicePoints/EditServicePoints.js, src/components/Wrappers/withServicePoints.js, src/routes/UserRecordContainer.js, src/views/UserDetail/UserDetail.js, src/views/UserEdit/UserEdit.js, src/views/UserEdit/UserForm.js
Save button is not enabling when editing a newly created user, despite changes in values.
It turns out that `props.resources.servicePoints.records` and `getServicePoints()` are two very different things...
I passed those to UserForm in the proper places, and renamed `getServicePoints()` to `getUserSevicePoints` so that it's slightly clearer.
Additionally, I cleaned up a couple of console gripes for invalid prop types and resolved an error attempting to `trim()` an undefined value.
=> UIU-1314 - Problems editing a newly created user.

src/index.js, src/views/UserSearch/UserSearch.js
Restore the former search-input DOM id. It's simpler than changing all
the integration tests.
Refs [UIU-897](https://issues.folio.org/browse/UIU-897) / PR #839.
=> UIU-897 restore former form element id

test/ui-testing/patron-group.js
It seems the search form may re-render in the middle of collecting input
from Nightmare, which sucks. Waiting for the "no results" message seems
like a good element to wait for that satisfies "all done rendering".
Refs [UIU-897](https://issues.folio.org/browse/UIU-897)
=> UIU-897 test cleanup

src/routes/UserSearchContainer.js
Restore splitting of the search string on whitespace. This was
originally implemented in UIU-1068/#863/#876 and inadvertently removed
in #839.
Refs [UIU-1068](https://issues.folio.org/browse/UIU-1068)
=> UIU-1068 restore tokenization of search string

src/components/ErrorModal/ErrorModal.js
Don't use deprecated props. They're, ya know, deprecated. Ooooh, pretty
clean console!
=> ErrorModal should not use deprecated props

src/components/Accounts/Actions/ActionModal.js, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/util/navigationHandlers.js, src/routes/ChargeFeesFinesContainer.js
See [UIU-1320](https://issues.folio.org/browse/UIU-1320)
Logic for fetching loans/choosing the selected loan was checking the URL for a loan id in 2 different ways: the query string AND dynamic params picked up via react-router. I opted for the params route and removed the extra query string logic.
The charge fee/fine form should now have what it needs to apply the fine to the loan correctly.
The amounts in the Loans listing/detail will be updated, no refresh/navigation necessary.
=> UIU-1320 Updating fee/fine column/display after charge

test/ui-testing/new-user.js
There's a bit of reorganization of the form-fields for clarity here, so
the order they appear in the test is more consistent with the order
they appear on-screen, and there's the new, required preferred-contact
field.
But the interesting thing here is that this test failed _not_ because it
was missing the required preferred-contact field but because the click
sent to the dummy-search:
```
-          .type('#input-user-search', '0')
-          .wait('button[type=submit]')
-          .click('button[type=submit]')
```
somehow caused future interaction with the user-form to immediately
close the form and cause nightmare to get lost in neverneverland on the
user-list page.
This makes _no sense whatsoever_.
The user-search form is entirely separate from the new-user form, and
even if a click on …
=> appease Nightmare's mysterious desires

src/components/EditSections/EditUserInfo/EditUserInfo.js, src/views/UserEdit/UserEdit.js, src/views/UserEdit/UserForm.js
It's not really fair to pin this on UIU-897 since many of these errors
were present previously. All that's going on here is some cleanup of
incorrect and/or missing and/or extraneous props.
* `EditUserInfo` needed a formatter for its boolean status value
* `UserEdit` omitted `defaultWidth`
* `UserForm` included `stripes` but that's handled by `withStripes`
I found this stuff while pursuing something else that was blowing up in
the console, and the console pollution from this stuff was just killing
me, so I fixed it.
=> UIU-897 props cleanup

src/views/UserEdit/UserEdit.js
Proxies and sponsors should be pulled from the methods in `withProxy`,
rather than directly from the resources in order to be properly massaged
for use in the form.
Refs [UIU-897](https://issues.folio.org/browse/UIU-897)
=> UIU-897 restore proxies to the edit-form

src/components/Loans/OpenLoans/components/ActionsDropdown/Popdown.js, src/components/ProxyGroup/ProxyEditList/ProxyEditList.js, src/components/ProxyGroup/ProxyViewList/ProxyViewList.js, src/components/Wrappers/withProxy.js, src/routes/ChargeFeesFinesContainer.js, src/views/UserEdit/UserForm.js, test/bigtest/interactors/user-form-page.js, test/bigtest/interactors/user-view-page.js, test/bigtest/network/factories/loan.js, test/bigtest/network/factories/proxiesfor.js, test/bigtest/network/models/proxiesfor.js, test/bigtest/network/scenarios/user-proxy-edit.js, test/bigtest/network/serializers/proxiesfor.js, test/bigtest/tests/user-proxy-edit-test.js
Proxy edit workflow wasn't really testable.
Adding a single sponsor caused multiple to show up when navigating back to the user detail page upon success.
Added facilities to test proxy edit workflow.
Ended up removing the `componentDidMount` method of `withProxy` and adjusting its `cDU` method.
It's possible that loading proxies/sponsors was okay on mount, and the save process needs to be refactored so that we only get transferred to the page without, I believe, an updated resource in tow...
Curious to see if this passes CI tests also...
=> Add proxy behavior

CHANGELOG.md, package.json, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/Loans/OpenLoans/components/OpenLoansSubHeader/OpenLoansSubHeader.js
Implement edit loan permission as part of [UIU-1177](https://issues.folio.org/browse/UIU-1177). This permission works in conjunction with permissions for viewing the loans.
=> UIU-1177: Implement edit loan permission

test/ui-testing/new-user.js
Remove some extraneous debugging code that was left in the new-users
integration test by accident.
=> clean up integration test debugging

src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, src/components/EditSections/EditExtendedInfo/RequestPreferencesEdit/RequestPreferencesEdit.css, src/components/EditSections/EditExtendedInfo/RequestPreferencesEdit/RequestPreferencesEdit.js, src/components/EditSections/EditExtendedInfo/RequestPreferencesEdit/index.js, src/components/UserDetailSections/ExtendedInfo/ExtendedInfo.js, src/components/UserDetailSections/ExtendedInfo/components/RequestPreferencesView/RequestPreferencesView.css, src/components/UserDetailSections/ExtendedInfo/components/RequestPreferencesView/RequestPreferencesView.js, src/components/UserDetailSections/ExtendedInfo/components/RequestPreferencesView/index.js, src/components/UserDetailSections/ExtendedInfo/components/index.js, src/components/UserDetailSections/index.js, src/components/data/converters/address.js, src/components/data/converters/address_type.js, src/constants.js, src/routes/UserRecordContainer.js, src/shapes.js, src/views/UserDetail/UserDetail.js, src/views/UserEdit/UserEdit.js, src/views/UserEdit/UserForm.js, translations/ui-users/en.json
`RequestPreferencesEdit` and `RequestPreferencesView` components were created to display and edit request preferences of users. `ViewUser` handles a lot of things, including displaying the edit user form, so the logic of GETting, PUTting, and POSTting the request preferences was placed in the `ViewUser` component.
Tests part is out of scope and extracted to this task https://issues.folio.org/browse/UIU-1328
=> UIU-1155: implement request preferences on view and edit pages

CHANGELOG.md, src/routes/UserSearchContainer.js
Retrieve up to max amount (2147483647 according to the [doc](https://s3.amazonaws.com/foliodocs/api/mod-circulation/p/circulation.html#circulation_loans_get)) of overdue loans instead of 10 to add information about all records to the CSV report. The value 2147483647 was selected after discussion with PO and backend devs. Fix [UIU-1297 ](https://issues.folio.org/browse/UIU-1297)
=> UIU-1297: Retrieve up to max amount of overdue loans instead of 10 for CSV report

src/components/EditSections/EditExtendedInfo/CreateResetPasswordControl/CreateResetPasswordControl.js, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, src/components/EditSections/EditExtendedInfo/RequestPreferencesEdit/RequestPreferencesEdit.css, src/components/EditSections/EditExtendedInfo/RequestPreferencesEdit/RequestPreferencesEdit.js, src/routes/UserRecordContainer.js, translations/ui-users/en.json
Improvements:
- Bold the Request preferences label
- Change the label from "Default service point" to "Default pickup service point"
- Unbold the FOLIO number label
- Unbold FOLIO password label
- Use all service points exсept of current user's
- Avoid raising of the permission errors during request preferences requests as permissions are out of scope
=> UIU-1155: Add style improvements, replace current user service points with all

CHANGELOG.md, package.json, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/Loans/OpenLoans/components/OpenLoansSubHeader/OpenLoansSubHeader.js
Implement loans renew permission as part of [UIU-1176](https://issues.folio.org/browse/UIU-1176). This permission works in conjunction with permissions for viewing the loans.
=> UIU-1176: Implement loans renew permission

CHANGELOG.md, src/routes/LoansListingContainer.js
Retrieve up to 100k of requested user loans instead of 100 to fix the [issue](https://issues.folio.org/browse/UIU-1292).
=> UIU-1292: Retrieve up to 100k of requested user loans instead of 100

src/views/UserEdit/UserForm.js
Allow to the user cancel form editing by click on the enter key when cancel button is focused.
https://issues.folio.org/browse/UIU-1252
Currently User form wrapped in HasCommand component and one of its command is used to deny handle enter click everywhere except save button. In order to save such behavior I've created list of allowed controls that can use this key in order to save or cancel form editing.
=> UIU-1252 - Edit User Record : Using Enter key should Save or Cancel changes IF in focus

CHANGELOG.md, package.json, src/components/BulkOverrideDialog/BulkOverrideInfo.js, src/components/BulkRenewalDialog/BulkRenewInfo.js, src/views/LoanDetails/LoanDetails.js
Implement loans renew through override permission as part of [UIU-1184](https://issues.folio.org/browse/UIU-1184). This permission works in conjunction with permissions for viewing the loans and loans renew.
=> UIU-1184: Implement loans renew through override permission

src/components/Accounts/Actions/WarningModal.js, src/components/Accounts/ViewFeesFines/ViewFeesFines.js, src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/OpenLoans/OpenLoans.js, src/components/UserDetailSections/PatronBlock/PatronBlock.js, src/components/util/util.js, src/constants.js, src/views/AccountDetails/AccountDetails.js
1) Move the duplicated code for sorting lists to the reusable function. The further work on this might be creating HOC so the sorting function will exist in one place only and thus calls of sort function will not be duplicated.
2) Additionally, handle Sonar "Conditionally executed blocks should be reachable" in a couple of places.
=> Remove sort logic duplications

CHANGELOG.md, package.json, src/components/Loans/OpenLoans/OpenLoans.js, src/components/Wrappers/withRenew.js, src/views/LoanDetails/LoanDetails.js
Show requests information when a user has view loans permission only. Part of [UIU-1184](https://issues.folio.org/browse/UIU-1184).
=> UIU-1184: Show requests information when user has view loans permission only

test/bigtest/tests/application-test.js, test/bigtest/tests/change-due-date-test.js, test/bigtest/tests/charge-fee-fine-test.js, test/bigtest/tests/closed-loans-test.js, test/bigtest/tests/fee-fine-history-test.js, test/bigtest/tests/loan-actions-history-test.js, test/bigtest/tests/manual-patron-blocks-test.js, test/bigtest/tests/manual-patron-loan-test.js, test/bigtest/tests/note-flow-test.js, test/bigtest/tests/open-loan-override-test.js, test/bigtest/tests/open-loans-test.js, test/bigtest/tests/overdue-loan-report-test.js, test/bigtest/tests/permissions-assign-test.js, test/bigtest/tests/permissions-modal-test.js, test/bigtest/tests/settings-comment-test.js, test/bigtest/tests/settings-manual-charges-test.js, test/bigtest/tests/settings-owners-test.js, test/bigtest/tests/settings-payments-test.js, test/bigtest/tests/settings-refunds-test.js, test/bigtest/tests/settings-transfers-test.js, test/bigtest/tests/settings-waives-test.js, test/bigtest/tests/user-create-page-test.js, test/bigtest/tests/user-edit-page-test.js, test/bigtest/tests/user-proxy-edit-test.js, test/bigtest/tests/user-transfer-test.js, test/bigtest/tests/user-view-page-test.js, test/bigtest/tests/users-show-all-test.js, test/bigtest/tests/users-status-filter-test.js
Unit tests recently fixed in `stripes-smart-components`, e.g.
/folio-org/stripes-smart-components/pull/665, were failing, it appears,
because of bad initialization practices: values were initialized outside
of `before` and `beforeAll` blocks, allowing tests to proceed before the
data they rely on was properly set up.
This PR tests whether the same issue may be behind some of the
mysterious failures here in ui-users.
Refs [FOLIO-2360](https://issues.folio.org/browse/FOLIO-23602)
=> FOLIO-2360 use before blocks

test/bigtest/tests/permissions-modal-test.js, test/bigtest/tests/settings-owners-test.js, test/bigtest/tests/settings-payments-test.js, test/bigtest/tests/user-transfer-test.js
Some unit tests are still failing for unclear reasons. These changes
continue efforts to make tests more robust. Among the changes:
* don't `await` calls to `this.visit(...)`; it doesn't return a promise
* move additional `setupApplication` calls into `before` blocks
Refs [FOLIO-2360](https://issues.folio.org/browse/FOLIO-2360)
=> FOLIO-2360 more robust test initialization

src/views/UserEdit/UserForm.js, test/bigtest/tests/note-flow-test.js, test/bigtest/tests/user-proxy-edit-test.js, translations/ui-users/en.json
The warning message displayed on the proxy-relationship-status field
when the current user record is expired was inadequate. Now, it clearly
states that the source of the warning is the current user.
Refs [UIU-820](https://issues.folio.org/browse/UIU-820)
=> UIU-820 better current-user-expired messaging

CHANGELOG.md, src/routes/ChargeFeesFinesContainer.js
Searching for items by barcode wildcard is not performant on a
production system with millions of entries. The intent here is that a
barcode will be scanned in so there is really no need for a wildcard
search anyway; this is essentially "lookup by barcode" not "search by
barcode" and the query now reflects that.
Refs [UIU-1380](https://issues.folio.org/browse/UIU-1380)
=> UIU-1380 don't search items by barcode wildcard

src/components/data/static/loanActionMap.js, translations/ui-users/en.json
The UI is not broken when I update a loan with the status "declared lost"
=> CIRC-567: Add translation for declared lost item status

CHANGELOG.md, package.json, src/components/Accounts/ViewFeesFines/ViewFeesFines.js, src/views/AccountsListing/AccountsListing.js, test/bigtest/interactors/fee-fine-history.js, test/bigtest/tests/fee-fine-history-test.js
Rename "Loans: All permissions" permission to "Users: User loans view, edit, renew (all)" in the scope of [UIU-1344](https://issues.folio.org/browse/UIU-1344).
=> UIU-1344: Rename "Loans: All permissions" permission to "Users: User loans view, edit, renew (all)"

package.json
Allow users to renew loans through override when they have "Users: User loans view, edit, renew (all)" permission in the scope of [UIU-1344](https://issues.folio.org/browse/UIU-1344).
=> UIU-1344: Allow users to renew loans through override

CHANGELOG.md, src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/OpenLoans/OpenLoans.js, src/components/Loans/OpenLoans/OpenLoansControl.js, src/components/Loans/OpenLoans/components/OpenLoansWithStaticData/OpenLoansWithStaticData.js, src/components/UserDetailSections/UserLoans/UserLoans.js, src/components/util/navigationHandlers.js, src/views/LoanDetails/LoanDetails.js, src/views/LoansListing/LoansListing.js, test/bigtest/interactors/closed-loans.js, test/bigtest/interactors/loan-actions-history.js, test/bigtest/interactors/loans-listing-pane.js, test/bigtest/interactors/open-loans.js, test/bigtest/interactors/user-view-page.js, test/bigtest/tests/closed-loans-test.js, test/bigtest/tests/loan-actions-history-test.js, test/bigtest/tests/open-loans-test.js, test/bigtest/tests/users-show-all-test.js
Fix close button handling for the next panes: loan actions history, open loans list, closed loans list. [Issue](https://issues.folio.org/browse/UIU-1377)
=> UIU-1377: Fix cancel button on loan details, open and closed loan lists pages

CHANGELOG.md, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/Loans/OpenLoans/components/ActionsDropdown/Popdown.js, test/bigtest/interactors/open-loans.js, test/bigtest/tests/open-loans-test.js
Prevent loan details opening upon click in loans action menu without selecting link in the scope of [UIU-1359](https://issues.folio.org/browse/UIU-1359).
=> UIU-1359: Prevent loan details opening upon click in loans action menu without selecting link

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/Accounts/ChargeFeeFine/ChargeForm.js, src/routes/ChargeFeesFinesContainer.js
There is a lot of questionable code in fees/fines and I think we should consider reserving some time to refactor / clean it up. 
A quick fix here was to add a `resourceShouldRefresh` to make sure the items resource gets cleaned up.
=> UIU-1410: Clear previous item data when open a new fee/fine form page.

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeForm.js, test/bigtest/tests/charge-fee-fine-test.js
https://issues.folio.org/browse/UIU-1412
This still feels wrong in some situations. I think the best would be to turn the fee/fine form into a plugin as @zburke suggested.
=> UIU-1412 Go back to user's accounts when clicking on cancel or 'x' from fee/fine form.

CHANGELOG.md, src/components/UserDetailSections/PatronBlock/PatronBlock.js, test/bigtest/tests/manual-patron-blocks-test.js
Since the `accumulate` is set to true for `patronBlocks` the accumulation was causing issues with editing and removing patron blocks reported in UIU-1430 and UIU-1431. 
This PR should address it.
https://issues.folio.org/browse/UIU-1430
https://issues.folio.org/browse/UIU-1431
=> UIU-1430 Reset patronBlocks before refetching.

src/routes/ChargeFeesFinesContainer.js
There were still some cases where `items` would get reloaded because of the stale data present in `loan` and `loanItems`. This PR should address it.
https://issues.folio.org/browse/UIU-1410
The code in `components/Accounts` is very very bad...
=> UIU-1410: Refresh loan and loan items

CHANGELOG.md, src/components/Accounts/Actions/Actions.js, src/components/Accounts/Actions/WarningModal.js
Prevent page crash when multiple fee/fine items is paying 
---
https://issues.folio.org/browse/UIU-1413
---
=> UIU-1413: Add check if object has status field to avoid page crash

src/components/Accounts/Actions/WarningModal.js, src/components/Accounts/ViewFeesFines/ViewFeesFines.js
Check-all checkboxes on Fees/Fines listings are not working!
There's a few things wrong here with Fees/Fines... I think this will need #1104 or similar to see the warning modal working properly.
Used the `rowUpdater` prop of MCL to pass in the checked status.
=> UIU-1407 and UIU-1408 - Fees Fines check-all checkboxes not working.

CHANGELOG.md, src/components/UserDetailSections/PatronBlock/PatronBlock.js, test/bigtest/tests/manual-patron-blocks-test.js
Since the accumulate is set to true for patronBlocks the accumulation was causing issues with editing and removing patron blocks reported in UIU-1430 and UIU-1431.
This PR should address it.
https://issues.folio.org/browse/UIU-1430
https://issues.folio.org/browse/UIU-1431
=> UIU-1430 UIU-1431 reset resource correctly

CHANGELOG.md, src/components/PatronBlock/PatronBlockForm.js, src/components/PatronBlock/PatronBlockLayer.js
Derive metadata from `initialValues` instead of `selectedItem`, which was factored away (but not completely, hence this bug).
=> UIU-1420 restore metadata to manual patron block

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js
Omit 'notify' field upon creating fee/fine in order to prevent backend error in the scope of [UIU-1438](https://issues.folio.org/browse/UIU-1438).
=> UIU-1438: Omit 'notify' field upon creating fee/fine

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeForm.js, src/views/AccountsListing/AccountsListing.js, test/bigtest/tests/charge-fee-fine-test.js
When closing an account listing or fee-fine form, return to the user-details pane. Previously, the close-handler used `history.goBack()`, which could cause a navigation loop in some circumstances. 
Refs [UIU-1412](https://issues.folio.org/browse/UIU-1412)
=> UIU-1412 show user details when closing modals

CHANGELOG.md, package.json, src/components/DeclareLostDialog/DeclareLostDialog.css, src/components/DeclareLostDialog/DeclareLostDialog.js, src/components/DeclareLostDialog/DeclareLostInfo.js, src/components/DeclareLostDialog/index.js, src/components/Loans/OpenLoans/OpenLoansControl.js, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/Wrappers/index.js, src/components/Wrappers/withDeclareLost.js, src/routes/LoanDetailContainer.js, src/views/LoanDetails/LoanDetails.js, test/bigtest/interactors/declare-lost-dialog.js, test/bigtest/interactors/loan-actions-history.js, test/bigtest/interactors/open-loans.js, test/bigtest/tests/declare-lost-test.js, translations/ui-users/en.json
Add ability to mark items "Declared lost" on UI. The detailed information about the supported scenarios can be found by [link](https://issues.folio.org/browse/UIU-1202).
=> UIU-1202: Add UI to mark items Declared lost

src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, test/bigtest/interactors/FindUserInstances.js, test/bigtest/interactors/loan-actions-history.js, test/bigtest/interactors/loans-listing-pane.js, test/bigtest/interactors/user-form-page.js, test/bigtest/interactors/users.js, test/bigtest/tests/user-proxy-edit-test.js, test/bigtest/tests/users-show-all-test.js, test/bigtest/tests/users-status-filter-test.js
Get rid of `modifiers` property from action dropdowns in open/closed loan lists since it now matches the defaults. Depends on the folio-org/stripes-components#1139 in stripes-components.
=> Get rid of 'modifiers' property from action dropdowns

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js
Omit `comments` and `patronInfo` fields, when fee/fine and charge is paying, to prevent backend error
https://issues.folio.org/browse/UIU-1413
=> UIU-1413: Omit useless fields, when fee/fine is paying, to prevent backend error

CHANGELOG.md, src/components/Wrappers/withRenew.js
Renew: Does not check its lifecycle
Sets the state, leaks out memory
Promise completes alone
When it resolves, component heaves, detached from the DOM
The console begins to moan
Memory, all alone without GC
It is leaking out two ways
From this component when:
It remembers loan policy and count-request too
Stop the memory leak again!
Refs [UIU-1450](https://issues.folio.org/browse/UIU-1450)
=> UIU-1450 XHRs musn't leak memory after component unmounts

src/views/UserEdit/UserEdit.js, src/views/UserEdit/UserForm.js, test/bigtest/interactors/users.js, test/bigtest/tests/user-edit-page-test.js, test/bigtest/tests/user-proxy-edit-test.js, test/bigtest/tests/users-show-all-test.js
Improve the situation with BigTest tests which are unstable recently. This is the analog of #1129 but without `React.lazy` which requires additional testing per @mkuklis and @aditya-matukumalli. They are going to test it on one route for the beginning.
- reduced the flow to get to the test (basically reducing the nested describes). For example, the need to test the edit user form. Instead of navigating to /users and then by clicking on the edit button to the edit form, -navigate straight away to edit route;
- grouped some unstable tests. For example, the tests which test for existing properties after the heavy beforeEach has done;
Additionally, the navigation was handled [here](https://github.com/folio-org/ui-users/pull/1129/commits/b4185107e43328f41852cfd2e0d7e86ee1a05906#diff-e74dacc8738 …
=> Improve tests

src/components/PermissionsAccordion/components/PermissionsModal/PermissionsModal.js, src/index.js, src/views/UserDetail/UserDetail.js, src/views/UserEdit/UserForm.js, src/views/UserSearch/UserSearch.js
We have a theory that a memory leak in a transitive dependency of
`<CommandList>` and `<HasCommand>` is behind the failing unit tests. The
problem may be that event listeners are not properly detached and
recycled.
This is a test of that. Obviously, we don't actually want to get rid of
key bindings. But we would really REALLY like to have reliable unit
tests. 
Refs [FOLIO-2097](https://issues.folio.org/browse/FOLIO-2097)
=> FOLIO-2097 avoid CommandList and HasCommand

CHANGELOG.md, src/views/UserSearch/UserSearch.js
The first column in the search results had the name `status` but the
field-name on the object is `active`. I think we have gone around and
around on how to properly display this field. In any case, the problem
here is that there is no `status` field to sort by, so of course trying
to use that does not work.
Fixes [UIU-1406](https://issues.folio.org/browse/UIU-1406)
=> UIU-1406 correctly sort "Active" column

test/ui-testing/new-permission-set.js
HTML markup changed in [#1149](https://github.com/folio-org/stripes-components/pull/1149) which inadvertently broke this test. It
would be great to have a more-semantic/less-markupy selector here, but
here we are.
Refs [FOLIO-2440](https://issues.folio.org/browse/FOLIO-2440), [UICAL-85](https://issues.folio.org/browse/UICAL-85)
=> FOLIO-2440 fix failing integration tests

test/ui-testing/new-permission-set.js
A `wait(30000)` clause useful for debugging was inadvertently committed.
Refs [FOLIO-2440](https://issues.folio.org/browse/FOLIO-2440)
=> FOLIO-2440 remove extraneous wait clause

src/routes/UserSearchContainer.js
**Ticket:** https://issues.folio.org/browse/UIU-1476
Passing down`queryGetter` to `<UserSearch>` to enable retrieving the current sort value which re-enables the sort indicator icons.
=> UIU-1476: Fixed missing sort indicators

CHANGELOG.md, src/components/Accounts/Actions/Actions.js
Send `Notify Patron` checkbox value to backend in the Confirm fee/fine cancellation modal
https://issues.folio.org/browse/UIU-1483
=> UIU-1483: Send notify patron value in the Confirm fee/fine cancellation modal

CHANGELOG.md, src/components/ClaimReturnedDialog/ClaimReturnedDialog.css, src/components/ClaimReturnedDialog/ClaimReturnedDialog.js, src/components/ClaimReturnedDialog/ClaimReturnedInfo.js, src/components/ClaimReturnedDialog/index.js, src/components/Loans/OpenLoans/OpenLoansControl.js, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/Wrappers/index.js, src/components/Wrappers/withClaimReturned.js, src/components/data/static/loanActionMap.js, src/views/LoanDetails/LoanDetails.js, test/bigtest/interactors/claim-returned-dialog.js, test/bigtest/interactors/loan-actions-history.js, test/bigtest/interactors/open-loans.js, test/bigtest/tests/claim-returned-test.js, translations/ui-users/en.json
Add the ability to mark items "Claimed returned" on UI. [Story](https://issues.folio.org/browse/UIU-1213).
**Screenshot**
=> UIU-1213: Add UI to mark items Claim returned

CHANGELOG.md, src/components/UserDetailSections/ExtendedInfo/ExtendedInfo.js, src/views/UserEdit/UserEdit.js
It turns out `user.personal` is not a required attribute but there is
some front-end code that made such an assumption.
Refs [UIU-1510](https://issues.folio.org/browse/UIU-1510)
=> UIU-1510 validate presence of user.personal

CHANGELOG.md, package.json, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/constants.js, src/views/LoanDetails/LoanDetails.js
Implement declare items lost permission as part of [UIU-1265](https://issues.folio.org/browse/UIU-1265). This permission works in conjunction with permissions for viewing the loans.
=> UIU-1265: Implement declare items lost permission

CHANGELOG.md, src/settings/CustomFieldsSettings.js
[PR 730](https://github.com/folio-org/stripes-smart-components/pull/730) in stripes-smart-components changed the API for
`ViewCustomFieldSettings`. This change accommodates that one.
Refs [UIU-1521](https://issues.folio.org/browse/UIU-1521)
=> UIU-1521 provide permissions for custom fields

CHANGELOG.md, src/settings/permissions/PermissionSetDetails.js, src/views/UserEdit/UserForm.js
Bug fix: Can not assign and unassign permissions to users unless you have "Settings (Users): Can create, edit and remove permission sets"
https://issues.folio.org/browse/UIU-1518
=> UIU-1518: Fix permissions

CHANGELOG.md, src/settings/FeeFineSettings.js
Fix form save where url depends on local resource.
https://issues.folio.org/browse/UIU-1486
=> UIU-1486 - Default charge and action notices not saved on manual fee/fine charge settings

package.json
PR #1178 changed the dev-dep on `stripes-core` from caret to tilde
without explanation. I think this was unintentional, but it had the
effect of pulling multiple copies of `stripes-core` into the build as
soon as the next minor version of `stripes-core` was published. This
happened because the looser caret dev-dep on `@folio/stripes` pulled
in the new version while the tilde dev-dep specified here held on to
the old version.
=> correctly restrict stripes-core devDep

CHANGELOG.md, package.json
`plugin-find-user` `v2.0.0` uses `@folio/stripes` `v3.0.0`.
=> update to compatible version of plugin-find-user

src/index.js, src/routes/UserSearchContainer.js, src/settings/FeeFineSettings.js, src/settings/index.js, src/settings/sections.js
Reverts folio-org/ui-users#1066
Rather than completely bailing on local routing and deferring to `@folio/stripes/smart-components/Settings`, I think we can accomplish UIU-1051 simply by defining the necessary style in `@folio/stripes/components/NavListSection`.
=> Revert "UIU-1051: Fix Settings>Users spacing before Fee/fine section"

CHANGELOG.md, src/views/UserDetail/UserDetail.js, src/views/UserEdit/UserForm.js, test/bigtest/interactors/user-form-page.js, test/bigtest/interactors/user-view-page.js, test/bigtest/network/config.js, test/bigtest/network/factories/user.js, test/bigtest/tests/settings-custom-fields-test.js, test/bigtest/tests/user-edit-page-test.js, test/bigtest/tests/user-view-page-test.js
- Add Custom Fields accordion to User Details Page
- Add Custom Fields accordion to Create/Edit User Page
- Add tests
Implementation of accordions in [`stripes-smart-components`](https://github.com/folio-org/stripes-smart-components/pull/743)
[UIU-1279](https://issues.folio.org/browse/UIU-1279)
=> UIU-1279: Apply Custom Fields page components for record

src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, src/views/UserDetail/UserDetail.js, src/views/UserEdit/UserForm.js, test/bigtest/interactors/user-form-page.js, test/bigtest/tests/user-create-page-test.js, test/bigtest/tests/user-edit-page-test.js
- On Create New user record should no longer show a password field
- Entering a username should no longer require entering a password
- If username has already been saved to the record then display the Send a create password email link
https://issues.folio.org/browse/UIU-1511
=> UIU-1511: Remove password field

src/views/UserSearch/UserSearch.js
We made a change in the `<MultiColumnList>`-component that removes the horizontal margin by default, making the component span from edge to edge.
This works for most implementations but MCL's used in the result panes must have the `hasMargin`-prop applied to enable proper spacing and alignment.
This PR adds that prop for the results view.
=> Added hasMargin-prop for MCL in users results list

CHANGELOG.md, src/components/EditSections/EditUserInfo/EditUserInfo.js, src/views/UserEdit/UserEdit.js, test/bigtest/interactors/user-form-page.js, test/bigtest/interactors/user-view-page.js, test/bigtest/network/config.js, test/bigtest/network/factories/user.js, test/bigtest/tests/user-edit-page-test.js
https://issues.folio.org/browse/UIU-913
This PR should fix two cases:
1. Changing status to inactive when `expirationDate` is empty or set with the date in the future
2. Keeping status as active when `expirationDate` is removed
=> UIU-913: Fix ability to mark user as inactive

Jenkinsfile
Unit tests are failing with the bunk error
```
Error: convergent assertion was successful, but exceeded the 2000ms timeout
```
preventing legit PRs from being merged. Hence, we are turning off unit
tests in CI because these bogus failures are preventing us from merging
any of our open work.
Refs [UIU-1566](https://issues.folio.org/browse/UIU-1566), [FOLIO-2097](https://issues.folio.org/browse/FOLIO-2097)
=> UIU-1566 TEMPORARILY disable unit tests in CI

CHANGELOG.md, src/settings/OwnerSettings.js
**Bug:** Settings --> Users --> Fee/Fine Owners only displays ten service points in the Associated Service Points drop-down.
**To do:** increase limit of service points in query
https://issues.folio.org/browse/UIU-1540
**Before**
**After**
=> UIU-1540: Add query param

src/routes/EditCustomFields.js, src/settings/CustomFieldsSettings.js
Import from `@folio/stripes/core` instead of `@folio/stripes-core` in
order to prevent NPEs. I think this worked prior to #1202 because the
SSC `<Settings>` component inadvertently, but fortuitously, provided
`stripes` to this component.
=> correctly import useStripes

package.json
`yarn` will load deps based on the _loosest_ dependency it finds, not
the strictest. This means if you have transitive deps on `~1.2.3` and
`^1.2.3` and the available package is `1.3.0` you'll get TWO copies!
Hooray! Poop.
We only want one copy of each of the `@folio/stripes-*` libraries in our
builds. With multiple copies, unit tests will not run.
Reverts that change from #1195.
=> stripes devDeps must use caret, not tilde

src/settings/FeeFineSettings.js
Properly filter owners, ignore automatic fee fines for copy modal.
https://issues.folio.org/browse/UIU-1550
**Before**
**After**
=> UIU-1550 - Copy existing fee/fine owner table drop-down entries incorrect

CHANGELOG.md, src/settings/OwnerSettings.js
Settings > Users > Fee/Fine Owners only displays ten service points
in the Associated Service Points drop-down. Bump the limit to 200.
Fixes [UIU-1540](https://issues.folio.org/browse/UIU-1540)
=> UIU-1540: Add query param (#1214)

src/index.js, src/views/UserDetail/UserDetail.js
This function got added, twice, _months_ ago in PR #839, but SonarCloud
just started complaining about it now. I don't know why it only came up
now, but it is (1) clearly a duplicate function, which is a bug and (2)
not called anywhere, which means it's safe to just get rid of it. So I'm
getting rid of it.
=> remove unused checkScope function

src/views/AccountDetails/AccountDetails.js
Instead of using `history.goBack()`, which can lead to navigation loops if
you arrive at the details-pane from an external application, use 
`history.push()` to navigate to `/users/${params.id}/accounts/${status}`.
Fixes [UIU-1542](https://issues.folio.org/browse/UIU-1542)
=> UIU-1542 - fixed incorrect close behavior (#1216)

src/settings/CommentRequiredSettings.js
It's very confusing how to use a local resource that should evaluate to a scalar.
A resource is an object. It may have scalar values, but the resource itself is an 
object. 
Here, trying to embed the resource `%{recordId}` in the path caused an error
because `recordId`, i.e. the resource itself, is an object, and thus would be 
serialized to `[object Object]`. The documentation isn't great on how this is
supposed to work. 
Fixes [UIU-1544](https://issues.folio.org/browse/UIU-1544)
=> UIU-1544 - updated recordId entity in manifest (#1217)

src/settings/FeeFineSettings.js
Remove empty fields from the request before submitting it. When a field is present, 
its value is expected to contain a foreign key. Thus, empty-string values present a 
problem and should instead be omitted.
Refs [UIU-1546](https://issues.folio.org/browse/UIU-1546)
=> UIU-1546 remove empty fields from request before submission

test/bigtest/network/factories/user.js
The user expiration-date was originally hard-coded to `2020-04-07`. What
do you know, today, tests started failing! Who knew that would happen!?!
Thanks to @mkuklis for fixing this on master in #1212 so I could easily
steal the fix and apply it here.
=> do not use hard-coded expiration dates

src/settings/FeeFineSettings.js, test/bigtest/network/factories/user.js
The owners-dropdown should only display owners who are affiliated with manual fee/fine types. Previously, it would erroneously include a blank entry which Holly figured out corresponded to automated charges created via overdue fine or lost item policies. This PR removes the blank entry.
Refs [UIU-1550](https://issues.folio.org/browse/UIU-1550)
=> UIU-1550 - removed blank option from copy modal owners dropdown

CHANGELOG.md, src/routes/UserSearchContainer.js, src/views/UserSearch/Filters.js, src/views/UserSearch/UserSearch.js
Add `Load more` button at the end of the result list in order to scroll records more easily.
Story [UIU-1532](https://issues.folio.org/browse/UIU-1532).
To achieve the needed functionality, in addition to the steps described in the [Migration Paths](https://github.com/folio-org/stripes-connect/blob/master/MIGRATIONPATHS.md), it was necessary to override the `onNeedMoreData` method in the `UserSearchContainer` component.
Thanks, @ryandberger, for pointing this out.
=> UIU-1532: Add 'Load more' button at the end of the result list

CHANGELOG.md, src/views/UserSearch/Filters.js
https://issues.folio.org/browse/UIU-1596
Thanks to @MikeTaylor for advocating for this approach. It made me look at this again and it turned out there was a way to use the `ids` instead of the names when building up the filter string.
=> UIU-1596: Build filter string by using ids instead of names

CHANGELOG.md, src/components/Accounts/Actions/Actions.js, src/components/UserDetailSections/UserAccounts/UserAccounts.js, src/routes/AccountDetailsContainer.js, src/routes/AccountsListingContainer.js, src/routes/ChargeFeesFinesContainer.js, src/routes/LoanDetailContainer.js, src/routes/LoansListingContainer.js, src/routes/UserRecordContainer.js, src/routes/UserSearchContainer.js, src/settings/FeeFineSettings.js, src/settings/OwnerSettings.js
Increase limits of fee-fines-related fetches:
* `accounts` - 10 000
* `feefineactions` - 10 000
* `feefines` - 10 000
* `owners` - 2000
* `groups` - 200 (patron groups)
Refs [UIU-1585](https://issues.folio.org/browse/UIU-1585)
=> UIU-1585 increase fetch limits for fee/fines endpoints

test/ui-testing/new-user.js
Since UIU-1511 it is no longer possible to directly set a user's
password during the user-creation process, thus those aspects are
removed from the test.
Refs [UIU-1511](https://issues.folio.org/browse/UIU-1511)
=> UIU-1511 remove password from new-user tests

test/ui-testing/new-permission-set.js
New-permission set form used to have a selector like `a div` but it
appears that switched to `div a` ... somewhere, probably in
`<MultiColumnList>` in stripes-components. This update tries to make the
selectors a little bit more semantic/robust. I'm not sure if it actually
does that or if it just rearranges things, but in any case tests work
again, so, yay.
Also, this moves all clicks into nightmare instead of doing some in
browser-scope, which is much more reliable.
See also folio-org/stripes-testing/pull/69 for parallel changes in the
shared handlers.
=> update MCL anchor handling

CHANGELOG.md, src/components/ModalContent/ModalContent.js, test/bigtest/helpers/setup-application.js, test/bigtest/tests/declare-lost-test.js
Based on the scenario 5 in https://issues.folio.org/browse/UIU-1203 we need to pass current servicePointId to `declare-item-lost` endpoint. This PR does just that.
https://issues.folio.org/browse/UIU-1203
=> UIU-1203: Pass current servicePointId to declare-item-lost endpoint

translations/ui-users/en.json
Fix typo in `Create password email confirmation` modal
https://issues.folio.org/browse/UIU-1475
=> UIU-1475: Fix typo

test/bigtest/helpers/monkey-patch-run.js, test/bigtest/index.js, test/bigtest/network/config.js, test/bigtest/tests/user-edit-page-test.js
This PR monkey patches the part of BigTest (`Interactor.prototype.run`) in order to turn off the famous error:
`convergent assertion was successful, but exceeded the ${timeout}ms timeout`.
The important change is here:
https://github.com/folio-org/ui-users/pull/1285/files#diff-6dd65ac431218c762d36549899c792ffR92-R108
=> Monkey patch BigTest

CHANGELOG.md, src/views/UserEdit/UserEdit.js
It looks like history was getting confused because we were not using `history.push` correctly:
When object is being passed to `history.push` we have to provide `search` and other parts of the url explicitly otherwise the path is not parsed correctly and the `search` part of the history object is lost.
The `search` piece is being used in locationService:
https://github.com/folio-org/stripes-core/blob/master/src/locationService.js#L6
and when that becomes incorrect it causes issues.
=> Use history.push correctly. Part of UIU-1620

src/views/UserEdit/UserEdit.js
Make the POST request when `username` is set after user was created
When Users --> Edit:
We need to differ if `username` is setted now or it was already setted, so the check was added if user's object contains the `username` field
https://issues.folio.org/browse/UIU-1503
=> UIU-1503: Fix updating user

src/views/UserEdit/UserForm.js
`formName` and `isReduxForm` props were added to make custom fields able to be used with both `final-form` and `redux-form`
=> UIU-1514: pass correct props to custom fields edit component

src/settings/sections.js, test/bigtest/tests/settings-custom-fields-test.js, test/bigtest/tests/user-edit-page-test.js
Users with custom fields attached cannot login at present. This creates
problems in the production environments if folks happen to add
custom-fields values to common users like `diku_admin`. Until we resolve
this larger issue, we are disabling the custom-fields routes to prevent
this common problem.
Refs [MODUSERBL-89](https://issues.folio.org/browse/MODUSERBL-89)
=> MODUSERBL-89 remove custom fields routes to prevent carnage

CHANGELOG.md, src/routes/UserSearchContainer.js, test/bigtest/network/config.js, test/bigtest/network/factories/credential.js, test/bigtest/network/models/credential.js
https://issues.folio.org/browse/UIU-1628
It looks like the work I did in: 
https://github.com/folio-org/ui-users/commit/7fb07a137e19b0d4e3a372bf98b675fd3be4ccc9#diff-26d2a657583a2e42dc1a61fc10acc892R191
broke `Reset all` button so this is pretty much reverting it back to what it was.
=> UIU-1628: Fix Reset all button for filters and query

CHANGELOG.md, src/components/UserDetailSections/UserAccounts/UserAccounts.js
If a promise returns after a component has unmounted, you can no longer
call `setState()`, so now we don't.
=> don't leak memory after unmount

CHANGELOG.md, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/Loans/OpenLoans/components/OpenLoansSubHeader/OpenLoansSubHeader.js, src/components/util/util.js, src/views/LoanDetails/LoanDetails.js, test/bigtest/interactors/loan-actions-history.js, test/bigtest/interactors/open-loans.js, test/bigtest/tests/claim-returned-test.js
Added functionality to disable/hide the Renew button if the item with status Claimed returned selected.
Story [UIU-1261](https://issues.folio.org/browse/UIU-1261).
=> UIU-1261: Prevent renewal of claimed returned item

CHANGELOG.md, src/views/LoanDetails/LoanDetails.js, test/bigtest/interactors/loan-actions-history.js, test/bigtest/tests/claim-returned-test.js, test/bigtest/tests/declare-lost-test.js, translations/ui-users/en.json
Introduce `Resolve claim` menu on the loan details view.
https://issues.folio.org/browse/UIU-1524
=> UIU-1524: Add resolve claim to loan details screen

CHANGELOG.md, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/Loans/OpenLoans/components/OpenLoansSubHeader/OpenLoansSubHeader.js, src/views/LoanDetails/LoanDetails.js, test/bigtest/interactors/loan-actions-history.js, test/bigtest/interactors/open-loans.js, test/bigtest/tests/claim-returned-test.js
Added functionality to disable/hide the `Change due date` button if the item with status Claimed returned selected.
Story [UIU-1260](https://issues.folio.org/browse/UIU-1260).
=> UIU-1260: Prevent change due date for claimed returned items

CHANGELOG.md, src/views/AccountDetails/AccountDetails.js
Refresh page after performing fee fine action.
https://issues.folio.org/browse/UIU-1644
Manually call accountActions.GET() endpoint in order to trigger getDerivedStateFromProps with proper data.
=> UIU-1644 - Fee/Fine Details is not refreshing, which may result in user entering duplicate actions

CHANGELOG.md, src/components/BulkOverrideDialog/BulkOverrideInfo.js, src/components/BulkRenewalDialog/BulkRenewInfo.js, src/components/ModalContent/ModalContent.js
https://issues.folio.org/browse/UIU-1660
Due to changes in [response-intl-safe-html](https://github.com/folio-org/react-intl-safe-html/commit/f3d494e47fe25160082b0c2e0777aa20f1cfa475), in the `SafeHTMLMessage` component, the default value of `tagName` (`'span'`) was deleted. Therefore, all elements within the `SafeHTMLMessage` were arranged in the order determined by its parent tag.
In those cases where the parent tag was used to align several elements (including `SafeHTMLMessage`), the property `tagHame='span'` has been explicitly set for the `SafeHTMLMessage`.
In other cases, the parent tag has been painlessly deleted.
**_Before_**
**_After_**
=> UIU-1660: Fix the arrangement of elements inside SafeHTMLMessage

CHANGELOG.md, src/components/Wrappers/withRenew.js
https://issues.folio.org/browse/UIU-1652
This is a difficult bug to reproduce as reported, since it apparently stems from an abnormal condition in which a loan is missing either an itemId or a loanPolicyId. But in artificial tests (i.e., deliberately breaking things), filtering out the null values before mapping the arrays seems to protect against the CQL errors.
=> UIU-1652: Protect loan action history page from CQL null query errors

CHANGELOG.md, src/views/AccountDetails/AccountDetails.js
After submitting a payment in the fee-fine modal, the payment details would not be displayed in the fee-fine details table.
Refs [UIU-1644](https://issues.folio.org/browse/UIU-1644)
=> UIU-1644 correctly show payment details

CHANGELOG.md, package.json, src/views/UserDetail/UserDetail.js, test/bigtest/network/config.js
This PR is trying to address issue described in: 
https://issues.folio.org/browse/UIU-1600
The user's details screen and edit form should now work without throwing bunch of errors when the `feefines` and `notes` interfaces are not present.
=> UIU-1600: Add interface checks for notes, feesfines and circulation

CHANGELOG.md, src/routes/LoanDetailContainer.js
This is a continuation of work @Baroquem did under https://github.com/folio-org/ui-users/pull/1340.
It looks like in some circumstances an empty loan object is being created here:
https://github.com/folio-org/ui-users/blob/3a3a2cf25082cb8dc8260b64a41ffec94a3f2071/src/routes/LoanDetailContainer.js#L129
Which was causing bunch of issues in `withRenew` (because the `loans` array contained one empty loan object):
https://github.com/folio-org/ui-users/blob/2f10ab037d7fb1704e6ec09441127b502cefdcf9/src/components/Wrappers/withRenew.js#L83
https://github.com/folio-org/ui-users/blob/2f10ab037d7fb1704e6ec09441127b502cefdcf9/src/components/Wrappers/withRenew.js#L63
This PR should address it.
https://issues.folio.org/browse/UIU-1653
=> UIU-1653: Check for an empty loan to protect from generating incorrect CQL

CHANGELOG.md, src/views/UserEdit/UserEdit.js
Previously, the "reset password" functionality of mod-login would fail
if a credentials record for the given user did not already exist
(MODLOGIN-131). A hedge around this was to create credentials records
with empty-string passwords whenever a username was added to a user
record. But that's a giant security hole, and now that MODLOGIN-131 is
resolved we no longer need to keep that workaround in place.
Refs [UIU-1671](https://issues.folio.org/browse/UIU-1671), [MODLOGIN-131](https://issues.folio.org/browse/MODLOGIN-131)
=> UIU-1671 do not create empty credentials records

CHANGELOG.md, package.json
See https://issues.folio.org/browse/UIU-1663 
I think https://github.com/folio-org/ui-users/pull/1353 allows us to have dual support for login 6.0 and 7.0
For additional context, see https://issues.folio.org/browse/MODLOGIN-128 and related issues
=> UIU-1663 - Add 7.0 login interface version

package.json, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, src/views/UserEdit/UserForm.js, test/bigtest/tests/user-edit-page-test.js, translations/ui-users/en.json
Rename permission to get the updated permission name. Also remove unnessesary permission from subPermissions.
https://issues.folio.org/browse/UIU-1337
=> UIU-1337: Rename permission

package.json, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, test/bigtest/tests/user-edit-page-test.js, translations/ui-users/en.json
Rename permission from `Users: Create/reset password send` to `Users: Create/reset password`
https://issues.folio.org/browse/UIU-1337
=> UIU-1337: Change permission name

CHANGELOG.md, src/components/Loans/ClosedLoans/ClosedLoans.js
https://issues.folio.org/browse/UIU-1204
Fix the bug of incorrect display of the date in the `Return date` field in the `Closed loans` table for the item was declared lost.
The functionality of the `<FormattedTime>` component from `react-intl` is implemented in such a way that when no return date presents, the current date and time are used by default. Therefore it was added a check for the presence of `Return date` value.
=> UIU-1204: Fix incorrect date display in Return date field

src/views/UserEdit/UserEdit.js, test/bigtest/interactors/settings-custom-fields.js, test/bigtest/tests/settings-custom-fields-test.js
When a custom field has no value, the backend expects us to not include that field in the payload.
=> fix custom fields payload formatting

CHANGELOG.md, src/components/Accounts/Actions/Actions.js, src/components/UserDetailSections/UserAccounts/UserAccounts.js, src/routes/AccountDetailsContainer.js, src/routes/AccountsListingContainer.js, src/routes/ChargeFeesFinesContainer.js, src/routes/LoanDetailContainer.js, src/routes/LoansListingContainer.js, src/routes/UserRecordContainer.js
Use `==` instead of `=` for more efficient queries.
Refs [PERF-62](https://issues.folio.org/browse/PERF-62)
=> PERF-62 use == for more efficient queries

CHANGELOG.md, package.json
`@folio/ui-plugin-find-user` must be updated for compatibility with
`@folio/stripes` `v4.0.0`.
=> increment ui-plugin-find-user for stripes compatibility

CHANGELOG.md, src/settings/patronBlocks/Limits/LimitsForm.js, test/bigtest/tests/patron-blocks/settings-limits-form-test.js
For patron block limits are allowed only integers values, but only for `Maximum outstanding fee/fine balance` condition allowed both decimal and integers.
https://issues.folio.org/browse/UIU-1675
=> UIU-1675: Add validation check for not decimal values

src/views/LoanDetails/LoanDetails.js
This is a continuation of work done under https://github.com/folio-org/ui-users/pull/1392 which belongs to
https://issues.folio.org/browse/UIU-1669
The link to the feefine details was broken after the refactoring done in  https://github.com/folio-org/ui-users/pull/1392
=> UIU-1669: Fix feefine details link

CHANGELOG.md, package.json, src/views/LoanDetails/LoanDetails.js
* Fix permissions so that get Custom Fields requests are allowed for users who don't have Settings permissions, but have view user details permissions
[UIU-1736](https://issues.folio.org/browse/UIU-1736)
=> UIU-1736:Fix Receive a toast error that maybe tied to custom field permissions

CHANGELOG.md, src/components/LoanActionDialog/LoanActionDialog.js, src/components/ModalContent/ModalContent.js, src/components/Wrappers/withDeclareLost.js, src/views/LoanDetails/LoanDetails.js, test/bigtest/tests/declare-lost-test.js
https://issues.folio.org/browse/UIU-1714
The purpose of this PR is to make it impossible to declare an item lost more than once in a row.
The `Declare lost` button was disabled for the duration of the previous `declare lost` action.
=> UIU-1714: Prevent declaring an item lost if it is already lost

CHANGELOG.md, src/components/BulkOverrideDialog/BulkOverrideInfo.js
https://issues.folio.org/browse/UIU-1712
Add `servicePointId` property to the request when the user overrides a loan.
=> UIU-1712: Add servicePointId property when overriding a loan

CHANGELOG.md, src/components/EditSections/EditContactInfo/EditContactInfo.js, src/components/UserDetailSections/ContactInfo/ContactInfo.js, src/components/UserDetailSections/PatronBlock/PatronBlock.js, test/bigtest/tests/patron-blocks-test.js, translations/ui-users/en.json
Change capitalization of sections in User Information:
`Patron Blocks` section should be `Patron blocks`
`Contact Information` section should be `Contract information`
https://issues.folio.org/browse/UIU-1754
=> UIU-1754: Change capitalization of sections in User Information

CHANGELOG.md, src/constants.js
`MAX_RECORDS` was added to `master` in a PR separate to those that were cherry-picked onto the `b4.0` branch, but we need it here as `ChargeFeesFinesContainer` makes use of it.
=> include MAX_RECORDS constant

CHANGELOG.md, src/components/Accounts/Actions/WarningModal.js, src/components/Accounts/Actions/modal.css
Fix button placement in pay/waive/transfer fees/fines 'deselect' modal (the buttons should not be so close to the last row of the table).
https://issues.folio.org/browse/UIU-1756
**Before**
**After**
=> UIU-1756: fix buttons layout

CHANGELOG.md, src/settings/FeeFineSettings.js, test/bigtest/tests/settings-manual-charges-test.js, translations/ui-users/en.json
We need to differ when there was not setted `charge/action notices` and display `-`, from when there was not setted `charge/action notices` but there are exist `charge/action notices` by default and display `Default`. 
https://issues.folio.org/browse/UIU-1755
**Before**
**After**
=> UIU-1755: Change '-' to 'Default' if default notice exists at Fee/Fine: Manual Charges

src/components/EditSections/EditProxy/EditProxy.js, src/components/UserDetailSections/ProxyPermissions/ProxyPermissions.js, src/components/UserDetailSections/UserAccounts/UserAccounts.js, src/views/AccountsListing/AccountsListing.js, test/bigtest/tests/fee-fine-history-test.js, translations/ui-users/en.json
Change capitalization of sections in User Information:
`Proxy/Sponsor` changed to `Proxy/sponsor`
`Fees/Fines` changed to `Fees/fines`
https://issues.folio.org/browse/UIU-1760
=> UIU-1760: Change capitalization of sections in User Information

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIU-1757
Add permission to anonymize manually closed loans.
=> UIU-1757: Add permission to anonymize manually closed loans

CHANGELOG.md, package.json
The tag-management component would display but throw errors because
there was no way to assign tag-related permissions in the UI. The
interaction between tag-CRUD permissions and entity-CRUD permissions can
be confusing and the `<Tags>` component does not, at present, handle
discrepancies between them.
Refs [UITAG-29](https://issues.folio.org/browse/UITAG-29)
=> UITAG-29 provide tag-related permissions

CHANGELOG.md, src/components/Loans/OpenLoans/OpenLoansControl.js, src/routes/AccountDetailsContainer.js, src/settings/patronBlocks/Conditions/Conditions.js, src/views/AccountDetails/AccountDetails.js, src/views/LoanDetails/LoanDetails.js, src/views/LoanDetails/LoanProxyDetails.js, src/views/UserSearch/Filters.js, test/bigtest/tests/declare-lost-test.js, test/bigtest/tests/permissions-assign-test.js, test/bigtest/tests/permissions-modal-test.js, test/bigtest/tests/user-edit-page-test.js, test/bigtest/tests/user-proxy-edit-test.js
The source of this problem was that the tags filter in the user search
was set to use tag ID when filtering by tag. This does not work because
the 'tags' smart component does not store tag IDs in entity records. It
stores the tag names as a list. So the only way to filter for any entity,
including users, is to filter by tag name. Changing this would require
reworking a fairly substantial portion of the tags smart component, so I
simply changed the search in ui-users back to filtering by tag name.
This PR also includes fixes for broken tests in UI-users.  These changes
are related to UIU-1801, but they don't fix that issue-I just adjusted the 
tests to work around it so people can merge PRs while it gets worked 
on, since the fix for that issue seems likely not to be simple.
refs: …
=> UIU 1750: Filter users by tags does not work

CHANGELOG.md, src/components/data/static/loanActionMap.js, src/views/LoanDetails/LoanDetails.js, translations/ui-users/en.json
Add handling for the loan action `itemAgedToLost`, and add handling if
new, as of yet unknown statuses, are added so the UI can display
`unknown action` instead of exploding with a stacktrace when they do.
Refs [UIU-1791](https://issues.folio.org/browse/UIU-1791)
=> UIU-1791 handle known/unknown loan action values

CHANGELOG.md, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/util/util.js, src/views/LoanDetails/LoanDetails.js
Use item id instead of barcode for links to ui-requests module.
https://issues.folio.org/browse/UIU-1727
=> UIU-1727: Use item id instead of barcode for links to ui-requests module

CHANGELOG.md, test/bigtest/helpers/setup-application.js
We determined that tests in UI-users were failing because
The discovery part of the store is now only populated after a successful
login.This caused some tests to fail because the discovery information
was missing, especially data on interfaces and modules needed for some
pages to load/ behave properly.
Refs:
https://github.com/folio-org/stripes-core/pull/907
https://github.com/folio-org/stripes-core/pull/893/files
=> Fix: Breaking tests in Ui-Users

src/components/Accounts/Actions/ActionModal.js
Use FIVE characters to display one space because ESLint is awesome and
makes everything easier. **sigh** Well, the code may not look better,
but hopefully the UI does.
=> add space after checkbox

CHANGELOG.md, src/components/Loans/OpenLoans/helpers/isOverridePossible/overridePossibleMessages.js
https://issues.folio.org/browse/UIU-1464
Have you ever wanted to renew an item that had been aged to lost, but found yourself stymied by the rigid rules of circulation? Well, now you can! Sometimes. With the right power. If you really think it's a good idea.
=> UIU-1464: Enable renewal override for Aged to lost items

CHANGELOG.md, src/components/Loans/OpenLoans/helpers/isOverridePossible/overridePossibleMessages.js, src/views/LoanDetails/LoanDetails.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-1803
This is to ensure that Aged to lost actions are properly represented in the loan details action history table. Most of the work for this is done automatically on the backend. The one UI change needed is to insert "System" into the source column whenever it's blank in the original.
=> UIU-1803: Include Aged to lost in loan details action history

src/views/LoanDetails/LoanDetails.js
- Fixes [UIU-1802](https://issues.folio.org/browse/UIU-1802).
- Handles network failures on the loan details screen.
- Instead of the page crashing, now network errors pop up on the screen for Back-End devs to debug:
=> Add null checks to prior to `status` property

CHANGELOG.md, src/settings/PatronGroupsSettings.js
Remove user count from patron groups.
https://issues.folio.org/browse/UIU-1562
=> UIU-1562: Remove user count from patron groups

CHANGELOG.md, src/components/util/util.js, src/routes/UserRecordContainer.js, src/views/UserEdit/UserEdit.js
https://issues.folio.org/browse/UIU-1369
This PR replaces the one-by-one permissions assignments with an all-in-one assignment, thanks to the API that Julian pointed out. For the case of assigning all available permissions to a user, that means a reduction from 200+ API requests down to one, or at most two. Hooray!
=> UIU-1369: Assign permissions more efficiently

CHANGELOG.md, package.json
Upgrade `react-intl` to `v5` since that is part of `@folio/stripes`
`v5`.
Refs [UIU-1851](https://issues.folio.org/browse/UIU-1851), [STRIPES-694](https://issues.folio.org/browse/STRIPES-694)
=> UIU-1851 react-intl v5

CHANGELOG.md, src/components/Wrappers/withServicePoints.js
This took a while to find.
the `nextProps.mutator.servicePointUserId.replace` was called multiple times when navigating away and back to users module causing:
````
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
````
https://issues.folio.org/browse/UIU-1849
=> UIU-1849: Only set servicePointUserId when it's present

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/UserInfo.js, translations/ui-users/ar.json, translations/ui-users/ca.json, translations/ui-users/da.json, translations/ui-users/de.json, translations/ui-users/en.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json, translations/ui-users/es.json, translations/ui-users/es_419.json, translations/ui-users/es_ES.json, translations/ui-users/fr.json, translations/ui-users/fr_FR.json, translations/ui-users/he.json, translations/ui-users/it_IT.json, translations/ui-users/ja.json, translations/ui-users/pt_BR.json, translations/ui-users/pt_PT.json, translations/ui-users/ru.json, translations/ui-users/ur.json, translations/ui-users/zh_CN.json, translations/ui-users/zh_TW.json
The output we are after here is something like this:
```
Barcode: <a href="">1234</a>
```
but the way it was coded, the translation value needed to contain
`Barcode: ` (note the trailing space). Sometimes it did, sometimes it
didn't, sometimes it didn't have the colon either. It was amazing how
much inconsistency there was, and how much that one space bugged the
crap outta me. No longer. No whitespace and no punctuation in the
translation should bring more consistent results.
=> consistent spacing around the colon

CHANGELOG.md, src/components/PermissionsAccordion/components/PermissionsModal/PermissionsModal.js
`<Paneset>`s contained in `<Modal>`s in layers [should not report their
size back to their ancestors](/folio-org/stripes-components/tree/master/lib/Paneset/#panesets-within-layers).
h/t @NikitaSedyx from [UIPFU-31](/folio-org/ui-plugin-find-user/pull/151/)
Refs [UIU-1857](https://issues.folio.org/browse/UIU-1857)
=> UIU-1857 do not report Paneset's size in modal

src/components/UserDetailSections/UserLoans/UserLoans.js
the loans accordion will have spacing between the number of open loans and claimed-returned loans
Ticket
https://issues.folio.org/browse/UIU-1665
Changes
Added {' '} to the front of claimed-returned loans to create a space. See commit for more detail.
=> Added space between open loan and claim return number

CHANGELOG.md, src/views/UserSearch/UserSearch.js, test/bigtest/interactors/users.js, test/bigtest/tests/overdue-loan-report-test.js
https://issues.folio.org/browse/UIU-1858
Prevent access to the Overdue loans report option if the user doesn't have view loan permissions.
=> UIU-1858: Hide Overdue loans report when no view loan permissions

CHANGELOG.md, src/components/Loans/OpenLoans/helpers/isOverridePossible/overridePossibleMessages.js, test/bigtest/tests/open-loan-renew-test.js
https://issues.folio.org/browse/UIU-1853
The infrastructure was already in place to enable overrides for loan actions that result in various error conditions, so this was just a matter of adding one more condition to the list.
=> UIU-1853: Allow overrides for renewals where due date doesn't change

src/components/Accounts/Actions/FeeFineActions.js, src/routes/AccountDetailsContainer.js
Added fixes of:
- `transactionInfo` field accepted for `payment` action only
- `contributor` record should be shown for fee/fines associated with `item` only 
https://issues.folio.org/browse/UIU-1793
=> UIU-1793: Fee/fines refactoring

src/components/Accounts/Actions/ActionModal.js, src/components/Accounts/Actions/FeeFineActions.js, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/Accounts/accountFunctions.js, src/views/AccountDetails/AccountDetails.js, test/bigtest/network/scenarios/fee-fine-details.js
Add fixes of refund functionality:
- `Refund` button should be active only if actions `payment` or `transfer` were occured
- `Refund amount` should include `payment` or/and  `transfer` already payed `amount` (not `waive` amount) 
https://issues.folio.org/browse/UIU-1850
**Before**
**After**
**Before**
**After**
=> UIU-1850: Refund fee/fines

src/components/Accounts/accountFunctions.js, test/bigtest/tests/fee-fine-details-test.js
Because of `refund` functionality does not finish yet, lets always show `refund` button disabled, and release refactoring fees/fines without refunding.
=> Always disable refund button

CHANGELOG.md, package.json
Apps and plugins must depend on the same versions of peer dependencies.
Refs [UIU-1901](https://issues.folio.org/browse/UIU-1901)
=> UIU-1901 update plugins for stripes v5 compat

CHANGELOG.md, src/components/EditSections/EditServicePoints/EditServicePoints.js
https://issues.folio.org/browse/UIU-1892
This is a bit of an odd one. It seems that if the editing window is invoked too quickly after saving, somehow the resources for service points are duplicated. I haven't been able to trace the exact cause, but it turns out that it's easy enough to filter out the duplicates if that happens.
=> UIU-1892: Fix bug in display of add service point dialog

CHANGELOG.md, src/components/UserDetailSections/PatronBlock/PatronBlock.js, src/routes/AccountDetailsContainer.js, src/routes/LoanDetailContainer.js
When searching by `id`, use a field-level match (`==`) rather than a
word-match (`=`).
Refs [UIU-1913](https://issues.folio.org/browse/UIU-1913)
=> UIU-1913 use more efficient queries

src/components/Accounts/Actions/FeeFineActions.js, src/routes/ChargeFeesFinesContainer.js
Filter feefineactions by userId
https://issues.folio.org/browse/UIU-1895
=> UIU-1895 - "Open fee/fine" page retrieves feefineactions and feefines records without qualifier

CHANGELOG.md, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, src/components/UserDetailSections/ExtendedInfo/ExtendedInfo.js
https://issues.folio.org/browse/UIU-1035
Relocate the username/password in the create/edit and detail view screens
=> UIU-1035 relocate username password in edit create detail

CHANGELOG.md, src/views/UserSearch/UserSearch.js, test/bigtest/network/config.js, test/bigtest/tests/users-show-all-test.js, translations/ui-users/en.json
This PR adds support for searching on the `personal.lastName` field of a user explicitly.
It adds `personal.lastName` to the `rawSearchableIndexes` of `UserSearch.js`. 
Refs https://issues.folio.org/browse/UIU-1706
=> UIU-1706: Search index last name

CHANGELOG.md, src/views/UserSearch/UserSearch.js, test/bigtest/network/config.js, test/bigtest/tests/users-show-all-test.js, translations/ui-users/en.json
This PR adds support for searching on the `barcode` field of a user explicitly.
It adds `barcode` to the rawSearchableIndexes of UserSearch.js.
Refs https://issues.folio.org/browse/UIU-1708
=> UIU-1708: Search index barcode

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/Accounts/accountFunctions.js, test/bigtest/interactors/user-form-page.js, test/bigtest/tests/user-edit-page-test.js
Manual `fee/fine` can be created `with` associated item or `without` (more often).
**Before:**
When `fee/fine` is not related to any `item`, in POST to `account` we sent such fields (`itemID`,  `loanId`, `materialTypeId`, `materialType`) with value `"0"` - because they were `required`
**Now:**
If no value for  (`itemID`,  `loanId`, `materialTypeId`, `materialType`) - we do not send them. Now these fields became `optional` [(MODFEE-88)](https://issues.folio.org/browse/MODFEE-88) 
Also in previous [PR](https://github.com/folio-org/ui-users/pull/1539), the failing test was skipped. In current PR was changed `Popover` interactor for fixing skipped test.
https://issues.folio.org/browse/UIU-1773
=> UIU-1773: Omit optional fields without values when Fee/Fine is created

CHANGELOG.md, package.json
After update version of `feesfines okapi interface` [here](https://github.com/folio-org/ui-users/pull/1544), major version of `ui-users` should be bumped as well
=> Update module version

CHANGELOG.md, src/routes/filterConfig.js
https://issues.folio.org/browse/UITAG-34
It looks like due to the change in stripes-components:
folio-org/stripes-components#1368
The searching by tags stopped working because tags.tagList only works with `=` operator.
=> UITAG-34: Fix filtering by tags

src/components/Accounts/Actions/FeeFineActions.js
Fix sending of transactionInfo field to BE for pay action.
https://issues.folio.org/browse/UIU-1938
=> UIU-1938 - 'Transaction information' not saved/displaying when 1 fee/fine paid

CHANGELOG.md, src/components/PatronBlock/PatronBlockForm.js, src/components/PatronBlock/PatronBlockLayer.js
- The next day after manual patron block was created, after view block the date was changed to the next or previous date, which should not be changed
- The manual block should be expired on the `00:00 am` at expirated date 
https://issues.folio.org/browse/UIU-1942
**Before**
**After**
=> UIU-1942: Manual block expiration date

src/views/UserDetail/UserDetail.js
This PR adds the tags button to UserDetail's lastMenu again to re-enable user tagging.
It was unintentionally removed by UIU-775, as noted in this [comment](https://github.com/folio-org/ui-users/pull/1529#issuecomment-721873861).
Refs https://issues.folio.org/browse/UIU-1949
=> UIU-1949: Add tags button to re-enable user tagging

CHANGELOG.md, src/views/UserSearch/Filters.js
Use `Array.sort()` and `String.localeCompare()` when sorting values for
filters to handle the sort in a case-insensitive manner.
Refs [UIU-1948](https://issues.folio.org/browse/UIU-1948)
=> UIU-1948 ignore case when sorting filter values

CHANGELOG.md, package.json
Requests related to open loans were incorrectly retrieved in the
`<ChangeDueDateDialog>` component. This was fixed in
`stripes-smart-components` `v5.0.1`, available in `stripes` `v5.0.2`.
Refs [UIU-1932](https://issues.folio.org/browse/UIU-1932), [UIU-1935](https://issues.folio.org/browse/UIU-1935), [STSMACOM-452](https://issues.folio.org/browse/STSMACOM-452)
=> UIU-1932, UIU-1935 correctly retrieve related requests

CHANGELOG.md, src/components/Loans/OpenLoans/helpers/isOverridePossible/overridePossibleMessages.js, test/bigtest/network/scenarios/request-related-failure-multiple-errors.js
Allow override for not loanable items when loan policy is not recognized.
https://issues.folio.org/browse/UIU-1930
It looks like we need to handle one more additional error coming from the server in order to allow for override.
=> UIU-1930: Allow override for not loanable items

CHANGELOG.md, src/components/Accounts/ViewFeesFines/ViewFeesFines.js, src/components/Accounts/accountFunctions.js, src/views/AccountDetails/AccountDetails.js, test/bigtest/interactors/fee-fine-details.js, test/bigtest/tests/fee-fine-cancel-test.js, test/bigtest/tests/fee-fine-details-test.js
Allow `cancel` fee/fine as `error ` only if any actions has not been applied and disabled `error` button if any actions were occured.
https://issues.folio.org/browse/UIU-1894
=> UIU-1894: Allow cancel fee/fine as error only if any 'actions' has not been applied

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/Accounts/ChargeFeeFine/ChargeForm.js, src/components/Accounts/ChargeFeeFine/FeeFineInfo.js, test/bigtest/network/config.js
New Fee/Fine page not listing Fee/Fine Types for predefined selected Fee/Fine Owner
Since `ChargeFeeFine` form was migrated to `react-final-form` this issue with selects of `Fee/Fine Owner` and `Fee/Fine Type` appeared, because for proper work of this related to each other selects we should pass `Fee/Fine Owner` in initial values. Accordingly appears the problem that  `Fee/Fine Owner` exists but `Fee/Fine Type` does not show any options, so now `Fee/Fine Types` for initial `Fee/Fine Owner` is passing in prop as `dataOptions` for `Fee/Fine Type` select.
Also to get proper `Fee/Fine Type` select value, we should `await` while parent's `onChange` handler will update the `state`.
https://issues.folio.org/browse/UIU-1968
**Before**
**After**
=> UIU-1968: Show default fee/fine types

src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js
'Payment methods' not always appearing for 'Charge & pay now' option of New fee/fine for predefined Owner
https://issues.folio.org/browse/UIU-1975
=> UIU-1975: Fix empty payments select

CHANGELOG.md, src/routes/LoanDetailContainer.js, src/views/LoanDetails/LoanDetails.js, test/bigtest/interactors/loan-details-404.js, test/bigtest/tests/loan-missing-test.js, translations/ui-users/en.json
If a URL for a loan is bookmarked (or copied, or stored in any way,
really), and then that loan is anonymized, show a "can't find that loan"
message.
Previously, the loan-details page would instead show a "loading"
spinner, as though the loan were being retrieved and just hadn't loaded
yet. Now, we show a "missing loan" message when fetching a user's loans
has finished and no matching loan is present.
Refs [UIU-1045](https://issues.folio.org/browse/UIU-1045)
=> UIU-1045 show "awol loan" when loan is ... awol

src/components/Accounts/ChargeFeeFine/ChargeForm.js, test/bigtest/tests/charge-and-pay-fee-fine-test.js
Since there are have appeared few bugs related to creation Fee/Fines through `Charge&pay` button, the decision was made to show always disabled `Charge&pay` button for [bugfest env](https://bugfest-honeysuckle.folio.ebsco.com/)
https://issues.folio.org/browse/UIU-1980
=> UIU-1980: Disable Charge&pay button

src/components/EditSections/EditUserInfo/EditUserInfo.js
Refs [UIU-1973](https://issues.folio.org/browse/UIU-1973)
In the User Edit form, when the form opens, there were no focused field by default.
Now focus goes to Last Name field.
=> UIU-1973 auto-focus Last Name field in user edit form

src/routes/AccountDetailsContainer.js, src/routes/ChargeFeesFinesContainer.js
Since on bugfest env New Fee/Fine option 'Charge only' no longer creating charge 'action', the problem appeared after huge amount of testing fee/fines. 
https://issues.folio.org/browse/UIU-1985
**Before**
**After**
=> UIU-1985: New Fee/Fine option 'Charge only' no longer creating charge 'action'

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/Accounts/ChargeFeeFine/ChargeForm.js, test/bigtest/network/factories/feefineaction.js, test/bigtest/tests/charge-and-pay-fee-fine-test.js
When you generate a manual fee/fine using the 'Charge & pay now' option, two 'actions' are created. One for the charge and one for the payment. Both payments 'action' should be listing the Source as the staff member who took the payment.
Also in scope of this ticket the button "Charge & pay now" became active again. 
https://issues.folio.org/browse/UIU-1981
**Before**
**After**
=> UIU-1981: Show correct fee/fine source

CHANGELOG.md, src/components/EditSections/EditServicePoints/EditServicePoints.js, test/bigtest/tests/service-points-modal-test.js
https://issues.folio.org/browse/UIU-1912
To be similar to the `Add permissions` functionality, the mechanism for selecting service points to be displayed in the user record has been changed. Now only the marked service points will be displayed, and not added to the existing ones, as it was before.
=> UIU-1912: Fix selection of service points to display in the user record

CHANGELOG.md, package.json
- Increased `notes` interface version to `2.0`.
https://github.com/folio-org/stripes-smart-components/pull/967
https://github.com/folio-org/ui-notes/pull/134
=> Increased "notes" interface version to "2.0"

src/components/Accounts/Actions/FeeFineActions.js
The multiple refund in Fees/Fines History does not refresh right after the multiple waive 
https://issues.folio.org/browse/UIU-1897
=> UIU-1897: Refresh feeFineActions

CHANGELOG.md, src/components/ErrorModal/ErrorModal.js, src/components/LoanActionDialog/LoanActionDialog.js, src/components/ModalContent/ModalContent.js, src/constants.js, test/bigtest/interactors/open-loans.js, test/bigtest/tests/declare-lost-test.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-2004
An error modal appears when an item is declared lost and a lost fee will be charged. In this case, a 
fee/fine owner for the item effective permanent location service point must be created.
This PR resolves the bug by displaying a more informative message explaining the cause and how to fix it.
=> UIU-2004: Set informative message when error declaring item lost

CHANGELOG.md, src/components/Accounts/Actions/CancellationModal.js, translations/ui-users/en.json
- Change 'Reason for cancellation' to 'Additional information for staff' on Cancel Fee/Fine page
- Remove empty line between label and textarea
https://issues.folio.org/browse/UIU-1999
**Before**
**After**
=> UIU-1999: Change label in Cancellation Modal

CHANGELOG.md, package.json, translations/ui-users/en.json
- Add 'User: Can override patron blocks' permission
https://issues.folio.org/browse/UIU-2025
=> UIU-2025: add can override patron blocks permission

CHANGELOG.md, package.json, translations/ui-users/en.json
- Add 'User: Can override item blocks' permission
https://issues.folio.org/browse/UIU-2019
=> UIU-2019: add can override item blocks permission

package.json, translations/ui-users/en.json
- Add 'User: Can override item blocks' permission
https://issues.folio.org/browse/UIU-2019
=> UIU-2019: Add permission for can override item blocks

package.json, translations/ui-users/en.json
- Add 'User: Can override patron blocks' permission
https://issues.folio.org/browse/UIU-2025
=> UIU-2025: Add permission for can override patron blocks

CHANGELOG.md, src/components/RefundsReportModal/RefundsReportModal.js, src/views/UserSearch/UserSearch.js
The issue is related to tenant's timezone. No matter what date is selected, the previous day appears.
https://issues.folio.org/browse/UIU-2033
=> UIU-2033: Unable to select today's date for refund report	

CHANGELOG.md, src/components/Accounts/Actions/FeeFineActions.js, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, test/bigtest/network/factories/feefineaction.js
Add consistency changes when 'Fee/Fine action' was occured (from all pages: ChargeFeeFine, AccountsHistory, AccountDetails).
Value or empty string will be sent instead of `-`.
- when POST on `${action}` endpoint - field `transactionInfo` is always present with `value` or empty string
- when POST on `feefineactions` endpoint - field `transactionInformation` is always present with `value` or empty string
transactionInformation field should be the same in both objects. Preferably, it should be equal to "". We need to handle this value correctly on the Fee/fine details page and display it as "-".
https://issues.folio.org/browse/UIU-2048
=> UIU-2048: Work with Transaction Information field

CHANGELOG.md, src/components/EditSections/EditUserInfo/EditUserInfo.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-2058
The text on the **expiration data modal**  needs to be changed.
The new text should be as follows:
**Heading:**
"Set expiration date?"
**Text:**
"Library accounts with patron group group expire in offset days. Do you want to set this user’s account to expire on date?"
**Button:**
"Set" instead of "Recalculate"
In addition, the text of the button in the users **edit form** needs to be changed:
**Button:** 
"Re-set" instead of "Recalculate".
**Important:**
The SIG wishes the previewed expiration date in the modal to have the format like in "March 1, 2023".
The important parts of the text should be in bold - The UM SIG agreed on this in yesterday's meeting. So the text should be like this:
Library accounts with patron group **group** expire in …
=> UIU-2058 rewording for text on expiration date modal 

CHANGELOG.md, src/components/EditSections/EditUserInfo/EditUserInfo.js
https://issues.folio.org/browse/UIU-2059
**Overview:**
**Steps to Reproduce:**
1. Go to users app
2. Choose a user record with a patron group that has an expiration date offset defined in the settings
3. Open this user record for editing
**Expected Results:** The modal should only open on patron group change.
**Actual Results:** The modal opens right away, for every edit
This is a new bug, the behaviour has been correct before.
=> UIU-2059 expiration date modal open bug

src/components/Loans/OpenLoans/OpenLoansControl.js, src/components/Loans/OpenLoans/components/OpenLoansSubHeader/OpenLoansSubHeader.js, src/components/util/index.js, src/components/util/patronBlocks.js, src/views/LoanDetails/LoanDetails.js
- Add possible for show Patron blocks modal for renew with automated patron blocks
- Move reusable code to utils
https://issues.folio.org/browse/UIU-2062
Patron blocks modal
Patron blocks modal not appear for renew for automated patron blocks 
Patron blocks modal appear for renew for automated patron blocks
=> UIU-2062: Patron blocks do not appear for renew for automated patron blocks

src/views/UserEdit/UserForm.js
As noted in the [custom fields documentation](https://github.com/folio-org/stripes-smart-components/tree/d954b19c5ffefe449de91a371976501a9bd29159/lib/CustomFields),
`changeFinalFormField` is necessary when using `final-form` but was
omitted when ui-users was refactored to final-form in #1645. Probably,
we didn't have any custom fields configured at the time and therefore
did not notice the omission.
Refs [UIU-1474](https://issues.folio.org/browse/UIU-1474)
=> UIU-1474 pass required props to custom-fields

CHANGELOG.md, src/components/UserDetailSections/UserAccounts/UserAccounts.js
This PR Improves fetching account data by making sure fetch happens only once per given query. It also removes unused `accountsHistory` definition from the `UserAccounts` manifest.
https://issues.folio.org/browse/UIU-2063
Fetches before this change:
Fetches after:
=> UIU-2063: Improve fetching account data

src/components/UserDetailSections/UserAccounts/UserAccounts.js, src/constants.js, src/views/UserDetail/UserDetail.js, test/bigtest/tests/fee-fine-history-test.js
https://issues.folio.org/browse/UIU-2063
We made some progress to cut the number of requests related to accounts from 6 to 3 in https://github.com/folio-org/ui-users/pull/1666
This PR takes it further based on some good feedback from @wafschneider under [UIU-2063](https://issues.folio.org/browse/UIU-2063?focusedCommentId=99814&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-99814) and cuts it down to a single request. The number of open and closed accounts are calculated on the client.
=> UIU-2063: Refactor UserAccounts to use single fetch for accounts data

CHANGELOG.md, package.json
Update deps for compatibility with `@folio/stripes` `v6`, including:
* `@folio/plugin-find-user`
=> use deps compatible with @folio/stripes v6

CHANGELOG.md, src/components/UserDetailSections/PatronBlock/PatronBlock.css, src/components/UserDetailSections/PatronBlock/PatronBlock.js
We should  add clickable indicate  for cursor when we navigate to manual block.
I according that we don't have possible add css class to row we add content wrapper for cell. Cursor should appear only for clickable block(manual block).
https://issues.folio.org/browse/UIU-2052
=> UIU-2052: Add changes to indicate clickable for cursor

CHANGELOG.md, src/components/UserDetailSections/PatronBlock/PatronBlock.js
We should  migrate from string notation to column mapping for PatronBlock
We should use column mapping approach for consistency, readable and etc.
https://issues.folio.org/browse/UIU-2091
After merge UIU-2052 ( https://github.com/folio-org/ui-users/pull/1675 ) we should change target branch to master
=> UIU-2091: Migrate from string notation to column mapping for PatronBlock

CHANGELOG.md, src/views/UserSearch/UserSearch.js
https://issues.folio.org/browse/UIU-1884
Checks for the ui-users.loans.view perm before displaying the menu item for the claimed returned CSV report.
=> UIU-1884: Show claimed returned report only if user has necessary permission

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/Accounts/ChargeFeeFine/ChargeForm.js, src/components/Accounts/ChargeFeeFine/FeeFineInfo.js
"Notify patron" box should be check marked for "New fee/fine" when default patron notice is set.
When we have initial values for Fee/fine owner or we select them should work the same logic.
https://issues.folio.org/browse/UIU-2111
=> UIU-2111: Fix Notify patron box behavior for New fee/fine when default patron notice is set

CHANGELOG.md, src/components/PatronBlock/PatronBlockForm.js
When we have invalid values Manual patron block "Save & close" button should be disabled
https://issues.folio.org/browse/UIU-2123
=> UIU-2123: Fix disabling "Save & close" button for Manual patron block

CHANGELOG.md, src/components/PatronBlock/PatronBlockForm.js
Not allowed to have an expiration date of today because manual patron blocks will be expire.
https://issues.folio.org/browse/UIU-2122
=> UIU-2122: Fix the possibility of create manual patron block with expiration date of today

CHANGELOG.md, package.json
We should have possible for create "Refunds to Process Manually" report
Permission was changed on BE from feefine-reports.refund.get to feefine-reports.refund.post, we add consistency changes on UI
https://issues.folio.org/browse/UIU-2126
=> UIU-2126: Fix permission error for Refunds to Process Manually report

CHANGELOG.md, package.json
The only breaking change in `circulation` `10.0` was the removal of the
`override-check-out-by-barcode` which is not used here, hence continuing
to support `9.0`.
Refs [UIU-2135](https://issues.folio.org/browse/UIU-2135)
=> UIU-2135 also support circulation 10.0

CHANGELOG.md, package.json
`stripes-cli` `2.1.1` locks `stripes-webpack` to `~1.1.0`, avoiding the
`1.2.0` release that adds some helpful things to do with CSV files and
the new react JSX transform but that does not play nice with BigTest for
some developers, making tests impossible to run, and, therefore,
releases impossible to release. This allows tests to be run locally in
order to prove they run successfully, even when the fail consistently
in CI.
Refs [UIU-2137](https://issues.folio.org/browse/UIU-2137)
=> UIU-2137 lock stripes-cli to ~2.1.1

CHANGELOG.md, src/components/PermissionsAccordion/components/PermissionsModal/PermissionsModal.js
ASTified translations are no longer formatted as `{string, string}`,
they are `{string, array}` and the permission-search feature doesn't
know how to handle this. Given permission translation values should not
have any substitutions in them, we can somewhat naively inspect the 0th
element when the value is an array.
See also https://github.com/folio-org/ui-developer/pull/236
Refs [UIU-2142](https://issues.folio.org/browse/UIU-2142)
=> UIU-2142 handle search of ASTified translations

CHANGELOG.md, src/components/Wrappers/withRenew.js
The limit clause in the request count query was missing. We did a nice
job batching the query to handle a long list of loan-ids, but,
astonishingly, completely forgot that if we had, say, 15 loan-ids, we
might get 15+ requests (or even if we had only one loan-id that it might
have 15 open requests). Whoops.
Refs [UIU-2143](https://issues.folio.org/browse/UIU-2143)
=> UIU-2143 include missing limit clause in request-count query

src/settings/index.js
Use `{sectionInner}` within JSX to evaluate the variable; without the
braces, it's just a string.
Bugfix for #1707 
Refs [UIU-2140](https://issues.folio.org/browse/UIU-2140)
=> correctly include sectionInner

src/components/ErrorPane/ErrorPane.js
The bugfest environment is not using the newest version of `stripes-webpack` which includes new version of jsx transform: https://github.com/folio-org/stripes-webpack/pull/11
This PR imports `react` in order to avoid issues like this one in bugfest:
`Error: ReferenceError: React is not defined`
=> Import react

CHANGELOG.md, src/components/PermissionsAccordion/components/PermissionsList/PermissionsList.js, src/components/UserDetailSections/UserAccounts/UserAccounts.js, src/views/UserDetail/UserDetail.js
Some proptype declarations have drifted out of sync and generate bogus
console warnings, making legit console messages difficult to track down
amid the noise.
* PermissionsList.js: `displayName` is not a required attribute of
permissions.
* UserAccounts.js: `accounts` represents the resource. It contains
an array of records, but it is not itself an array of records.
* UserDetail.js: a user's service points are represented by an
array of objects, not string corresponding to a single UUID.
Refs [UIU-2158](https://issues.folio.org/browse/UIU-2158)
=> UIU-2158 correct proptypes do not generate console warnings

translations/ui-users/en.json
https://issues.folio.org/browse/UIU-2159
Remove unused translation strings, which will be translated in stripes-component now:
_"shortcut.action": "Action",
"shortcut.shortcut": "Shortcut",_
=> UIU-2159: Remove unused translations

CHANGELOG.md, src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js
The `aria-label` for the loan menus' `<IconButton>` trigger was missing.
Refs [UIU-1635](https://issues.folio.org/browse/UIU-1635)
=> UIU-1635 loan action menus have a useful aria-label value

CHANGELOG.md, src/settings/permissions/PermissionSetForm.js
https://issues.folio.org/browse/UIU-1630
**Acceptance Criteria**
Given I create a permission set
When I click Add permissions to view the Add permissions modal
Then show me permissions sets that have been created along with individual permissions
Given I am assigning permissions to a permission set B in Settings
When I select permission set A on the Add permissions modal
Then permission set A is now assigned to permission set B
=> UIU-1630: Allow assign permission set

CHANGELOG.md, src/settings/permissions/PermissionSetForm.js
https://issues.folio.org/browse/UIU-2164
**Description**
At users settings - Permission sets - select a permission - Edit permission - Add permission:
The "Select Permissions" modal should be expanded for filter **Permissions types** with the values _Permission sets_ and _Permissions_.
=> UIU-2164: Add permissiions type fiter

src/components/Accounts/ChargeFeeFine/FeeFineInfo.js, src/settings/CommentRequiredForm.js, src/settings/ConditionsSettings.js, src/settings/patronBlocks/BlockTemplates/BlockTemplates.js
Man oh man what a PITA `react-intl` `v5` is when it comes to
render-props. Sheesh. Fix that shiz mainly by using `injectIntl` and
`formatMessage` to get strings where they are necessary; it's so much
cleaner and easier to follow than the render-props.
And sync other prop-types that have drifted out of sync and are now
causing console pollution.
Refs [UIU-2158](https://issues.folio.org/browse/UIU-2158)
=> UIU-2158 use correct prop-types

jest.config.js, package.json, src/components/ReportModals/CashDrawerReportModal.test.js, src/components/UserDetailSections/UserAccounts/UserAccounts.js, test/jest/__mock__/stripesComponents.mock.js
Spacing!
Mock the stripes-COMPONENTS like an ADULT
INSTALL PACKAGES!
[LINT ALL THE THINGS!](http://hyperboleandahalf.blogspot.com/2010/06/this-is-why-ill-never-be-adult.html)
If anybody has better idea about how we can destructure props in the mocks to avoid misapplying them as HTML element attributes, I'm all ears. We need to pull out `dismissible` to avoid this one: 
```
console.error
Warning: Received `true` for a non-boolean attribute `dismissible`.
If you want to write it to the DOM, pass a string instead: dismissible="true" or dismissible={value.toString()}.
in div (created by mockConstructor)
in mockConstructor (created by CashDrawerReportModal)
in CashDrawerReportModal
in Unknown (created by ReactFinalForm)
in ReactFinalForm (created by Context.Consumer)
in StripesFinalFormWrapper …
```
=> test cleanup; lint cleanup

src/views/UserEdit/UserEdit.js
`EditExtendedInfo` expects certain attributes to be present, even if
empty.
Refs [UIU-2172](https://issues.folio.org/browse/UIU-2172)
=> UIU-2172 correctly initialize new user initialValues

src/customTypeValidators.js
When a prop is not passed at all, its value will be `undefined`, not
`null`. Such a value should be acceptable to this validator.
Refs [UIU-2171](https://issues.folio.org/browse/UIU-2171)
=> UIU-2171 correctly handle undefined in nullOrStringIsRequiredTypeValidator

src/components/Accounts/ViewFeesFines/ViewFeesFines.js, src/views/AccountDetails/AccountDetails.js, test/bigtest/network/scenarios/fee-fine-details.js, test/bigtest/network/scenarios/view-fees-fines.js, test/bigtest/tests/fee-fine-details-test.js, test/bigtest/tests/fee-fine-history-test.js, translations/ui-users/en.json, translations/ui-users/en_US.json
If a fee/fine is associated with a loan, but the loan has been scrubbed (i.e. no longer exists) change the Loan details 'View' link value in Fee/Fine Details to text 'Anonymized'.
https://issues.folio.org/browse/UIU-1840
Related to https://github.com/folio-org/ui-users/pull/1757
=> UIU-1840: Change Fee/Fine Details 'Loan details' from 'View' link to 'Anonymized' text if associated loan has been scrubbed

CHANGELOG.md, src/components/ReportModals/CashDrawerReportModal.js, src/components/ReportModals/CashDrawerReportModal.test.js
Fix validation error with `END DATE` for` Cash drawer reconciliation report` modal
Fix problem with `END DATE`
Add tests for validation
Remove default value for format (`options.format = 'both'`) that we already sent it in `initialValues`.
https://issues.folio.org/browse/UIU-2175
=> UIU-2175: Fix validation error with END DATE for Cash drawer reconciliation report modal

CHANGELOG.md, src/components/data/reports/cashDrawerReconciliationReportCSV.js, src/components/data/reports/cashDrawerReconciliationReportCSV.test.js, test/jest/__mock__/cashDrawerReconciliationReportEmptyData.mock.js
An empty data array would cause an NPE in `parse()` because it did not
validate the return value from `buildReport()`.
Refs [UIU-2184](https://issues.folio.org/browse/UIU-2184)
=> UIU-2184 CashDrawerReconciliationReportCSV should handle empty data

CHANGELOG.md, package.json, test/jest/babel.config.js
The jest babel config needs to be updated to handle the new JSX
transform, among other tweaks.
Refs [UIU-2190](https://issues.folio.org/browse/UIU-2190), [STRIPES-757](https://issues.folio.org/browse/STRIPES-757)
=> UIU-2190 correctly configure babel

CHANGELOG.md, src/routes/UserRecordContainer.js
https://issues.folio.org/browse/UIU-2191
Steps to Reproduce:
Select a user
Expected Results:
User details should be loaded without fetching data of resource 'delUser'.
Actual Results:
ERROR: in module @folio/users, operation GET on resource 'delUser' failed, saying: Index 0 out of bounds for length 0.
=> UIU-2191: Prevent fetching delUser

CHANGELOG.md, src/views/UserDetail/UserDetail.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-2193
Given a staff person selects "check for open transactions/delete user,"
the user does not have any open transactions and the staff person confirms to delete the user.
Then the system does delete the user.
**To be added:**
This deletion process should create a confirmation toast message in the lower right corner of the screen:
IF the deletion was successful:
Green message: "User **[last name], [first name]** deleted successfully."
else
Red message: "User **[last name], [first name]** could not be deleted." OR any other more detailed error message that already be implemented.
=> UIU-2193: Delete user confirmation message

CHANGELOG.md, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-2192
**Current situation:**
Given a staff person selects "check for open transactions/delete user,"
and the user does not have any open transactions
then the pop up currently says: 
"Are you sure you want to delete this user [last name], [first name]?
Yes No"
**This should be changed to:**
"No open transactions for user [last name], [first name].
Are you sure you want to delete this user?
Yes No"
=> UIU-2192: Change text for no open transactions

CHANGELOG.md, src/routes/UserDetailContainer.js, src/routes/UserRecordContainer.js
https://issues.folio.org/browse/UIU-2183
The `key` is required in order to unmount / mount `UserRecordContainer` when switching between users.
The remounting together with `resourceShouldRefresh` will trigger refresh for permissions endpoint.
=> UIU-2183: Add resourceShouldRefresh to permissions resource to refresh permissions 

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js
Shared manual fees/fines not showing up for new fee/fine owner.
Fee/fine types should be populated with the 6 Shared fee/fine types.
https://issues.folio.org/browse/UIU-2208
**Before**
**After**
=> UIU-2208: Shared manual fees/fines not showing up for new fee/fine owner

CHANGELOG.md, src/views/UserEdit/UserEdit.js
An empty username is causing an error on the server. This PR removes it from the POST request.
https://issues.folio.org/browse/UIU-2214
=> UIU-2214: Omit empty username during user creation

src/settings/sections.js
Reverts folio-org/ui-users#1797
Misunderstood where this wrt approval
=> Revert "Removed Profile Picture settings"

CHANGELOG.md, src/routes/AccountDetailsContainer.js, src/routes/AccountsListingContainer.js, src/routes/feeFineConfig.js, src/views/AccountDetails/AccountDetails.js
Fix `Total owed amount`/`Total paid amount` on `Fee/Fine Details`. Refs UIU-2211.
1. File AccountsListingContainer.js 
- Moved reusable part (filterConfig, queryFunction, args) form AccountDetailsContainer.js to  feeFineConfig.js
- Changed hardcode 10000 to MAX_RECORDS 
2. File AccountDetailsContainer.js
- Added feefineshistory and all necessary changes for use it (we add it in the same way that we use it in AccountDetailsContainer.js)
- Changed hardcode 10000 to MAX_RECORDS 
3. File feeFineConfig.js
- Reusable part (filterConfig, queryFunction, args) was moved from AccountsListingContainer.js  without any code changes
4. File AccountDetails.js
- Was added all necessary changes for calculate Total owed amount and Total paid amount
- Calculation for balance was implemented in the similar …
=> UIU-2211: Fix Total owed amount/Total paid amount on Fee/Fine Details

CHANGELOG.md, src/components/Loans/OpenLoans/components/BulkClaimReturnedModal/BulkClaimReturnedModal.js, src/components/ModalContent/ModalContent.js
Additional information in loan-action forms is a required field;
whitespace alone should not be acceptable as valid.
Refs [UIU-2227](https://issues.folio.org/browse/UIU-2227)
=> UIU-2227 whitespace should not make loan-action forms dirty

CHANGELOG.md, src/components/Accounts/Actions/FeeFineActions.js
We should show "Notify patron" in three ways
The transfer of a single fee/fine may be executed in three different ways:
1. Using the TRANSFER button in Fee/Fine Details.
2. Using the TRANSFER option in the ellipsis menu in Fees/Fines History.
3. Using the TRANSFER button in Fees/Fines History after putting a check mark in the box for a single fee/fine.
We have inconsistency behavior in case 3.
After discussing this issue with "PO", we should fix this issue as follows:
1. We must have consistent behavior in all 3 cases.
2. We must have the same behavior as we have on "iris"
3. If we will need provide any changes in behavior for "Notify patron" we should provide them in separate story/task.
https://issues.folio.org/browse/UIU-2215
=> UIU-2215: Default notice not sent to patron when Transfer done in one of the three ways

CHANGELOG.md, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/Loans/OpenLoans/components/OpenLoansSubHeader/OpenLoansSubHeader.js, src/components/Loans/OpenLoans/components/OpenLoansWithStaticData/OpenLoansWithStaticData.js, src/components/Loans/OpenLoans/helpers/getListDataFormatter.js, src/components/util/util.js, src/components/util/util.test.js, src/views/LoanDetails/LoanDetails.js
https://issues.folio.org/browse/UIU-2229
When loading the loan detail or loan history views, this checks the user record to see whether the `active` flag is set and the expiration date hasn't expired yet (which is probably redundant).
=> UIU-2229: Disable renewals for inactive users

src/views/UserDetail/UserDetail.js
I botched the original cherry-pick, bringing in some changes from #1768
that were not part of the `v6.1` tree. Removing that extra code resolves
those errors.
Refs UIU-2212
=> UIU-2212 correctly handle UserDetail merge

CHANGELOG.md, src/components/util/util.js
`Financial transactions detail report:` date with empty value columns says "Unix Epoch"
https://issues.folio.org/browse/UIU-2239
**Before**
**After**
=> UIU-2239: Handle empty date

CHANGELOG.md, src/components/util/refundTransferClaimReturned.js
https://issues.folio.org/browse/UIU-2228
`babel-plugin-lodash` currently complains about lodash using chain sequences. 
This PR refactors it to use `flow` instead.
More info:
https://medium.com/bootstart/why-using-chain-is-a-mistake-9bc1f80d51ba
We need this in place in order to finalize work on https://issues.folio.org/browse/STRWEB-20
=>  UIU-2228: Make sure users module builds with babel-plugin-lodash present

CHANGELOG.md, src/components/Loans/OpenLoans/OpenLoansControl.js, src/components/data/reports/CsvReport.js, src/views/UserSearch/UserSearch.js
https://issues.folio.org/browse/UIU-2224
Overdue loans report included dates in UTC rather than local time. This PR is trying to address it and use local time instead.
=> UIU-2224: Show dates in local time when generating CSV reports

src/settings/sections.js
Reverts folio-org/ui-users#1804
I've always wanted to revert a revert! Last day on the project seems like a good time to do it. 😄 
(This is now approved by the UM SIG so we can finally get rid of this silly useless setting.)
=> Revert "Revert "Removed Profile Picture settings""

CHANGELOG.md, src/components/data/reports/FinancialTransactionsReport.js, src/components/data/reports/financialTransactionsReportHelpers.js, src/components/data/reports/financialTransactionsReportHelpers.test.js
Fix hyperlink in Financial transactions detail report
We should not render hyperlink for "Item Barcode", "Loan Policy", "Overdue Policy", "Lost Item Policy", "Loan Details" when we don't have all necessary data.
https://issues.folio.org/browse/UIU-2217
=> UIU-2217: Fix hyperlink in Financial transactions detail report

CHANGELOG.md, src/components/data/reports/FinancialTransactionsReport.js, src/components/data/reports/financialTransactionsReportHelpers.js, src/components/data/reports/financialTransactionsReportHelpers.test.js, translations/ui-users/en.json
Fix hyperlink with missing `Patron barcode`
We should not render hyperlink for `Patron barcode` when we don't have all necessary data.
We should render `Patron barcode` hyperlink with `no barcode` label when Patron don't have barcode.
https://issues.folio.org/browse/UIU-2242
=> UIU-2242: Fix hyperlink with missing `Patron barcode`

CHANGELOG.md, src/components/data/reports/FinancialTransactionsReport.js
Fix `Invalid date` for `Financial transaction detail report`
We get date from BE already formatted or empty string and we need render it as is
https://issues.folio.org/browse/UIU-2251
=> UIU-2251: Fix Invalid date for Financial transaction detail report

CHANGELOG.md, package.json
Support `feesfines` interface version `17.0`
We should merge all associated task with https://issues.folio.org/browse/MODFEE-98 in the same time. In scope of https://issues.folio.org/browse/MODFEE-98 was added the standard UUID regular expression pattern to all the id fields in the Fees/Fines module JSON schemas. All changes was tested in scope https://issues.folio.org/browse/MODFEE-197.
https://issues.folio.org/browse/UIU-2248
@zburke @mkuklis  Could you please clarify do we need to add someone else for review this task?
=> UIU-2248: Support `feesfines` interface version `17.0`

.github/workflows/buildnpm.yml
It appears a test-value was left in place, leading build artifacts to be
published in the wrong places.
Refs [FOLIO-3279](https://issues.folio.org/browse/FOLIO-3279)
=> FOLIO-3279 correctly configure npm registry

src/components/util/util.js, src/components/util/util.test.js
Array validation functions must handle null input, not just empty array
input. Sloppy, @zburke, sloppy 😠 
Refs [UIU-2434](https://issues.folio.org/browse/UIU-2434)
=> UIU-2434 array validation must handle null input

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeForm.js, test/bigtest/tests/charge-fee-fine-test.js
There are now  is displaying the automated fee/fine types when you create a new fee/fine.  But we cannot have users creating manual fees/fines using the automated fee/fine types. So let's check if `fee/fine type` is automatic when we form `feefineList`.
https://issues.folio.org/browse/UIU-2411
**Before**
**After**
=> UIU-2411: Automatic fees/fines are appearing in New Fee/Fine "Fee/fine type" drop-down

CHANGELOG.md, package.json
https://issues.folio.org/browse/UIU-2247
Permission set `ui-users.settings.profilePictures` is not used anymore (it also had a wrong `displayName` which was confusing).
=> UIU-2247: Remove unused permission set

src/components/util/util.js, src/components/util/util.test.js
lodash's `every` implementation handles any of its collection types,
including objects (which iterate their values), not just arrays.
Restoring the more flexible lodash implementation, rather than writing
an increasingly complex vanilla JS implementation, seems like the right
approach here.
Refs [UIU-2434](https://issues.folio.org/browse/UIU-2434)
=> UIU-2434 restore lodash implementation of collection.every

package.json
https://issues.folio.org/browse/UIU-2244
This PR moves permissions
````
circulation-storage.request-preferences.item.post 
circulation-storage.request-preferences.item.put 
````
under correct permission set `ui-users.edit` based on the feedback from Brooks Travis.
=> UIU-2244: Move permissions under correct perm set

src/routes/UserRecordContainer.js
https://issues.folio.org/browse/UIU-2244
The refresh was still not happening because `resourceShouldRefresh` was defined under wrong place. 
stripes-connect checks it only on the top level of each resource:
https://github.com/folio-org/stripes-connect/blob/master/RESTResource/RESTResource.js#L522
=> UIU-2244: Move resourceShouldRefresh under correct place

package.json
There was a typo in the compiled translation path. h/t
@aditya-matukumalli
=> use correct path for compiled translation output

CHANGELOG.md, src/components/EditSections/EditUserInfo/EditUserInfo.js
It's possible to create a minimal user object at the `/users` endpoint,
e.g. a POST request with a username field and nothing else, but editing
such a record in the UI fails because fields the UI requires (though the
backend does not) are missing.
Provide default value (`"false"`) for the `active` field when it is
missing.
Refs [UIU-2435](https://issues.folio.org/browse/UIU-2435)
=> UIU-2435 don't choke when editing minimal user

CHANGELOG.md, src/settings/LimitsSettings.js
Keep existing formating of "Patron groups" names on "Limits" tab.
https://issues.folio.org/browse/UIU-1763
Name of created "Patrong group":
Before:
After:
=> UIU-1763: fix issue when `Patron groups` and `Limits` have diferent name formating

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/util/util.js, src/components/util/util.test.js, src/routes/AccountDetailsContainer.js, src/views/AccountDetails/AccountDetails.js
We should additionaly send `contributors` filed when we create fee/fine record.
We should also display contributors from fee/fine record.
When we display `contributors` on fee/fine details page, we should in first order display contributors from fee/fine record. If there are no contributors in fee/fine record, we should display them from instance record. If contributors absent at all, we should display '`-`'.
This approach was discussed here https://issues.folio.org/browse/UIU-2092?focusedCommentId=111003&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-111003
Function `getContributors` was extracted in `util` to be able to test it..
Initialy it was in `AccountDetailsContainer`. But when I try to export it and test it separately, I am faced with the inability …
=> UIU-2203: Add Contributors field to account request

CHANGELOG.md, src/components/Accounts/Actions/FeeFineActions.js, src/components/Accounts/Actions/WarningModal.js, src/components/Accounts/Menu.js, src/components/Accounts/ViewFeesFines/ViewFeesFines.js, src/components/Accounts/accountFunctions.js, src/components/util/index.js, src/components/util/isRefundAllowed.js, src/components/util/isRefundAllowed.test.js, src/views/AccountDetails/AccountDetails.js
Fix issue when `refund` button became inactive before the user was returned entire amount of money.
We should not more rely on `refundStatuses` when define should `refund` button be active or not. This was discussed with PO here https://issues.folio.org/browse/UIU-2438?focusedCommentId=111858&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-111858.
The `hasBeenFullyRefunded` function was deleted as unnecessary.
In the `isRefundAllowed` function the `isAccountRefunded` flag is calculating rely on  `calculateSelectedAmount` function now.
Also `isRefundAllowed` function was extracted into utils for two reasons:
- we use it in many places, so i think utils is the right place;
- extraction gives us the opportunity to test this function more comfortably by using …
=> UIU-2438: fix `refund` button issue

CHANGELOG.md, src/components/util/util.js, src/components/util/util.test.js
Display `contributors name` consistent with other modules.
https://issues.folio.org/browse/UIU-2440
=> UIU-2440: Display `contributors name` consistent with other modules.

CHANGELOG.md, src/components/Wrappers/withMarkAsMissing.test.js
Create Jest/RTL test for `withMarkAsMissing`.
https://issues.folio.org/browse/UIU-2265
=> UIU-2265: Create Jest/RTL test for withMarkAsMissing.

CHANGELOG.md, src/views/LoanDetails/LoanDetails.js
This was subtle. In JSX, `<>{value}</>` returns a component, but in
plain ol' JS, `{value}` returns an object. Here, we need either a
component or a primitive, but we got an object. Whoops.
Introduced in #1613.
Refs [UIU-2446](https://issues.folio.org/browse/UIU-2446)
=> UIU-2446 correctly show fee/fine to unprivileged user

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
We don't run the BigTest workflows any longer so there is no value in
reporting the results of the test we didn't run. :laugh:
=> disable BigTest workflows and reports

test/jest/babel.config.js, test/jest/helpers/renderWithRouter.js
Test scaffolding has been evolving rapidly. It appears that some feature
relies on test scaffolding (`renderWithRouter`) that was added in a
separate PR.
=> include jest helper renderWithRouter.js

.eslintrc
`.eslintrc` needs to have the know about the aliases in use in test
files, otherwise it will complain about paths it can't handle.
=> eslint config should reflect test aliases

CHANGELOG.md, src/index.js
The `<Route>` components accepts both `components` and a render-props
function to determine the component to render, but only one should be
provided. Here, both were provided, but only one (the render-props)
includes the necessary permissions check. This PR removes the former.
Refs [UIU-2474](https://issues.folio.org/browse/UIU-2474)
=> UIU-2474 correctly check permissions on accounts routes

test/jest/__mock__/stripesCore.mock.js
Many components import `stripesShape` from `@folio/stripes/core` and
hence throw warnings under test if the mock doesn't match that shape.
Now, the mock matches that shape.
=> elaborate stripes-core mock matches stripesShape

src/settings/permissions/PermissionSetForm.js
`ariaLabel` must be a string but `<FormattedMessage>` render props
passes an array.
Refs [UIU-2475](https://issues.folio.org/browse/UIU-2475), [STRIPES-694](https://issues.folio.org/browse/STRIPES-694)
=> UIU-2475 ariaLabel must be a string

src/settings/LimitsSettings.test.js
`resources` shape is required; an empty object is not sufficient.
=> correctly mock props

CHANGELOG.md, src/routes/UserSearchContainer.js
Search hidden fields along with all the other fields. This is not
_exactly_ what UIU-2165 asked for (which was a drop-down menu with
different options, similar to the different search options in
ui-inventory) but this was the simplest possible implementation, so I
just went for it (with Patty's blessing). 
Refs [UIU-2165](https://issues.folio.org/browse/UIU-2165)
=> UIU-2165 search hidden fields

package.json, src/routes/AccountDetailsContainer.js, src/views/AccountDetails/AccountDetails.js
Permission to view fees and fines no longer includes any permissions
associated with viewing loans.
See discussion under [UICIRC-693](https://issues.folio.org/browse/UICIRC-693?focusedCommentId=116650&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-116650)
Refs [UIU-2472](https://issues.folio.org/browse/UIU-2472)
=> UIU-2472 view fees/fines does not include view loans

package.json, translations/ui-users/en.json, translations/ui-users/en_GB.json, translations/ui-users/en_SE.json, translations/ui-users/en_US.json
At the request of the RA SIG, permission to view fees and fines should
include permission to view loans.
(Including translation file updates here because I expect this PR to be cherry-picked into a patch release and there is a high probability of that happening before translations are updated.)
Refs [UIU-2472](https://issues.folio.org/browse/UIU-2472)
=> UIU-2472 view-fees/fines pset includes view-loans

CHANGELOG.md, package.json, src/components/Accounts/Actions/ActionModal.js, src/components/Accounts/Actions/CancellationModal.js, src/components/Accounts/Actions/FeeFineActions.js, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/BulkOverrideDialog/BulkOverrideInfo.js, src/components/BulkRenewalDialog/BulkRenewInfo.js, src/components/EditSections/EditUserInfo/EditUserInfo.js, src/components/LoanActionDialog/LoanActionDialog.js, src/components/Loans/OpenLoans/components/BulkClaimReturnedModal/BulkClaimReturnedModal.js, src/components/ModalContent/ModalContent.js, src/components/ProxyGroup/ProxyEditList/ProxyEditList.js, src/components/Wrappers/withRenew.js, src/settings/patronBlocks/Conditions/Conditions.js, src/settings/patronBlocks/Limits/Limits.js
`<SafeHTMLMessage>` is deprecated and its features subsumed by
`react-intl` as of `v5`.
Refs [UIU-2179](https://issues.folio.org/browse/UIU-2179), [STRIPES-754](https://issues.folio.org/browse/STRIPES-754)
=> UIU-2179 refactor from SafeHTMLMessage to FormattedMessage

CHANGELOG.md, src/routes/UserSearchContainer.js
Sorting was not working correctly after "Load more" option was used to fetch more data. This PR resets the offset when sort is used so only the first sorted page is loaded. 
https://issues.folio.org/browse/UIU-2466
=> UIU-2466: Reset offset when sort values change

CHANGELOG.md, src/routes/UserSearchContainer.js
https://issues.folio.org/browse/UIU-2490
Only use `history.push` if the url is actually different from the current one.
I noticed this bug when working on lazy loading. The ui-users would just go into infinitive loop and keep re-rendering `UserSearchContainer` reloading all resources. This doesn't happen when everything is bundled into one single module in webpack. It almost seems like a timing issue.
=> UIU-2490: Do not push to history if the url didn't change.

CHANGELOG.md, src/routes/AccountDetailsContainer.js, src/views/AccountDetails/AccountDetails.js
https://issues.folio.org/browse/UIU-2473
In order to get the correct service point name, we need to pull in the full list of service points to match against. As Zak stated in the issue comments, this code was previously trying to match based on the user's assigned service points, which could be just a small subset of the full list of SPs where the fine could have been assigned.
=> UIU-2473: Properly show service point name in fee/fine details

CHANGELOG.md, src/components/EditSections/EditUserInfo/EditUserInfo.js
https://issues.folio.org/browse/UIU-2498
**Overview:** 
With UXPROD-2389, a default expiration date can be filled in when a new user is created, a user is changed from inactive to active, re-set or, the case here, a patron group is changed.
The default expiartion period for the patron group is either added to the current expiration date or the current date. 
In the case of a change of patron group, it should be added to the current date.
**Steps to Reproduce:**
1.     Set default expiration date for a patron group X.
2.     Open a user with a set expiration date.
3.     Change the patron group
**Expected Results:**
The expiration date should be changed to expiration date = today + expiration period.
**Actual Results:**
It is changed to expiration date = current expiration date + …
=> UIU-2498: Fix calcualtion for expiration date

CHANGELOG.md, src/routes/UserRecordContainer.js, src/views/UserDetail/UserDetail.js, src/views/UserDetail/components/ActionMenuEditOption/ActionMenuEditOption.js, src/views/UserDetail/components/ActionMenuEditOption/ActionMenuEditOption.test.js, src/views/UserDetail/components/ActionMenuEditOption/index.js
Suppress edit of users whose IDs are specified in an array stored in mod-configuration. 
Create a configurations entry by sending a POST request to `/configurations/entries` with a body like
```
{
"module": "@folio/users",
"configName": "suppressEdit",
"default": true,
"enabled": true,
"value": "[\"SOME_UUID\", \"OTHER_UUID\"]",
}
```
Users whose UUIDs match array values will not have an "Edit" button when viewing the "Actions" menu from the user-details pane. This is a bit kludgey; all it does is remove the "Edit" button from the Action menu, so a determined user could still directly access the edit screen by manually entering a URL like `/users/SOME_UUID/edit`. I could add a check there too if folks think this needs to be more robust. 
Refs …
=> UIU-2499 suppress edit of some users

CHANGELOG.md, src/components/Accounts/Actions/FeeFineActions.js
Fix unexpected increase of fee/fine remaining balance.
`this.props.balnce` was a overall calculated amount for all user fee/fines.
When we use `New staff info`, we update currnet fee/fine, so overall balance is not what we need.
`account.remaining` - is correct field.
I tested new behaviour with all posible actions - everything looks fine. 
https://issues.folio.org/browse/UIU-2506
Before:
Аfter:
=> UIU-2506: Fix unexpected increase of fee/fine remaining balance

CHANGELOG.md, src/components/EditSections/EditUserInfo/EditUserInfo.js
https://issues.folio.org/browse/UIU-2498
**Overview:** 
With UXPROD-2389, a default expiration date can be filled in when a new user is created, a user is changed from inactive to active, re-set or, the case here, a patron group is changed.
The default expiartion period for the patron group is either added to the current expiration date or the current date. 
In the case of a change of patron group, it should be added to the current date.
**Steps to Reproduce:**
1.  Set default expiration date for a patron group X.
2. Open a user with a set expiration date.
3. Change the patron group
**Expected Results:**
The expiration date should be changed to expiration date = today + expiration period.
**Actual Results:**
It is changed to expiration date = current expiration date + expiration period. …
=> UIU-2498: calculation expiration date

CHANGELOG.md, src/components/Accounts/Actions/FeeFineActions.test.js
Add Jest/RTL tests for `CommentModal` business logic in `FeeFineActions` component
https://issues.folio.org/browse/UIU-2515
Associated with https://github.com/folio-org/ui-users/pull/2019
=> UIU-2515: Add Jest/RTL tests for `CommentModal` business logic in `FeeFineActions` component

CHANGELOG.md, src/components/Wrappers/withRenew.js
Without an explicit `limit` clause, API queries will retrieve only 10
records. This change does not address the latent/potential too-long-query
problem if a patron has loans affiliated with > ~50 policies, but > 50
seems less likely to occur than > 10.
AFAIK, no tenants have hit either limitation in production, but thinking
about [MODUSERS-303](https://issues.folio.org/browse/MODUSERS-303) got me thinking about it.
Refs [UIU-2520](https://issues.folio.org/browse/UIU-2520)
=> UIU-2520 retrieve more than 10 loan policies

CHANGELOG.md, src/components/Wrappers/withProxy.js
Without a `limit` clause, the previous implementation defaulted to only
10 records. It wasn't enough. A more robust implementation would
implement paging, but we may be able to squeak by with 50 as that seems
likely to be the upper bound, and it's certainly a quick-fix.
Refs [UIU-2510](https://issues.folio.org/browse/UIU-2510)
=> UIU-2510 retrieve up to 50 proxies/sponsors

CHANGELOG.md, src/views/UserDetail/UserDetail.js
https://issues.folio.org/browse/UIU-2484
Not much to say about this one; the `location.search` was being lost when edit mode was entered.
=> UIU-2484: Preserve search filters during user edit

CHANGELOG.md, src/components/Loans/OpenLoans/components/OpenLoansWithStaticData/OpenLoansWithStaticData.js, src/components/Loans/OpenLoans/helpers/getListDataFormatter.js, translations/ui-users/en.json
- Open Loans List: Form does not include label.
- Add `aria-label` attribute to `input` elements.
- https://issues.folio.org/browse/UIU-1638
=> UIU-1638: Open Loans List: Form does not include label

CHANGELOG.md, src/views/UserEdit/UserForm.js
Refs https://issues.folio.org/browse/UIU-1695
Approach: don't render empty component when it's redundant
=> UIU-1695 Accessibility: Headings must not be empty

CHANGELOG.md, src/components/PermissionsAccordion/components/PermissionsModal/PermissionsModal.js
https://issues.folio.org/browse/UIU-2486
https://issues.folio.org/browse/UIU-2496
Most of the bugs and weird behaviors around permissions selection and assignment in `<PermissionsModal>` were the result of double-dipping from the `availablePermissions` resource. I've fixed this by adding a new state variable to hold the complete list of permissions; the existing state `permissions` variable actually changes during searches, which was confusing the issue.
I've also fixed another (unreported?) bug: when the modal was opened for a user who already had assigned permissions, none of the assigned perms were checked/selected. Then, unless you carefully re-selected all of the extant assignments before saving, you'd lose the old ones because they weren't selected in the list. (I hadn't realized at …
=> UIU-2496: Fix problems with permissions duplication in PermissionsModal

CHANGELOG.md, src/views/UserSearch/UserSearch.js
- Display preferred name in the search result
- If user has `preferredFirstName` then display `LastName`, `PreferredFirstName` `(FirstName)` `MiddleName` in result list
- if user doesn't have  `preferredFirstName` then display `LastName`, `FirstName` `MiddleName` in result list
- Refs: https://issues.folio.org/browse/UIU-2500
- Refactor `getFullName` function to include `preferredFirstName`
=> UIU-2500: Display preferred name in the search result

CHANGELOG.md, src/components/util/util.js, src/components/util/util.test.js
UIU-2502 - Display preferred name in the top of the edit view of the user record.
When a staff member searches for a user name, and selects a user record, the record header and the large display of the name lists the lastname, first name, and middle name or initial, regardless of whether the patron has selected a preferred first name.
In scope Revise the display to include preferred first name, so the result is Lastname, PreferredFirstName MiddleName
https://issues.folio.org/browse/UIU-2501
https://issues.folio.org/browse/UIU-2502
=> UIU-2501 - Display preferred name in the header and body of the user record.

CHANGELOG.md, src/components/EditSections/EditContactInfo/EditContactInfo.js
- Newly created `address` record should be in focus
- Refs: https://issues.folio.org/browse/UIU-1161
- Add `autoFocus` prop to `Select` component to move focus on it on `mount`
=> UIU-1161: Newly created address record should be in focus

CHANGELOG.md, src/views/LoansListing/LoansListing.js
- Currently when you access the Open/Closed Loans list, the initial focus is outside the page.
- Requirement: initial focus should be on pane header title.
- Refs: https://issues.folio.org/browse/UIU-1257
- Pass `paneTitleRef` prop to `Pane` component to move focus on pane header on `Mount`
=> UIU-1257: Focus should be on pane header title when Loans list is open

src/views/UserEdit/UserEdit.js, src/views/UserEdit/UserEditHelpers.js, src/views/UserEdit/UserEditHelpers.test.js, translations/ui-users/en.json
If a user-edit action such as updating user attributes, changing
permissions, or changing request attributes fails, show an error callout
instead of failing silently.
Refs [UIU-2541](https://issues.folio.org/browse/UIU-2541)
=> UIU-2541 warn if user-edit actions fail

CHANGELOG.md, src/routes/PatronBlockContainer.js
We should be able to edit Manual Patron Blocks.
This issue appears when we have a more than 10 active manual patron blocks. Before changes we fetch them all, find neccesary by id and prefill data from responce. But when we have more than 10 records, and our block doesn't appears in them, there are no any prefilled data. I added patron id to request, and raize records limit. It helped.
https://issues.folio.org/browse/UIU-2548
=> UIU-2548: fix the issue when unable to edit manual patron blocks

CHANGELOG.md, package.json
Thus, users with ui-users.editperms can continue to grant
any permission to any user - except okapi permissions.
=> Include perms.users.assign in ui-users.editperms UIU-2549

CHANGELOG.md, src/components/Accounts/Actions/WarningModal.js, src/components/Accounts/ViewFeesFines/ViewFeesFines.js
https://issues.folio.org/browse/UIU-2543
This PR replaces `onChange` with `onClick` so the events are correctly propagated. The `onChange` is currently not working correctly because MCL is stopping the propagation:
https://github.com/folio-org/stripes-components/blob/08fa633f7660869bc1a29c0f13d80deba62afc80/lib/MultiColumnList/MCLRenderer.js#L833-L834
=> UIU-2543: Replace onChange with onClick when checkbox is clicked on MCL row.

CHANGELOG.md, src/routes/AccountDetailsContainer.js
https://issues.folio.org/browse/UIU-2544
The limit was set incorrectly and only first 10 service points were returned which was causing issues with not finding correct one on the `AccountDetailsContainer` under `Create at` column:
=> UIU-2544: Increase limit for servicePoints query in AccountDetailsContainer

CHANGELOG.md, package.json
The ui-users package.json file doesn't declare a dependency on the tags interface.  When opening up the users app, you can clearly see a call being made to GET /tags in the browser tools.  It appears this call is made in order to populate the tags filter drop-down.
Missing interface dependency has been added into the okapiInterfaces
=> UIU-2557 - Missing interface dependency: tags

CHANGELOG.md, src/components/Accounts/Actions/CommentModal.js
Error message "Enter comment" appears erroneously when entering New Staff Info on Fee/Fine Details.
Form was reseting before component fully unmout, that why we was able to see error message. With flag `destroyOnUnregister` we no more need to reset form manualy. This resolve first part of the issue. The second problem that when we type something, and than delete and try to click on cancel, in first turn works validation on blure, button runs away from under our cursor and we should click on it one more time to close the window. Regarding this I think we can remove our validation, because we can't save empty message with or without validation.
https://issues.folio.org/browse/UIU-2569
=> UIU-2569: fix error message appearing

CHANGELOG.md, package.json
Prior to `permissions` `5.5`, having `perms.users.items.put`, `...post`,
or `...delete` was a security vulnerability because it allowed any user
with the ability to assign permissions to assign permissions they did
not already have, e.g. for a user with `A` and `B` to grant `C` to
somebody else. That _is_ a useful feature, but the two should not be
coupled (assign own permissions; assign non-owned permissions).
Here, that same logic is applied to creation of permission sets: users
with the ability to create permission sets need the ability to create
sets with permissions they may not own.
Refs [UIU-2563](https://issues.folio.org/browse/UIU-2563)
=> UIU-2563 users manipulating psets need permission to do so

CHANGELOG.md, src/components/Wrappers/withRenew.js
https://issues.folio.org/browse/UIU-2570
https://issues.folio.org/browse/UIU-2574
This fixes a couple of related bugs in which the number of open requests on a loaned item would never show more than 1 request. This only required an adjustment to the `limit` parameter for the query.
=> UIU-2570: Fix inaccurate request counts in various open loan views & modals

CHANGELOG.md, src/settings/patronBlocks/BlockTemplates/BlockTemplates.js
https://issues.folio.org/browse/UIU-2577
**Steps to Reproduce:**
1. Go to Settings- users - Patron blocks: Templates
2. Create more than 10 templates
**Expected Results:**
All templates should be visible in Patron blocks: Templates
**Actual Results:**
Just 10 templates are visible in Patron blocks: Templates
**Additional Information:**
URL: settings/users/manual-block-templates
=> UIU-2577: Increase record limit for manual-block-templates

package.json
Manipulating run-time (mutable) sets composed of build-time (immutable)
permissions requires (drumroll) permission to manage immutable
permissions.
Refs [UIU-2563](https://issues.folio.org/browse/UIU-2563)
=> UIU-2563 immutable permission is necessary to manipulate sets

CHANGELOG.md, package.json
Many fee/fines settings permission sets were missing a permission or
two.
Refs [UIU-2572](https://issues.folio.org/browse/UIU-2572)
=> UIU-2572 include missing fee/fine settings permissions

CHANGELOG.md, src/views/UserSearch/UserSearch.js
Search results with a single hit should automatically open the detail view
Added a code-block inside SearchAndSort.js file which is checking if showSingleResult behaviour is true and total results are 1. This code-block is calling onSelectRow function which is responsible for opening the detail pane.
[UIU-2601](https://issues.folio.org/browse/UIU-2601)
https://user-images.githubusercontent.com/101391438/167606090-903e500c-b934-41c3-b321-adaff0486b03.mp4
=> UIU-2601 Search results with a single hit should automatically open the detail view

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeForm.js, src/components/Accounts/ChargeFeeFine/FeeFineInfo.js
Fix the issue when fee/fine amount unexpectedly resets on manual charge form.
1. We dont need `this.amount` at all, because final form should handle changing of values by it self.
2. Also I deleted `async ... await` from `onChangeFeeFine` because we don't need to wait `setState`. I rechecked the bug that was fixed by this construction [(in this pull)](https://github.com/folio-org/ui-users/pull/1571) - works fine.
3. `onChangeFeeFine` in `onChangeAmount` was not working at all because instead of `event` amount was passed, and if no `e?.target?.value` than nothing happend.
https://issues.folio.org/browse/UIU-2600
=> UIU-2600: fix the issue when fee/fine amount unexpectedly resets on manual charge form

CHANGELOG.md, src/views/LoanDetails/LoanDetails.js
Get rid of console error if there is no renewals.
[UIU-2603](https://issues.folio.org/browse/UIU-2603)
[e2e tests related PR](https://github.com/folio-org/stripes-testing/pull/410) - should be merged after merging of current PR
**BEFORE**
**AFTER**
=> UIU-2603: "Cannot read properties of undefined (reading 'replace')" after Renew of user loan

CHANGELOG.md, src/components/UserDetailSections/UserLoans/UserLoans.js
The open-loan count on the "Loans" accordion could be inaccurate when
there were more than 1000 loans because it used a `limit=1` query
parameter (which still allows for an [estimated `totalRecords` value](https://github.com/folio-org/raml-module-builder#estimated-totalrecords))
instead of `limit=0` which forces an accurate count.
Display the badge value on the closed accordion with `<FormattedNumber>`
so it will be correctly formatted when the value is > 999.
Refs [UIU-2631](https://issues.folio.org/browse/UIU-2631)
=> UIU-2631 accurately count loans > 1000

CHANGELOG.md, src/components/Accounts/Actions/ActionModal.js
"Remaining amount" field had an incorrect value when payment/waive/transfer/refund amount is empty. 
[UIU-2644](https://issues.folio.org/browse/UIU-2644)
=> UIU-2644: "Remaining amount" doesn't have the correct value when the field "Payment amount" is emptied

CHANGELOG.md, package.json
`mod-notes` module was updated with breaking changes to `/note-types` endpoint and updated interface version to `3.0`
However, these changes don't affect `/notes` endpoint so `ui-users` can safely use either `2.0` or `3.0`
@zburke should I add anyone else to reviewers?
=> UIU-2647 Support notes interface v3.0

src/components/ModalContent/ModalContent.js, src/views/LoanDetails/LoanDetails.js
Return back `defaultProps` because in some cases components do not receive `toggleButton` prop.
[UIU-2645](https://issues.folio.org/browse/UIU-2645)
Related PR - https://github.com/folio-org/ui-users/pull/2198
=> UIU-2645: Confirm button is not disabled after the click and each click on this button sends the request to the server

CHANGELOG.md, src/components/util/util.js, src/components/util/util.test.js
When formatting a name object where some values could be present but
empty, treat such values as empty. Previously, the formatter only
checked if values were null or undefined; empty-string was ignored. This
led objects like
```
{
firstName: "Andrea",
preferredFirstName: "",
lastName: "Andromeda"
}
```
to be formatted as "Andromeda" instead of "Andromeda, Andrea" because
`preferredFirstName` was non-null. Now, undefined, null, and empty
string will all be treated as falsy.
Refs [UIU-2610](https://issues.folio.org/browse/UIU-2610)
=> UIU-2610 treat empty-string values as null in name-format

src/components/EditSections/EditUserInfo/EditUserInfo.test.js
Due to the incorrectly implemented mocked date, we have failed test after 2022-08-16.
2022-08-16 date was hardcoded and if the test is executed after this date - it fails.
The mocked date should always be in the future.
Next day date was used for mocks. 
As a result, we have an expiration date which is always the next day.
[UIU-2668](https://issues.folio.org/browse/UIU-2668)
=> Fix failed test

CHANGELOG.md, src/views/AccountDetails/AccountDetails.js
Import from paths within `@folio/stripes`, which is provided at the
platform level, instead of directly from `@folio/stripes-core`, which is
not visible at the platform level.
Refs [UIU-2642](https://issues.folio.org/browse/UIU-2642)
=> UIU-2642 correctly import from @folio/stripes/core

CHANGELOG.md, src/settings/FeeFineSettings.js
We had an issue with error messages which happen because we do not clear the local state of `EditableListForm` component.
Using `shouldReinitialize` property we will clear it.
[UIU-2670](https://issues.folio.org/browse/UIU-2670)
[Related story PR #1286](https://github.com/folio-org/stripes-smart-components/pull/1286)
=> UIU-2670: Duplicate Fee/Fine Type error message not being cleared after error corrected

CHANGELOG.md, src/components/data/reports/FeeFineReport.js
Fix broken link to item in export fees fines report
When we have all necessary data we render link 
When we have barcode with out other data, this mean that we can't find and navigate to item and we notify about that
Constant for empty value was added
https://issues.folio.org/browse/UIU-2540
=> UIU-2540: Fix broken link to item in export fees fines report

src/components/Accounts/Menu.js, src/components/Accounts/Menu.test.js, src/views/AccountsListing/AccountsListing.js, src/views/AccountsListing/AccountsListing.test.js
The original work done in: https://github.com/folio-org/ui-users/pull/2259
[UIU-2673](https://issues.folio.org/browse/UIU-2673) Change Fees/Fines History to use an ACTIONS menu instead of buttons
=> UIU-2673: Change Fees/Fines History to use an ACTIONS menu instead of buttons

CHANGELOG.md, src/views/UserEdit/UserForm.js
https://issues.folio.org/browse/UIU-2697
This PR removed password validation from `UserForm`. The password field is no longer accessible from the form.
=> UIU-2697: Remove password validation from UserForm

src/views/UserEdit/UserForm.js, src/views/UserEdit/UserForm.test.js, test/jest/__mock__/stripesComponents.mock.js
Test validation function. I couldn't get the component to render :/
Refs [UIU-2430](https://issues.folio.org/browse/UIU-2430)
=> UIU-2430 test UserForm

src/components/Wrappers/withClaimReturned.js
Disable 'Claimed return' button after click to prevent multiple submissions.
Remove unused variables for remove possible get side effect
https://issues.folio.org/browse/UIU-2732
=> UIU-2732: Disable 'Claimed return' button after click to prevent multiple submissions

CHANGELOG.md, src/routes/AccountsListingContainer.js
Fix problem with Fee/Fine list loading
When we trying to open Fee/Fine list we don't get it.
This problem do not reproduce (or do not reproduce often) when we open Fee/Fine list from user page.
This problem reproduced when we refresh page or copy/past link to Fee/Fine list.
With `recordsRequired: '%{activeRecord.records}'`, we get in response (`resources.feefineshistory`) `hasLoaded : false` when we refresh page.
https://issues.folio.org/browse/UIU-2735
Do not merge until discussion will be finished and we will have full understanding for best approach for fix this bug.
Hello @zburke , @mkuklis , @JohnC-80 , @artem-blazhko I don't see any necessity in `recordsRequired` in `manifest`. Could you please correct me if i am wrong? Could you please describe your opinion about current pull for …
=> UIU-2735: Fix problem with Fee/Fine list loading

CHANGELOG.md, src/components/ModalContent/ModalContent.js, src/components/ModalContent/ModalContent.test.js, src/components/Wrappers/withDeclareLost.js, src/components/Wrappers/withDeclareLost.test.js, src/views/LoanDetails/LoanDetails.js
Refactor code for disable 'Declare lost' button after click to prevent multiple submissions.
UIU-2372 introduced a generic isInProgress prop which should be used in lieu of props like claimedReturnInProgress or declarationInProgress that pollute this generic component with business logic they don't need to know about.
https://issues.folio.org/browse/UIU-2736
=> UIU-2736: Refactor code for disable 'Declare lost' button after click to prevent multiple submissions

test/jest/__mock__/stripesCore.mock.js
* Correct the `okapi` value (it's a string, not an object).
* Replace no-op functions with `jest.fn()` to allow for instrumentation.
* Add `refreshRemote` to `connect` since it's part of `stripesShape` and thus illicits a prop-types warning when missing.
=> include better test infrastructure

yarn.lock
Upgrading yarn.lock upgrades decode-uri-component from 0.2.0 to 0.2.2 fixing Denial of Service (DoS):
https://nvd.nist.gov/vuln/detail/CVE-2022-38900
For production not this yarn.lock file but the platform yarn.lock file is used. However, the builds from this repository should contain the fixed decode-uri-component version so that any side-effects pop up early and we can be sure that ui-users is ready to use the fixed decode-uri-component version.
=> UIU-2750: Upgrade yarn.lock fixing decode-uri-component DoS CVE

CHANGELOG.md, src/settings/patronBlocks/Conditions/Conditions.test.js, src/settings/patronBlocks/Conditions/ConditionsForm.js
In Settings > Users > Patron Blocks > Conditions, mark "Message to be displayed" as required
Refs: [UIU-2487](https://issues.folio.org/browse/UIU-2487)
=> UIU-2487: In Settings > Users > Patron Blocks > Conditions, mark "Message to be displayed" as required

.github/dependabot.yml, CHANGELOG.md
Enable dependabot. This is a POC. This is only a POC. If this turns out to be overwhelming, we'll turn it off.
See https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates for configuration options, including ignoring certain libraries and automatically tagging certain contributors for review, among many other options.
Refs [UIU-2747](https://issues.folio.org/browse/UIU-2747), [FOLIO-3664](https://issues.folio.org/browse/FOLIO-3664)
=> UIU-2747 enable dependabot

CHANGELOG.md, src/views/UserDetail/UserDetail.js
https://issues.folio.org/browse/UIU-2765
Add support for `request-storage` 5.0 around `UserRequests`.
=> UIU-2765: Add support for request-storage 5.0 around UserRequests

src/components/Accounts/Actions/CancellationModal.test.js, src/components/Accounts/Actions/CommentModal.test.js, src/components/Accounts/ChargeFeeFine/UserInfo.js, src/components/PatronBlock/PatronBlockForm.js, src/components/PatronBlock/PatronBlockForm.test.js, src/components/PatronBlock/PatronBlockModalWithOverrideModal.test.js, src/settings/FeeFinesTable/CopyModal.test.js, yarn.lock
Tests should not be dependent on dynamically generated element IDs. These values are subject to change for who knows what reasons, say, maybe, a change in the rendering of elements in a third party library when `yarn.lock` changes, which causes those tests to break even though there has been no material change.
=> refactor brittle tests

CHANGELOG.md, package.json, src/components/PatronBlock/PatronBlockForm.test.js, src/settings/permissions/PermissionSetDetails.test.js, yarn.lock
- Refs https://issues.folio.org/browse/UIU-2775.
- Upgrade will be happening across all of Stripes framework and modules that reference react-redux.
- v7 to v8 is a very harmless upgrade and is only considered breaking since they removed a few rarely used functions (which I confirmed we don't use). See https://github.com/reduxjs/react-redux/releases/tag/v8.0.0 for more details.
=> Upgrade react-redux to v8

CHANGELOG.md, src/components/CustomFieldsFilters/CustomFieldsFilter.js
https://issues.folio.org/browse/UIU-2759
The single checkbox custom field was not wired with the checkbox filter. This PR adds the mapping between  `SINGLE_CHECKBOX` custom field and `CheckboxFilter`.
=> UIU-2759: Add support for checkbox custom field filter

CHANGELOG.md, src/components/Wrappers/withServicePoints.js, src/components/Wrappers/withServicePoints.test.js
https://issues.folio.org/browse/UIU-2788
The `setServicePoints` and  `setCurServicePoint` were removed from `stripes-core` in https://issues.folio.org/browse/UIU-2788
Instead, a new API was introduced called `updateUser` to modify user session data.
This PR replaces `setServicePoints` and  `setCurServicePoint` with `updateUser` to align with the recent changes in stripes-core.
=> UIU-2788: Use updateUser from @folio/stripes-core to update service-point data

CHANGELOG.md, src/components/Wrappers/withServicePoints.js
Correctly update the list of service points for each user when navigating among users by making sure local state is updated whenever the user changes. Previous comparisons between state and resources were insufficient.
Refs [UIU-2790](https://issues.folio.org/browse/UIU-2790)
=> UIU-2790 show users' service points correctly

CHANGELOG.md, src/views/UserEdit/UserEdit.js
Check if permissions exist when adding new permissions to user record
Refs [UIU-2672](https://issues.folio.org/browse/UIU-2672) (the original fix) and [UIU-2789](https://issues.folio.org/browse/UIU-2789) (patch release for MG)
=> UIU-2672 Update permUserId before updating permissions. (#2235)

CHANGELOG.md, src/components/Wrappers/withServicePoints.js
Correctly update the list of service points for each user when navigating among users by making sure local state is updated whenever the user changes. Previous comparisons between state and resources were insufficient.
Refs [UIU-2790](https://issues.folio.org/browse/UIU-2790), [UIU-2795](https://issues.folio.org/browse/UIU-2795)
=> UIU-2790 show users' service points correctly (#2339)

CHANGELOG.md, src/components/Accounts/accountFunctions.js, src/components/Accounts/accountFunctions.test.js, src/components/util/isRefundAllowed.js, src/components/util/isRefundAllowed.test.js, src/constants.js
Fee/fine that was refunded with the full amount and then canceled as an error can not be refunded one more time.
[UIU-2700](https://issues.folio.org/browse/UIU-2700)
=> UIU-2700: "Refund" option should not be available for cancelled fee/fine that was already refunded

CHANGELOG.md, src/components/Accounts/Actions/FeeFineActions.js
Fix problem with an additional information comment that can't be added after a page reload
https://issues.folio.org/browse/UIU-2794
=> UIU-2794: Fix problem with an additional information comment that can't  be added after a page reload

CHANGELOG.md, src/views/UserEdit/UserEdit.js
Allow the proxy and sponsor lists to be completely emptied. The previous incarnation only called the update handlers if the lists were defined, thus the handler would only be called if the list had at least one item on it. This made it impossible to empty the lists. Whoops.
Refs [UIU-2804](https://issues.folio.org/browse/UIU-2804)
=> UIU-2804 allow proxy/sponor lists to be emptied

CHANGELOG.md, src/components/ProxyGroup/ProxyItem/ProxyItem.js, src/components/ProxyGroup/ProxyItem/ProxyItem.test.js
Sometimes, it is possible to create a proxy record that has an invalid `proxyUserId` attribute, resulting in `ProxyItem` receiving a `record` prop with a null `user` attribute. It isn't totally clear how this happens, but it clearly does happen sometimes, and so the UI needs to handle the situation. e.g. it is possible to create a corrupt record by directly sending a PUT request to `/proxiesfor/${id}` with invalid data, even if it's not possible to create such a request in the UI.
Refs [UIU-2803](https://issues.folio.org/browse/UIU-2803)
=> UIU-2803 show an error if proxy record is corrupt

src/components/PermissionsAccordion/PermissionsAccordion.js
Generally typos in comments don't matter, but this one (it's "openPermissionModal", not "Permission**s**") is actually a minor problem, because "see X" implies you can search on X to find the implementation, and that fails when it's typo'ed.
=> Fix comments "See openPermissionsModal"

CHANGELOG.md, src/components/Accounts/Actions/ActionModal.js
Fix problem with remaining amount (not shown correct value after filling the payment amount)
Validate amount do not called when we input the same value this mean that we don't need check for comparisons current and previous value. 
https://issues.folio.org/browse/UIU-2812
=> UIU-2812: Fix problem with remaining amount (not shown correct value after filling the payment amount)

CHANGELOG.md, src/components/LostItemsLink/LostItemsLink.js, src/components/LostItemsLink/LostItemsLink.test.js, src/routes/LostItemsContainer.js, src/views/LostItems/LostItemsListContainer/LostItemsListContainer.js
Add close button to "Lost items requiring actual cost" page.
If user came to "Lost items requiring actual cost" page via "Lost items requiring actual cost" button, redirect them to the previous page on close button click. Otherwise, redirect to /users
(refs https://issues.folio.org/browse/UIU-2813)
=> UIU-2813: Add close button to "Lost items requiring actual cost" page

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
Based on comments from https://jestjs.io/docs/troubleshooting#tests-are-extremely-slow-on-docker-andor-continuous-integration-ci-server: 
> While Jest is most of the time extremely fast on modern multi-core computers with fast SSDs, it may be slow on certain setups as our users [have](https://github.com/facebook/jest/issues/1395) [discovered](https://github.com/facebook/jest/issues/1524#issuecomment-260246008).
> [...]
> ...
> If you use GitHub Actions, you can use [github-actions-cpu-cores](https://github.com/SimenB/github-actions-cpu-cores) to detect number of CPUs, and pass that to Jest.
Refs [UIU-2842](https://issues.folio.org/browse/UIU-2842), [STRIPES-854](https://issues.folio.org/browse/STRIPES-854)
=> UIU-2842 run tests on multiple cores

CHANGELOG.md, src/components/UserDetailSections/UserInfo/UserInfo.js
Display `expirationDate` based on the current timezone.
https://issues.folio.org/browse/UIU-2839
=> UIU-2839: Display expirationDate based on the current timezone

src/views/LostItems/LostItemsListContainer/components/LostItemsList/components/ActualCostDetailsModal/ActualCostDetailsModal.js, src/views/LostItems/LostItemsListContainer/components/LostItemsList/components/ActualCostDetailsModal/ActualCostDetailsModal.test.js
Add actual cost details to lost items requiring actual cost processing page
fee/fine amount should include decimal part
https://issues.folio.org/browse/UIU-2774
=> UIU-2774: Add actual cost details to lost items requiring actual cost processing page

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js
"Notify patron" checkbox is not checked when fee/fine owner has default notice. But if fee/fine owner has a default notice and the appropriate owner is selected "Notify patron" checkbox should be checked.
[UIU-2823](https://issues.folio.org/browse/UIU-2823)
=> UIU-2823: New fee/fine modal: Notify patron checkbox not checked correctly when fee/fine owner has default notice

src/components/UserDetailSections/UserAffiliations/UserAffiliations.js, src/components/UserDetailSections/UserAffiliations/util.js, src/components/UserDetailSections/UserAffiliations/util.test.js, src/hooks/useUserAffiliationsMutation/useUserAffiliationsMutation.js, src/hooks/useUserAffiliationsMutation/useUserAffiliationsMutation.test.js
- change error toast message timeout 0 until users close it
- make error messages unique if the same error messages are received from the backend response
- remove if `tenantName` exist conditional check dues to some error messages that don't require tenant names.
=> UIU-2852- Success and Error toasts

CHANGELOG.md, package.json
Also support request-storage 6.0
Field fulfilmentPreference was renamed to fulfillmentPreference. This changes do not affect current module.
https://issues.folio.org/browse/UIU-2875
=> UIU-2875: Also support request-storage 6.0

src/components/PermissionsAccordion/components/PermissionsModal/PermissionsModal.js, src/components/RenderPermissions/RenderPermissions.js, src/views/UserEdit/TenantsPermissionsAccordion.js, src/views/UserEdit/UserEdit.js
Improvement of https://issues.folio.org/browse/UIU-2805
When tenant permissions are initialized related form field is just changed (via form.change()), but it's not registered and doesn't have an initial value, so it causes form state issues (pristine, dirty, etc.).
Register a field in the final form (if it was not registered yet) when tenant permissions were initialized.
=> UIU-2805 Fix form state after tenant selection in the permissions form

CHANGELOG.md, src/components/AffiliationsManager/AffiliationsManagerModal/AffiliationsManagerModal.js, src/components/AffiliationsManager/AffiliationsManagerResultsPane/AffiliationsManagerResultsPane.js, src/components/AffiliationsManager/useAffiliationsAssignment.js, src/components/AffiliationsManager/useAffiliationsAssignment.test.js
https://issues.folio.org/browse/UIU-2876
Remove message banner
The initial approach has been changed and user permissions will not be cleared after affiliation unassign. Therefore message banner should be removed from `<AffiliationsManager>`.
<details open><summary>Preview</summary>
<p>
</p>
</details>
=> UIU-2876 Unassigning banner should not be displayed at top of 'Assign / Unassign affiliation' modal

CHANGELOG.md, package.json
User that has "Settings (Users): Can create, edit and remove all feefines-related entries" permission does not have access to the following fee/fine settings:
- Manual charges
- Transfer criteria
In the scope of [this PR](https://github.com/folio-org/ui-users/pull/2459) "ui-users.settings.manual-charges.all" and "ui-plugin-bursar-export.bursar-exports.all" permissions were not added to "ui-users.settings.feefines.all" permission. As a result "Manual charges" and "Transfer criteria" are not visible.
[UIU-2881](https://issues.folio.org/browse/UIU-2881)
=> UIU-2881: User does not have access to all feefines-related entries in settings.

CHANGELOG.md, src/views/LoanDetails/LoanDetails.js
=> In loan history, older staff notes are NOT marked "SUPERSEDED"

CHANGELOG.md, index.js, package.json
https://issues.folio.org/browse/UIU-2896
In order to implement consortium-related components, it would be useful not to write all from scratch, but use existing ones.
=> UIU-2896 Expose `<RenderPermissions>`, `<PermissionSetDetails>` and `<PermissionSetForm>` components for reuse

CHANGELOG.md, index.js, package.json
Reverts folio-org/ui-users#2491
=> Revert "UIU-2896 Expose `<RenderPermissions>`, `<PermissionSetDetails>` and `<PermissionSetForm>` components for reuse"

CHANGELOG.md, package.json
Since the addition of the `/circulation/loans/{id}/add-info` WSAPI to mod-circulation, we use that to add patron and staff notes instead of doing a PUT to the loan object. As a result, the user-level permissions for adding patron and staff notes no longer require the high-powered `circulation.loans.item.put` subpermission, but do require the permission that guards the new API, `circulation.loans.add-info.post`.
Fixes UIU-2895.
=> UIU-2895 correct subpermission for adding patron/loan notes

CHANGELOG.md, src/constants.js, src/settings/DepartmentsSettings.js, src/settings/PatronGroupsSettings.js, test/jest/__mock__/stripesUtils.mock.js
https://issues.folio.org/browse/UIU-2914
Prevent editing or deleting controlled vocabulary settings with the "consortium" source.
**Note**: applied for the settings from the [list](https://wiki.folio.org/display/FOLIJET/Consortium+manager+settings)
=> UIU-2914 Prevent editing of shared settings from outside "Consortium manager"

CHANGELOG.md, src/components/util/getLoanLastReminderNumber.js, src/components/util/getLoanLastReminderNumber.test.js, src/components/util/index.js, src/views/LoanDetails/LoanDetails.js, translations/ui-users/en.json
https://issues.folio.org/browse/UIU-2591
Display the number of reminder fees the patron has already been billed for.
=> UIU-2591: Add info about reminder fees to loan details screen

CHANGELOG.md, src/components/Loans/OpenLoans/components/OpenLoansWithStaticData/OpenLoansWithStaticData.js, src/components/Loans/OpenLoans/components/OpenLoansWithStaticData/OpenLoansWithStaticData.test.js
https://issues.folio.org/browse/UIU-2590
Add info about reminder fees to loan history
This is the continuation of the work from https://github.com/folio-org/ui-users/pull/2510
=> UIU-2590: Add info about reminder fees to loan history

CHANGELOG.md, package.json, yarn.lock
Replace unmaintained `word-wrap` package with a forked version that contains a fix for the vulnerable regex.
Refs CVE-2023-26115
=> CVE-2023-26115 mitigation

CHANGELOG.md, src/settings/patronBlocks/Limits/Limits.js, src/settings/patronBlocks/Limits/LimitsForm.js, src/settings/patronBlocks/Limits/LimitsForm.test.js
User settings > Limits: Disable editing for users with "Setting (Users): View all settings"
when logged in user has view all user settings permissions.
when logged in with diku
https://issues.folio.org/browse/UIU-2912
=> UIU-2912 - add permissions check to edit patron block limits

CHANGELOG.md, src/views/UserDetail/UserDetail.js
Add support for `request-storage` version `6.0` to be able to see the "Requests" accordion on a user details page.
[UIU-2920](https://issues.folio.org/browse/UIU-2920)
=> UIU-2920: Requests accordion is not shown on the User's details page

CHANGELOG.md, src/settings/FeeFineSettings.js, src/settings/FeeFineSettings.test.js, src/settings/FeeFinesTable/ChargeNotice.js, src/settings/FeeFinesTable/ChargeNotice.test.js
User settings > Manual Charges: Disable editing for users with "Setting (Users): View all settings" permission
Behavior on Manual charges settings page when logged in user have view only permission.
Behavior on Manual charges settings page when logged in diku user.
https://issues.folio.org/browse/UIU-2903
=> Add permisison checks to restrict edit on Manual charges settings page

CHANGELOG.md, package.json, translations/ui-users/en_US.json
Clean up setting.transfertypes permissions
Removed unused permissions
https://issues.folio.org/browse/UIU-2919
=> UIU-2919 - Clean up setting.transfertypes permissions.

CHANGELOG.md, src/settings/CommentRequiredSettings.test.js, src/settings/TransferAccountsSettings.js, src/settings/TransferAccountsSettings.test.js
User settings > Transfer Accounts: Disable editing for users with "Setting (Users): View all settings" permission
When logged in user has view all user settings permissions - 
when logged in with diku
https://issues.folio.org/browse/UIU-2910
=> UIU-2910 - Add permission check to restrict edit of transfer account page on user settings.

CHANGELOG.md, src/views/UserEdit/UserEdit.js, src/views/UserEdit/UserEdit.test.js
"User search results" pane is cleared after canceling user's profile editing
Add search filters to path while navigating back to user preview screen, when cancelling user edit.
https://issues.folio.org/browse/UIU-2928
=> UIU-2928 - Add serach filters to path while navigating back to user preview screen, when cancelling user edit

CHANGELOG.md, src/components/AssignedUsers/hooks/useAssignedUsers/useAssignedUsers.js, src/views/UserEdit/UserEdit.js, src/views/UserEdit/UserEditHelpers.js, src/views/UserEdit/UserEditHelpers.test.js, translations/ui-users/en.json
- Given staff user is creating/editing a user with a username
- When staff user inputs a username already in use by any member and clicks save
- Then staff user is alerted: "This username already exists"
- AND the create/edit screen remains open
- AND the user is NOT saved
https://github.com/folio-org/ui-users/assets/116072773/bec90133-c445-46a0-866a-6ca2b0632d86
=> UIU-2889: show error messages on create/edit users with existing username

src/components/AssignedUsers/AssignedUsersContainer.js, src/components/AssignedUsers/AssignedUsersContainer.test.js, src/components/AssignedUsers/hooks/useAssignedUsers/useAssignedUsers.js, src/components/AssignedUsers/hooks/useAssignedUsers/useAssignedUsers.test.js
[UIU-2873](https://issues.folio.org/browse/UIU-2873) - allow to run query with empty grantedToIds
The reason to allow run query when the user removes all assigned users the list isn't updated due to `grantedToIds` length equal to 0.
https://github.com/folio-org/ui-users/assets/116072773/abf5cef7-fbb1-42e0-8cad-cc8906578712
Ideally all of the PRs involved …
=> UIU-2873: allow to run query without grantedToIds

CHANGELOG.md, src/constants.js, src/routes/UserSearchContainer.js, src/routes/UserSearchContainer.test.js
https://issues.folio.org/browse/UIU-2933
Mix a directive in CQL to exclude users with `type` equal to "shadow".
https://github.com/folio-org/ui-users/assets/88109087/99bd9d8b-7d1d-4416-99fc-876a8d9d2f99 …
=> UIU-2933 ECS - Do not display shadow users in search results

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
Use the `master` branch of the SonarCloud GitHub action instead of pinning to an old old version. This has no effect on how things work in production, only on how code is analyzed in CI. This brings ui-users' workflow files into line with those in other UI repositories that were configured after we first configured it here as a POC.
=> use master branch of sonarcloud scanner GitHub Action

CHANGELOG.md, src/components/ModalContent/ModalContent.js
https://issues.folio.org/browse/UIU-2932
Add auto focus to textarea on staff and patron info modal
=> UIU-2932: Add auto focus to textarea on staff and patron info modal

CHANGELOG.md, src/components/EditSections/EditContactInfo/EditContactInfo.js, src/components/EditSections/EditContactInfo/EditContactInfo.test.js, src/components/EditSections/EditExtendedInfo/CreateResetPasswordControl/CreateResetPasswordControl.css, src/components/EditSections/EditExtendedInfo/CreateResetPasswordControl/CreateResetPasswordControl.js, src/components/EditSections/EditExtendedInfo/CreateResetPasswordControl/CreateResetPasswordControl.test.js, src/components/EditSections/EditExtendedInfo/DepartmentsNameEdit/DepartmentsNameEdit.js, src/components/EditSections/EditExtendedInfo/DepartmentsNameEdit/DepartmentsNameEdit.test.js, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.test.js, src/components/EditSections/EditExtendedInfo/RequestPreferencesEdit/RequestPreferencesEdit.js, src/components/EditSections/EditUserInfo/EditUserInfo.js, src/components/EditSections/EditUserInfo/EditUserInfo.test.js, src/views/UserDetail/UserDetail.js, src/views/UserDetail/UserDetail.test.js, src/views/UserEdit/UserForm.js
[UIU-2951](https://issues.folio.org/browse/UIU-2951) - ECS - Prevent editing of specific shadow user data
- disabled accordions and user details fields for shadow users
- 
https://github.com/folio-org/ui-users/assets/116072773/0a3bbf8f-97bf-4c1a-b096-8bf5964553fb
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid …
=> UIU-2951: ECS - Prevent editing of specific shadow user data

CHANGELOG.md, package.json, translations/ui-users/en.json
[UIU-2955](https://issues.folio.org/browse/UIU-2955) - Permission "Create users" includes "Edit users" as well
Relabel ui-users.create from "Users: Can create new user" to something like "Users: Can create and edit users", leaving the permissions as-is.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking …
=> UIU-2955 - Relabel 'Users: Can create new user' to 'Users: Can create and edit users'

src/views/UserSearch/UserSearch.js
[UIU-2943](https://issues.folio.org/browse/UIU-2943) - remove initially selected user types from filters
https://github.com/folio-org/ui-users/assets/116072773/12792488-0374-41b2-9025-2c2c551adcda
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount …
=> UIU-2869: remove initial selected user types from filters

CHANGELOG.md, src/components/Wrappers/withRenew.js
Fix user can not renew the loan through the override
We don't need use state in current case
https://issues.folio.org/browse/UIU-2948
=> UIU-2948: Fix user can not renew the loan through the override

CHANGELOG.md, package.json, src/components/PermissionsAccordion/PermissionsAccordion.js, src/components/util/util.js, src/components/util/util.test.js, src/constants.js, src/hooks/useUserAffiliations/useUserAffiliations.js, src/views/UserDetail/UserDetail.js, src/views/UserEdit/TenantsPermissionsAccordion.js
https://issues.folio.org/browse/UIU-2967
When changing a user type from `staff` to `patron` - affiliations are deleted on BE side and it results in an error when querying users' tenants. So for for users with types `patron` or `dbc` (a new user type, that isn't meant to work with affiliations) "Affiliations" selector should be hidden in the permissions accordion and the related query to fetch user affiliations should be disabled.
Prevent fetching affiliations if a user type is a `patron` or `dcb`. Hide the "Affiliations" selection for those types in the user edit form.
https://github.com/folio-org/ui-users/assets/88109087/14083b4c-c51c-4c71-8704-e4f520264fa1
- Does this PR meet or exceed the …
=> UIU-2967 Don't display affiliations of users with types `patron` or `dcb`

CHANGELOG.md, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.test.js, src/components/util/util.js, src/views/UserEdit/UserForm.js
https://issues.folio.org/browse/UIU-2970
Currently, it is possible to save staff users without a username populated. Basically, staff users should be able to login to ECS so a username is required. Also, the username field is necessary to create affiliations.
Make the `username` field required only for users with the `staff` type and only in the ESC mode (with enabled `consortia` interface).
https://github.com/folio-org/ui-users/assets/88109087/5b4332e9-5a9a-448a-a245-aa84075d1027
- What other modules will these changes …
=> UIU-2970 Make the `username` field required for users with the `staff` type in "ECS" mode

CHANGELOG.md, package.json
Also support `feesfines` interface version `19.0`
Changes was in endpoint `/accounts` the field `status` has become required, this does not affect the current module.
This is part of `Quesnelia (R1 2024)` release
Should be merged after merging https://issues.folio.org/browse/MODFEE-337
https://issues.folio.org/browse/UIU-2960
=> UIU-2960: Also support feesfines interface version 19.0

CHANGELOG.md, src/components/PermissionsAccordion/components/PermissionsModal/PermissionsModal.js
The `X-Okapi-Token` header is optional and should only be included when a token value is present on the `stripes.okapi` object.
Refs [UIU-2977](https://issues.folio.org/browse/UIUSERS-2977)
=> UIU-2977 x-okapi-token header must always be optional

CHANGELOG.md, src/routes/UserSearchContainer.js
[UIU-2995](https://issues.folio.org/browse/UIU-2995) - Mask/escape backslash and double quote in tag search
Special characters like ",*,?,\ are allowed in creation of tags.
When such a tag is searched in users app via the "Tags" filter, an error like "QueryValidationException: ? wildcard not allowed in full text query string" and "QueryValidationException: * right truncation wildcard must be followed by space or end of string, but found .." are observed.
Hence, the tags filters are escaped before passing them to makeQueryFunction.
If there are breaking changes, please **STOP** and consider the …
=> UIU-2995 - Update resourceData and queryParams in UserSearchContainer.js to escape special characters in tags filter

CHANGELOG.md, src/routes/LoansListingContainer.js
When user clicks on "Claim returned" button from the action menu dropdown item status becomes "Claimed returned" but fee/fine status is not "Suspended claim returned" and Fees/fines incurred is not "Suspended".
The issue happened because we did not have access to some data from manifest and as a result a few additional requests were not executed.
I extended already existing manifest to have all necessary "mutators" and "resources".
[UIU-2993](https://issues.folio.org/browse/UIU-2993)
=> UIU-2993: Add the possibility to do "Claim returned" from action menu

CHANGELOG.md
=> UIU-2979 - Update changelog after Release v10.0.4

CHANGELOG.md, src/components/UserDetailSections/PatronBlock/PatronBlock.js, src/components/UserDetailSections/PatronBlock/PatronBlock.test.js, src/components/UserDetailSections/UserAccounts/UserAccounts.js, src/components/UserDetailSections/UserAccounts/UserAccounts.test.js, src/components/UserDetailSections/UserRequests/UserRequests.js, src/components/UserDetailSections/UserRequests/UserRequests.test.js, src/views/UserDetail/UserDetail.js, src/views/UserDetail/UserDetail.test.js
Link to PR with master branch as target - https://github.com/folio-org/ui-users/pull/2592
=> UIU-2987-poppy-dcb - Hide all actionalble buttons on user details pane

CHANGELOG.md, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.test.js, src/components/Loans/OpenLoans/components/OpenLoansSubHeader/OpenLoansSubHeader.js, src/components/Loans/OpenLoans/components/OpenLoansSubHeader/OpenLoansSubHeader.test.js, src/components/util/util.js, src/components/util/util.test.js, src/constants.js, yarn.lock
Disable open loan action buttons and hide open loan record action menu items for DCB Lending library
UIU-2988 - https://issues.folio.org/browse/UIU-2988
Virtual user and virtual items are considered to determine DCB library roles.
Virtual User or DCB user will have lastName hardcoded to "DcbSystem" and type would be 'dcb'
Virtual Item would have hard coded instance id and holdings record id
borrowing-pickup - open loans page
lending role - open loans page
pickup role - open loans page
- What other modules will these changes …
=> UIU-2988 - User - Open Loans: UI changes for supporting DCB circulation

CHANGELOG.md, src/components/data/reports/CashDrawerReconciliationReport.js
Fix wrong date in Cash-Drawer-Reconciliation-Report.pdf
We should have the same date that we select in Datepicker
https://issues.folio.org/browse/UIU-3010
=> UIU-3010: Fix wrong date in Cash-Drawer-Reconciliation-Report.pdf

src/components/Loans/OpenLoans/helpers/getListDataFormatter.js
Revert UIU-3002 changes.
Accidently, effective call number sorting bug changes were pushed to master. This PR is to revert those changes from master.
The needful changes will be propagated via a new PR.
=> revert effective call number sorting change

CHANGELOG.md, src/components/Accounts/Actions/ActionModal.js
Update request header for pay several Fees/fines
Use correct function (getHeaderWithCredentials) for create request header instead of creating manually.
Consistency with singleItemCheck https://github.com/folio-org/ui-users/pull/2624/files#diff-5db4900190c2fce5fa7fc0b4c012e654f4abd378c1ace36aee8ea0ea4727e07dR214
https://issues.folio.org/browse/UIU-3040
=> UIU-3040: Update request header for pay several Fees/fines

CHANGELOG.md, src/components/EditSections/EditUserInfo/EditUserInfo.js, src/components/EditSections/EditUserInfo/EditUserInfo.test.js, src/components/EditSections/EditUserInfo/components/ChangeUserTypeModal/ChangeUserTypeModal.js, src/components/EditSections/EditUserInfo/components/ChangeUserTypeModal/ChangeUserTypeModal.test.js, src/components/EditSections/EditUserInfo/components/ChangeUserTypeModal/index.js, src/components/EditSections/EditUserInfo/components/index.js, translations/ui-users/en.json
[https://folio-org.atlassian.net/browse/UIU-2969](https://folio-org.atlassian.net/browse/UIU-2969)
https://github.com/folio-org/ui-users/assets/116072773/8e4bf2a1-cf4d-4127-b271-5e2e31ddebff
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if …
=> UIU-2969: change user type confirmation  modal

package.json
UIU-3030: Adjust permission names for batch-print
https://folio-org.atlassian.net/browse/UIU-3030
The wrong names were used before. This PR should address it.
=> UIU-3030: Adjust permission names for batch-print

CHANGELOG.md, package.json
https://folio-org.atlassian.net/browse/UIU-3068
Add newly added users-keycloak permissions to the package.json 
- add users-keycloak related permissions
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the …
=> UIU-3068: add users-keycloak perms

CHANGELOG.md, package.json, src/routes/UserRecordContainer.js, src/views/UserDetail/UserDetail.js, src/views/UserDetail/UserDetail.test.js, src/views/UserEdit/UserForm.js, src/views/UserEdit/UserForm.test.js, test/jest/__mock__/stripesSmartComponent.mock.js
When the `roles` interface is present, indicating the legacy permissions system has been replaced, do not show the permissions accordions on the user-details or user-edit panes, and do not query any permissions-related endpoints.
Refs [UIU-3061](https://folio-org.atlassian.net/browse/UIU-3061), [UIU-3063](https://folio-org.atlassian.net/browse/UIU-3063)
=> UIU-3061, UIU-3063 omit permissions accordions/queries

src/settings/DepartmentsSettings.js, src/settings/PatronGroupsSettings.js, yarn.lock
`DepartmentSettings` and `PatronGroupsSettings` were tweaked in a8f397f213472b9c9558430330ddcce1375a875b to avoid ECS-related functionality that was not yet committed in `@folio/stripes-util` when this work began. But now it has been committed, and we can undo this change, bringing them back into sync, and restoring their tests.
=> sync settings pages with master, repairing tests

CHANGELOG.md, package.json, src/hooks/useConsortiumPermissions/useConsortiumPermissions.js, src/hooks/useConsortiumPermissions/useConsortiumPermissionsUsersKeycloak.test.js
When the `users-keycloak` interface is present, use its endpoints to retrieve the logged-in user's permissions in the central tenant.
Refs [UIU-3054](https://folio-org.atlassian.net/browse/UIU-3054)
=> UIU-3054 use users-keycloak interface for central-tenant permissions

CHANGELOG.md, src/components/AddServicePointModal/AddServicePointModal.js
[UIU-3069](https://folio-org.atlassian.net/browse/UIU-3069) - AddServicePointModal may throw NPE on props.assignedServicePoints.map
Add optional chaining in AddServicePointModal in order to safely access assignedServicePoints from props.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
=> UIU-3069 - Add optional chaining in AddServicePointModal in order to safely access assignedServicePoints from props.

.github/workflows/build-npm.yml, package.json, yarn.lock
Include `@aashutoshrathi/word-wrap` as a dev-dep in addition to including it in `resolutions` where it is used as an alias to replace the (unmaintained) `word-wrap`. Just like peer-deps, yarn does not satisfy resolutions-deps, so if we want that reference in `resolutions` to be resolvable, we need to _actually_ depend on it elsewhere. `word-wrap` is a transitive dep via eslint > optionator, so I added `@aashutoshrathi/word-wrap` as a dev-dep. 
Some fool called @zburke introduced this bug -- trying to satisfy a resolutions-alias with a module that isn't included as a dependency -- in #2512. How did that ever work? What an idiot. Probably he added the dep manually, then added the alias, then manually removed the dep. Let this be a lesson to us all: always use tools to manipulate …
=> include @aashutoshrathi/word-wrap as a dev-dep

.github/workflows/build-npm.yml, package.json, yarn.lock
We were subject to CVE-2023-26115 via a transitive vulnerability from eslint > optionator > word-wrap. [optionator noticed the same vulnerability](https://github.com/gkz/optionator/issues/44) and made the same fix in [`06fd3a`](https://github.com/gkz/optionator/commit/06fd3a54a9b22bd9a5938c416fd491da6ff9eef1) so the best thing we can do here is ... nothing.
=> don't work so hard; CVE-2023-26115 was fixed upstream

CHANGELOG.md, src/components/AddServicePointModal/AddServicePointModal.js, src/components/AddServicePointModal/AddServicePointModal.test.js, src/components/AffiliationsManager/AffiliationsManager.test.js, src/components/AffiliationsManager/AffiliationsManagerModal/AffiliationsManagerModalFooter.js, src/components/EditSections/EditServicePoints/EditServicePoints.test.js, src/components/EditSections/EditUserInfo/components/LocalFileModal/LocalFileModal.js, src/components/EditSections/EditUserInfo/components/LocalFileModal/LocalFileModal.test.js, src/components/PermissionsAccordion/components/PermissionsModal/PermissionsModal.js, src/components/PermissionsAccordion/components/PermissionsModal/PermissionsModal.test.js, src/components/ReportModals/CashDrawerReportModal.js, src/components/ReportModals/FinancialTransactionsReportModal.js, src/components/ReportModals/RefundsReportModal.js, src/components/UserDetailSections/UserAffiliations/UserAffiliations.test.js, src/components/Wrappers/withAddInfo.js, src/settings/patronBlocks/BlockTemplates/BlockTemplateForm.js, src/settings/patronBlocks/BlockTemplates/BlockTemplateForm.test.js, src/settings/permissions/PermissionSetForm.js, src/settings/permissions/PermissionSetForm.test.js, src/views/UserEdit/UserForm.js, translations/ui-users/en.json
https://folio-org.atlassian.net/browse/UIU-3078
We removed local `saveAndClose` label and replace it with `stripes-components.saveAndClose`. Also all related tests updated
=> UIU-3078: use Save & close button label stripes-component translation key 

CHANGELOG.md, src/settings/FeeFinesTable/CopyModal.js, src/settings/FeeFinesTable/FeeFinesTable.css
[UIU-2929](https://folio-org.atlassian.net/jira/software/c/projects/UIU/boards/76?assignee=712020%3A5ca69dba-5ba2-4ee1-be22-97e32eeff056&selectedIssue=UIU-2929) - Fix two "triangle down" icons displayed in select element of "Copy existing fee/fine owner table entries" modal.
https://github.com/folio-org/ui-users/assets/105021655/a6a1c633-31cf-406b-b8c5-0c8dbb2d857c
- Do PRs exist for these …
=> UIU-2929 - fix two triangle icons

CHANGELOG.md, src/components/RenderRoles/RenderRoles.js, src/components/RenderRoles/RenderRoles.test.js, src/components/RenderRoles/index.js, src/components/UserDetailSections/UserRoles/UserRoles.js, src/components/UserDetailSections/UserRoles/UserRoles.test.js, src/components/UserDetailSections/UserRoles/index.js, src/components/UserDetailSections/index.js, src/hooks/index.js, src/hooks/useUserTenantRoles/index.js, src/hooks/useUserTenantRoles/useUserTenantRoles.js, src/hooks/useUserTenantRoles/useUserTenantRoles.test.js, src/routes/UserRecordContainer.js, src/views/UserDetail/UserDetail.js, src/views/UserDetail/UserDetail.test.js, test/jest/__mock__/stripesCore.mock.js, test/jest/fixtures/roles.json, translations/ui-users/en.json
Show roles assigned to users (i.e. the other half of [UIROLES-31](https://folio-org.atlassian.net/browse/UIROLES-31) where we show users assigned to roles). 
Refs [UIU-3110](https://folio-org.atlassian.net/browse/UIU-3110)
=> UIU-3110 show roles assigned to users

CHANGELOG.md, src/components/Accounts/Actions/ActionModal.js
Fix issue with "Total paid amount" value that has incorrect view.
Property that is used for "Total paid amount" value is `totalPaidAmount`. At the parent component this property was handled by `localizeCurrencyAmount` method and then inside `ActionModal` component it was handled by that method one more time. As a result we had `$NaN`. To fix this problem I had to remove one unnecessary handling.
[UIU-3094](https://folio-org.atlassian.net/browse/UIU-3094)
=> UIU-3094: "Total paid amount" value is set as "$NaN" on "Refund fee/fine" modal

CHANGELOG.md, src/components/Loans/OpenLoans/OpenLoansControl.js, src/components/Wrappers/withRenew.js, src/components/Wrappers/withRenew.test.js, translations/ui-users/en.json
Allow override for reminder fees with renewal blocked.
https://folio-org.atlassian.net/browse/UICIRC-1077
=> UICIRC-1077: Allow override for reminder fees with renewal blocked

CHANGELOG.md, src/components/EditSections/EditUserRoles/ EditUserRoles.test.js, src/components/EditSections/EditUserRoles/EditUserRoles.js, src/components/EditSections/EditUserRoles/EditUserRoles.test.js, src/components/EditSections/EditUserRoles/index.js, src/components/EditSections/index.js, src/views/UserEdit/UserForm.js, src/views/UserEdit/UserForm.test.js, translations/ui-users/en.json
Add user roles accordion into edit user …
=> UIU-3021: add edit user roles accordion to user edit view

CHANGELOG.md, src/components/UserDetailSections/ReadingRoomAccess/ReadingRoomAccess.js
[UIU-3150](https://folio-org.atlassian.net/browse/UIU-3150) - Make Reading Room filter case insensitive.  …
=> UIU-3150 - Make Reading Room filter case insensitive

src/hooks/index.js
The hook is present; we're just missing the top-level export. It got lost in the backporting of role-related work from #keycloak-ramsons onto #keycloak-quesnelia.
=> restore useProfilePicture

CHANGELOG.md, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js, src/components/EditSections/EditUserInfo/EditUserInfo.js, src/components/PatronBlock/PatronBlockForm.js, src/components/ProxyGroup/ProxyEditItem/ProxyEditItem.js
[UIU-2879](https://folio-org.atlassian.net/browse/UIU-2879) -  Set Users date format in all date input fields as per Session Locale Settings.
This PR address the following date input fields in ui-users :- 
- Expiration Date in => UserInfo Screen > Patron Blocks Accordion > Create  Block > Block Information Accordion.
- Expiration date, Date enrolled and Birth date => UserEdit Screen.
- Expiration date => UserEdit Screen > Proxy/Sponser Accordion. 
https://github.com/folio-org/ui-users/assets/105021655/60f43f05-5887-47bb-b3b6-f24762765741
If there are breaking changes, please **STOP** and consider …
=> UIU-2879 - Set Users date format as per Session Locale Settings

CHANGELOG.md, src/components/Accounts/ViewFeesFines/ViewFeesFines.js, src/constants.js, src/constants.test.js, src/views/AccountDetails/AccountDetails.js
When loan was closed by check in and when it has open fees or fines and if item is checked out again and gets claimed returned the previous borrower blocked from paying (waiving/transferring/canceling) their fees or fines.
Initially we had disabled pay, waive, transfer, refund, cancel buttons if item had a status "Claimed returned". But now we additionally rely on loan status that should have value 'Closed'. In this case all mentioned buttons will be enabled.
(Approach confirmed by PO).
[UIU-3125](https://folio-org.atlassian.net/browse/UIU-3125)
=> UIU-3125: Make unblocked fee-fine actions if item is claimed returned and loan is opened

src/components/EditSections/EditServicePoints/EditServicePoints.js
> This developer needs a copy-editor!
-- Zak Burke, FOLIO
* Remove the extra `}` that's plagued the service-points headline for the last three years since PR #1724. Can't believe we didn't notice!
Refs [UIU-2158](https://folio-org.atlassian.net/browse/UIU-2158)
=> UIU-2158 omit extra curly-brace

src/routes/UserRecordContainer.js
This PR is to revert certain changes in https://github.com/folio-org/ui-users/pull/2702 in order to resolve the error received while creating a new user.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as …
=> UIU-3132 - fix RRA error while creating a new user (follow-up)

src/components/EditSections/EditUserRoles/EditUserRoles.js, src/views/LoanDetails/LoanDetails.js
Resolve the following console error:
> Warning: React does not recognize the `data-testId` prop on a DOM
> element. If you intentionally want it to appear in the DOM as a custom
> attribute, spell it as lowercase `data-testid` instead. If you
> accidentally passed it from a parent component, remove it from the DOM
> element.
=> use data-testid, not data-testId, to avoid React complaints

src/components/EditSections/EditUserRoles/EditUserRoles.js, src/components/EditSections/EditUserRoles/EditUserRoles.test.js, src/components/EditSections/EditUserRoles/components/UserRolesModal/UserRolesModal.js, src/components/EditSections/EditUserRoles/components/UserRolesModal/UserRolesModal.test.js, src/views/UserEdit/UserForm.js
Fixing [comment](https://folio-org.atlassian.net/browse/UIU-3145?focusedCommentId=220800) from the [UIU-3145](https://folio-org.atlassian.net/browse/UIU-3145) - Not all roles are shown in “User roles“ accordion in user edit view after assigning multiple roles.
react-final-form provides a form API that includes getFieldState, which is not reactive. In order to track the changes of the form, a listener component is required. Use OnChange component to track the _assignedRoleIds_ fields from the form.  
- What other modules will …
=> UIU-3145-followup: use react-final-form OnChange listener to track the actual data of assignedRoleIds

CHANGELOG.md, src/components/PrintLibraryCardButton/PrintLibraryCardButton.js, src/components/PrintLibraryCardButton/PrintLibraryCardButton.test.js, src/views/UserDetail/UserDetail.js, translations/ui-users/en.json
[UIU-3171](https://folio-org.atlassian.net/browse/UIU-3171) - Success message for user details export for library card printing
1. Display success toasts on user details and user profile picture export.
2. Hide "Print Library Button" when either profile picture feature is not enabled.
3. Disable "PrintLibraryCard" button when profile picture feature is enabled and user do not have an image attached to his profile.
Display success toasts on user details and user profile picture export.
Hide "Print Library Button" when either profile picture feature is not enabled and disable "PrintLibraryCard" button when profile picture feature is enabled and user do not have an image attached to his profile.
- Does …
=> UIU-3171 - Success message for user details export for library card printing

CHANGELOG.md, package.json, src/views/LoanDetails/LoanDetails.js, src/views/LoanDetails/LoanDetails.test.js
The interface used for adding patron/staff notes to loans is now optional, and the relevant code guarded with `<IfInterface>`.
Fixes UIU-3182.
=> "add-info" interface is optional to prevent dependency cascades

CHANGELOG.md, src/components/EditSections/EditContactInfo/EditContactInfo.js, src/components/EditSections/EditContactInfo/EditContactInfo.test.js, src/components/UserAddresses/UserAddresses.js, src/components/UserAddresses/UserAddresses.test.js, src/components/data/converters/address.js, src/views/UserEdit/UserForm.js, src/views/UserEdit/UserForm.test.js
[UIU-3180](https://folio-org.atlassian.net/browse/UIU-3180) - Populate the 'Address Type' Field in UserEdit and UserInfo Screen on user creation via edge module.
https://github.com/user-attachments/assets/13e9dc01-097c-475b-9e2a-dd089ff6d05d
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> UIU-3180 - Populate the 'Address Type' Field in UserEdit and UserInfo Screen on user creation via edge module.

CHANGELOG.md, package.json, src/routes/UserSearchContainer.js, src/routes/UserSearchContainer.test.js
[UIU-3184](https://folio-org.atlassian.net/browse/UIU-3184) - Use keywords CQL field for keyword user search.
The /users API has a new CQL search index keywords that significantly speeds up the search. This [implementation](https://folio-org.atlassian.net/browse/MODUSERS-457) bumped up users interface from 16.2 to 16.3 and it is backwards compatible.
Hence search query is updated to leverage the new search index.
when users interface is not 16.3 (here 16.2)
when users interface is 16.3
- What other modules will these changes …
=> UIU-3184 - Use keywords CQL field for keyword user search.

CHANGELOG.md, src/routes/ChargeFeesFinesContainer.js
Fix issue when slash character in item barcode creates 404 error when adding fee/fine at check in.
Wrap item barcode by double quotes. In this case server correctly handles item barcode.
[UIU-3193](https://folio-org.atlassian.net/browse/UIU-3193)
=> UIU-3193: Fix issue when slash character in item barcode creates 404 error when adding fee/fine at check in

src/components/Wrappers/withUserRoles.js, src/components/Wrappers/withUserRoles.test.js, src/hooks/useAllRolesData/useAllRolesData.js, src/routes/UserRecordContainer.js, src/views/UserDetail/UserDetail.js, src/views/UserEdit/UserEdit.js
- Fixes [UIU-3212](https://folio-org.atlassian.net/browse/UIU-3212) by removing property `assignedRoleIds` from `PUT /users` request if `roles` interface is not present.
- Corrected API calls in `UserRecordContainer.js` to use variable in parameter instead of expecting `stripes-connect` which will only transform static string values and not functions.
- Removed duplicate code in `UserDetail.js`
=> [UIU-3212] Error when saving edited user

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
GitHub deprecated v2 so that must change, and we might as well just use the current version (v4) across the board.
=> bump workflow's upload-artifact action to v4

CHANGELOG.md, src/routes/UserRecordContainer.js
[UIU-3102](https://folio-org.atlassian.net/browse/UIU-3102) - revert conditional use of the users-keycloak interface …
=> UIU-3102: revert conditional use of the users-keycloak interface in UserRecordContainer

CHANGELOG.md, src/components/util/util.js, src/components/util/util.test.js
Sometimes, item records are removed even when they are attached to open loans.  Optional chaining in `isDcbItem()` prevents an NPE in this circumstance.
Refs [UIU-3230](https://folio-org.atlassian.net/browse/UIU-3230)
=> UIU-3230 isDcbItem must handle sparse data

CHANGELOG.md, src/views/UserEdit/UserEdit.js
[UIU-3233](https://folio-org.atlassian.net/browse/UIU-3233) - Cannot save edited user
Always omit `assignedRoleIds` field on user edit, since we don't need the one for selUser.PUT method, and assignedRoleIds handled separately.  
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing …
=> UIU-3233: omit assignedRoleIds field on edit user

CHANGELOG.md, src/components/PermissionsAccordion/components/PermissionsList/PermissionsList.test.js, src/components/PermissionsAccordion/components/PermissionsModal/PermissionsModal.test.js, src/components/PermissionsAccordion/helpers/filtersConfig.test.js
Update permission name after Review and cleanup Module Descriptor for ui-checkout
Consistency update permission with ui-checkout ( https://folio-org.atlassian.net/browse/UICHKOUT-919 )
Permissions renamed in according with Permissions naming convention ( https://folio-org.atlassian.net/wiki/spaces/FOLIJET/pages/156368925/Permissions+naming+convention )
https://issues.folio.org/browse/UIU-3216
=> UIU-3216: Update permission name after Review and cleanup Module Descriptor for ui-checkout

src/views/PatronsPreRegistrationListContainer/PatronsPreRegistrationList.js, src/views/UserDetail/UserDetail.js, src/views/UserDetail/UserDetail.test.js
https://folio-org.atlassian.net/browse/UIU-3224
The value of `document.referrer` stores the value of the page from which the original transition to the new tab was made. When navigating the page, this value does not change, which may lead to incorrect redirection when closing user details.
Ideally all of the PRs involved in breaking changes would be merged …
=> UIU-3224 Avoid using `document.referrer` to identify back path route

CHANGELOG.md, src/components/EditSections/EditExtendedInfo/CreateResetPasswordControl/CreateResetPasswordControl.js, src/components/EditSections/EditExtendedInfo/CreateResetPasswordControl/CreateResetPasswordControl.test.js
- Fixes [UIU-3236](https://folio-org.atlassian.net/browse/UIU-3236) which only affects Eureka environments.
- When trying to reset a password for a user which does not have a record in Keycloak (which could be users created before an environment migrates to Eureka), the password reset request will fail. This change first checks keycloak to see if it has a record of the user. If not, it creates the record and then proceeds to generate the password reset link.
=> [UIU-3236] Cannot reset password for user not having a Keycloak record

CHANGELOG.md, package.json
[UIU-3275](https://folio-org.atlassian.net/browse/UIU-3275) - Update permission checks
The requirement of the ticket was to support permission changes/updates leveraging `hasAnyPerm` and `IfAnyPermission `utilities from `stripes core`. **This is targeted for Ramsons bugfix.** 
ui-users is introduced as a breaking change for Ramsons. Hence, changing users interface from "16.0 16.1 16.2" to "16.3" should be fine. Also, this does not impact the permission checks, as 
1. permission checks have already been updated with new permission names - https://github.com/folio-org/ui-users/pull/2778/files
2. translations have already been updated with new permission names - https://github.com/folio-org/ui-users/pull/2778/files
3. translations have also been synced accordingly - …
=> UIU-3275 - Change users interface to 16.3

CHANGELOG.md, package.json, src/routes/PatronNoticePrintJobsContainer.js, src/views/PatronNoticePrintJobs/PatronNoticePrintJobs.js
We now show the top 100 patron notice print jobs, not 10.
More importantly, they are now sorted correctly (reverse chronological) on the server side, so even if the list grows past 100 and so is truncated in the UI at the first hundred, they will be the _right_ (most recent) first hundred.
Fixes UIU-3269.
=> Show all patron notice print jobs, in correct order

CHANGELOG.md, src/hooks/useUserTenantRoles/useUserTenantRoles.js, src/hooks/useUserTenantRoles/useUserTenantRoles.test.js
Supply the `tenantId` argument in all queries. It was present in the query for a user's roles, but missing from the follow-up join-query that retrieved those roles' details, and thus returned an empty list unless the selected-tenant matched that of the currently-authenticated user.
Refs [UIU-3279](https://folio-org.atlassian.net/browse/UIU-3279)
=> UIU-3279 supply tenantId in all useUserTenantRoles queries

CHANGELOG.md, package.json
Add missed `circulation-storage.loans.item.get` sub-permission to be able to create new fee-fine if used has "Users: Can create, edit and remove fees/fines" permission
[UIU-3291](https://folio-org.atlassian.net/browse/UIU-3291)
=> UIU-3291: Permissions error when adding a Fee-Fine via the User's app and Check-in.

CHANGELOG.md, package.json, src/hooks/useAllRolesData/useAllRolesData.js
[UIU-3294](https://folio-org.atlassian.net/browse/UIU-3294) - Error toasts when opening a user for edit without having "User Roles" capability set
1. Check endpoints used in [withUserRoles](https://github.com/folio-org/ui-users/blob/UIU-3294/src/components/Wrappers/withUserRoles.js) HOC;
2. Add subPermissions to ui-users.view, ui-users.edit based on module-descriptors [mod-roles-keycloak](https://github.com/folio-org/mod-roles-keycloak/blob/master/descriptors/ModuleDescriptor-template.json) and [mod-users-keycloak](https://github.com/folio-org/mod-users-keycloak/blob/master/descriptors/ModuleDescriptor-template.json)
- Does this introduce …
=> UIU-3294: Provide correct role-assignment permissions for endpoints within withUserRoles HOC used with UserEdit. 

CHANGELOG.md, package.json, src/components/Wrappers/withUserRoles.js, src/hooks/useAllRolesData/useAllRolesData.js
Release v11.0.9
While it's helpful for reviewers to help identify potential problems, …
=> Release v11.0.9

CHANGELOG.md, package.json
[UIU-3305](https://folio-org.atlassian.net/browse/UIU-3305) - Missing permissions to add manual block …
=> UIU-3305 - Add sub permission `manual-block-templates.collection.get` to permission `Users: Can create, edit and remove patron blocks`

CHANGELOG.md, src/components/AffiliationsManager/AffiliationsManager.js, src/components/AffiliationsSelect/AffiliationsSelect.js, src/components/AssignedUsers/AssignedUsersContainer.js, src/components/AssignedUsers/AssignedUsersList.js, src/components/BulkRenewalDialog/BulkRenewedLoansList.js, src/components/EditSections/EditUserInfo/components/ChangeUserTypeModal/ChangeUserTypeModal.js, src/components/EditSections/EditUserRoles/components/CheckboxColumn/CheckboxColumn.js, src/components/Loans/components/ActionsBar/ActionsBar.js, src/components/PermissionsAccordion/PermissionsAccordion.js, src/components/PermissionsAccordion/components/CheckboxColumn/CheckboxColumn.js, src/views/LostItems/LostItemsListContainer/components/LostItemsList/components/InstanceDetails/components/ShowLongContentInPopover/ShowLongContentInPopover.js
[UIU-3141](https://folio-org.atlassian.net/browse/UIU-3141) - refactor away from default props for functional components. …
=> UIU-3141 - refactor away from default props for functional components.

CHANGELOG.md
As per https://folio-org.atlassian.net/browse/UIU-3306
=> Release details for v11.0.10 patch release

CHANGELOG.md, src/components/Accounts/ViewFeesFines/ViewFeesFines.js, src/components/Accounts/ViewFeesFines/ViewFeesFines.test.js, src/views/AccountsListing/AccountsListing.js, translations/ui-users/en.json
https://folio-org.atlassian.net/browse/UIU-3027
Here we added a column for actions in Fees/fines part.
=> UIU-3027: Update fee/fine actions column UX for accessibility

package.json
Rename permission after BE changes
https://folio-org.atlassian.net/browse/UIU-3309
Associated with https://github.com/folio-org/ui-users/pull/2837
=> UIU-3309: Rename permission after BE changes

CHANGELOG.md, src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/data/reports/CsvReport.js, src/components/data/reports/FeeFineReport.js, src/components/data/reports/FinancialTransactionsReport.js, src/components/data/reports/RefundReport.js, src/components/data/reports/cashDrawerReconciliationReportCSV.js, test/jest/__mock__/stripesComponents.mock.js, test/jest/__mock__/stripesUtils.mock.js
Change import of `exportToCsv` from `stripes-util` to `stripes-components`
[UIU-3202](https://folio-org.atlassian.net/browse/UIU-3202)
=> UIU-3202 Change import of `exportToCsv` from `stripes-util` to `stripes-components`

CHANGELOG.md, src/components/EditSections/EditContactInfo/EditContactInfo.js
`MultiSelection` creates unique `key` attributes for its options with a default function of
```
(option) => option ? option.label : ''
```
but the `label` attribute here is a `<FormattedMessage>`, leading that function to serialize all options as `[object Object]`. Since we know the `value` attribute here is a unique string, we use that instead.
Refs [UIU-3312](https://folio-org.atlassian.net/browse/UIU-3312)
=> UIU-3312 provide itemToString to correctly serialize options

package.json
- Follow-on from [[UIU-3301] Improve capability sets for role assignment/unassignment](https://github.com/folio-org/ui-users/pull/2833) and [[UIU-3301] Add ui-users.view as subpermission to roles permission sets](https://github.com/folio-org/ui-users/pull/2839)
- Added missing subpermission `ui-users.edit` to `ui-users.roles.manage` as reported by QA. This makes sense to add since you cannot manage user roles on the User detail screen. You must be on the Edit User screen, so without this subpermission, manage user roles is inaccessible.
=> [UIU-3301] Add missing .edit subpermission to roles.manage.

CHANGELOG.md, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.js, src/components/Accounts/ChargeFeeFine/ChargeFeeFine.test.js, src/components/Accounts/ChargeFeeFine/ChargeForm.js, src/components/Accounts/ChargeFeeFine/ChargeForm.test.js, src/components/Accounts/ChargeFeeFine/ItemInfo.js, src/components/Accounts/ChargeFeeFine/ItemInfo.test.js, src/constants.js, translations/ui-users/en.json
Return appropriate error message when item for manual fee/fine can't be found.
Disable "Charge" and "Charge and pay" buttons if error is presented.
[UIU-2701](https://folio-org.atlassian.net/browse/UIU-2701)
=> UIU-2701: Return appropriate error message when item for manual fee/fine can't be found

CHANGELOG.md, package.json, src/components/EditSections/EditUserInfo/EditUserInfo.js, src/components/util/util.js, src/components/util/util.test.js, src/views/UserEdit/UserForm.css, src/views/UserEdit/UserForm.js, src/views/UserEdit/UserForm.test.js, translations/ui-users/en.json
Add `pronouns` field to user edit view and display `pronouns` in its header alongside with user's name if they're present.
https://folio-org.atlassian.net/browse/UIU-3119
=> UIU-3119: Pronoun Field - User Record Edit

CHANGELOG.md, src/components/Loans/ClosedLoans/ClosedLoans.js, src/components/Loans/ClosedLoans/ClosedLoans.test.js, src/components/Loans/OpenLoans/OpenLoansControl.js, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.js, src/components/Loans/OpenLoans/components/ActionsDropdown/ActionsDropdown.test.js, src/components/Loans/OpenLoans/components/ContributorsView/ContributorsView.js, src/components/Loans/OpenLoans/helpers/getListDataFormatter.js, src/views/LoanDetails/LoanDetails.js
Add functionality for handling absence of `loan.item` property in a case when item was deleted or data were corrupted.
[UIU-2531](https://folio-org.atlassian.net/browse/UIU-2531)
There is a Sonar issues related to analysis generation. Working on fixing it.
=> UIU-2531: Implement support for loans without item for Loan Detail

CHANGELOG.md, src/components/EditSections/EditContactInfo/EditContactInfo.js
An attempt to access `option.value` within `itemToString` prop fails when `option` is `null` or `undefined`. An optional chaining operator + fallback value is added to resolve this behavior.
https://folio-org.atlassian.net/browse/UIU-3335
=> UIU-3335: "Preferred email communications" field clicking causes error

CHANGELOG.md, src/hooks/useUserAffiliationRoles/useUserAffiliationRoles.js, src/hooks/useUserAffiliationRoles/useUserAffiliationRoles.test.js
Refs [UIU-3355](https://folio-org.atlassian.net/browse/UIU-3355) 
We retrieve `assignedRoleIds` by calling `users/roles`, but it returns only ids. To sort them correctly, we need a way to get the names of the roles.
Just retrieve all roles for each tenant, find the names of the assigned role ids, and sort roles alphabetically. 
Ideally all of the PRs …
=> UIU-3355: Assigned roles are not sorted in user edit view when roles assigned via roles UI or via API

CHANGELOG.md, src/components/EditSections/EditExtendedInfo/EditExtendedInfo.js
https://folio-org.atlassian.net/browse/UIU-3264
Here we add a timezone prop to `Datepicker` to fix the problem with different values in `view` and `edit` of `enrollement date`
=> UIU-3264: Field "Date enrolled" showing 1 day earlier in View than Edit

CHANGELOG.md, src/components/EditSections/EditUserInfo/EditUserInfo.js
There was a PR associated with this ticket already but it didn't cover the same issue within the `EditUserInfo` component.
https://folio-org.atlassian.net/browse/UIU-3352
=> UIU-3352: [Follow-up] Fix incorrect date display in 'EditUserInfo' due to unspecified timezone

src/components/UserDetailSections/ExtendedInfo/ExtendedInfo.js, src/components/UserDetailSections/ExtendedInfo/ExtendedInfo.test.js, src/views/UserDetail/UserDetail.js
Display the departments field if at least one department is added in Settings (follow-up PR).
https://folio-org.atlassian.net/browse/UIU-3122
With the "department name" field
Without it
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is …
=> UIU-3122: ExtendedInfo - display the departments field if at least one department is added in Settings (follow-up).

CHANGELOG.md, package.json, src/constants.js, src/settings/CustomFieldsSettings.js, src/views/UserDetail/UserDetail.js, src/views/UserEdit/UserForm.js
Custom field components in stripes-smart-components have already been migrated to mod-settings. It is just necessary to pass the `scope` property and create the permissions.
https://github.com/folio-org/stripes-smart-components/pull/1586
[UIU-3411](https://folio-org.atlassian.net/browse/UIU-3411)
Ideally all of the PRs involved in breaking changes would be …
=> UIU-3411: Migrate custom fields from mod-configuration to mod-settings.

CHANGELOG.md, package.json, src/constants.js, src/settings/CustomFieldsSettings.js, src/views/UserDetail/UserDetail.js, src/views/UserEdit/UserForm.js
Revert migration of custom fields __title__ from mod-configuration to mod-settings due to lack of data migration on the BE side for the Trillium release.
https://folio-org.atlassian.net/browse/UIU-3441 …
=> UIU-3441: Revert migration of custom fields title from mod-configuration to mod-settings.

CHANGELOG.md, package.json, src/components/Wrappers/withUserRoles.js
- Cherry-picking work from [UIU-3426](https://folio-org.atlassian.net/browse/UIU-3426) into patch `12.1.10` so it can be included in `Sunflower R1 2025 Service Patch`.
- This includes both https://github.com/folio-org/ui-users/pull/2948 and https://github.com/folio-org/ui-users/pull/2950.
=> B12.1 patch [UIU-3426]

CHANGELOG.md, src/views/UserEdit/UserForm.js, src/views/UserEdit/UserForm.test.js
Hide the `TenantsPermissionsAccordion` and `EditUserRoles` components from displaying on the user create page.
This PR addresses an issue where permissions and roles accordions were incorrectly displayed on the user create page, when they should only appear during user editing.
https://github.com/user-attachments/assets/39b93200-667e-49cb-b034-b722a99c1c8c
[UIU-3449](https://folio-org.atlassian.net/browse/UIU-3449)
=> UIU-3449: Hide permissions and roles accordions on user create page

CHANGELOG.md, package.json, src/components/ModalContent/ModalContent.js, src/components/ModalContent/ModalContent.test.js, src/constants.js
Add support for use circulation-bff for mark-as-missing
https://folio-org.atlassian.net/browse/UIU-3444
=> UIU-3444: Add support for use circulation-bff for mark-as-missing

src/routes/UserSearchContainer.js, src/routes/UserSearchContainer.test.js, src/views/UserSearch/UserSearch.js
1. Remove the total records display in the results list when the query and filters are empty.
2. Fetch actual total records when there is a query and selected filter, and then a user unselects the filter.
[UIU-3387](https://folio-org.atlassian.net/browse/UIU-3387)
1. Call the `this.resetActualTotalRecords();` in the `componentDidUpdate` when `query` or `filters` have changed and they are both empty.
2. Remove the `resources.query.query` and `resources.query.filters` from `componentDidUpdate`.
https://github.com/user-attachments/assets/1da82d05-0fcb-4687-a74e-6cc538a67dab
If there are breaking …
=> UIU-3387: Reset total records on query and filters removal (follow-up PR).

CHANGELOG.md, src/components/data/static/loanActionMap.js, src/components/data/static/loanActionMap.test.js, translations/ui-users/en.json
Add translations for use-at-location actions (Held for use at location, Picked up for use at location), which appear in the history of actions in the detail page for one of a user's loans.
=> [UIU-3420] use-at-location action translations
